### ISSUE TITLE
TEI feature request for `@hand` on `<stage>`

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#1]
Original ticket:

The Douai team want to encode hand shifts, but their handshifts align perfectly with the document hierarchy (e.g. hand 2 is responsible for adding `<stage>` directions). Using the standoff `<handShift/>` is a bit ugly in this context, and what would be much better would be to use e.e `@hand` on `<stage>`, but it's not available; the range of elements bearing `@hand` (att.written) is very small.

What have people done about this? Does it make sense to create a feature request to broaden the availability of `@hand`, or should we just use an existing global attribute (`@resp` springs to mind) to do the same job?

Current status:

The TEI FR is in progress, and @JanelleJenstad is working on it:

https://github.com/TEIC/TEI/issues/2197

**Comment by martindholmes** [comment]
We currently have a customization in place for this, but as soon as TEI releases a version incorporating the change, we can remove that.

**Comment by JanelleJenstad** [comment]
Update: Stage has been added to att.written for the forthcoming TEI release. Release starts April 19.

**Comment by martindholmes** [comment]
Excellent. Action on us would be to remove our customization once it's not needed.

**Comment by JanelleJenstad** [comment]
@martindholmes: Reminder that we can now remove our customization and close this ticket.

**Comment by martindholmes** [comment]
@JanelleJenstad Thanks for the reminder. Done, and closing.
