### ISSUE TITLE
FR: Implement ptr instead of ref for linking between documentation files

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#10]
In documentation files (files starting with learn_), we often link to other documentation files. 

Normal encoding:
`<ref target="doc:learn_terminal"><title level="a">Work in the Command Line (Terminal)</title></ref>`

I want to check that the text node of `<ref><title>` matches the text node of the `<head>` that is the child of the `<div>` to whose xml:id we are pointing. 

Sometimes we point to child divs:
`<ref target="doc:learn_terminal#learn_terminal_commands"><title level="a">Terminal Comamnds: Reference Table</title></ref>`
So we need to specify child `<head>` of a `<div>` rather than child `<head>` or the root `<div>`.

I always wrap `<ref>` around `<title>`. I can't guarantee that other writers of documentation haven't wrapped <title> around <ref> so maybe we should write the diagnostic to work with both encoding patterns (although perhaps that is something we can constrain).

**Comment by martindholmes** [comment]
@JanelleJenstad: I'm sure we talked about this at the last meeting, but maybe you weren't there. I think the way to do this is to use a ptr element that gets expanded at build time with the appropriate document title. That saves you from having to track down every instance of a title when you change it in the original. You would then only use a ref element if for some reason you wanted to provide a different title from what's in the actual document. If that's never likely to happen, we can just prevent ref elements from pointing to documentation divs, and insist on ptr. 

Does that make sense?

**Comment by JanelleJenstad** [comment]
Yes it does! (And I do remember that conversation, now that you've pinged my memory.) 

So does this ticket then become a feature request? You can probably use some of the processing we already have elsewhere for turning `<ptr>`s into ASL or ASSP, and tweak it to supply the content of `<head>`

We would never want to provide a different title than the one in the actual document.

**Comment by martindholmes** [comment]
Yes, let's make this a feature request.

**Comment by JanelleJenstad** [comment]
@martindholmes: The FR request is as follows:

### What we'd like to do: 
In documentation files, use pointers in our encoding and have the processing supply the heads of other documentation divs, wrapped in `<title level="a">` and processed as article titles. This would save us time in the encoding of documentation and ensure that our titles in documentation match the `<head>` elements. 

### Encoding:
In documentation, we want to be able to use the `<ptr type="localCit" target="doc:fileID"/>` (or the value "doc:fileID#divID") to point to other documentation that we want users to read. (Comparable to what we are doing with pointers to generate paragraph numbers, ASSP, or ASL in our print and digital texts.)

### At processing 
We'd like you to supply the text node of the child `<head>` element of the `<div>` and treat it as an article title (as it were wrapped in <title level="a">. For now, that means curly quotation marks around the title in the rendering.

**Comment by martindholmes** [comment]
@JanelleJenstad @nvatcher I've committed a preliminary implementation in rev 8162; it doesn't require any special attribute on the ptr element, but just assumes that if 'learn_' appears in the `@target`, then it should expand the element using the title from the target div's head element. It does this at an early stage of the documentation rendering, simply replacing the ptr with a ref element in the TEI, so the HTML rendering just happens as before.

However, there are a couple of questions to resolve. There are lots of ref elements that look like this:

```
<ref target="#subversion_linux_commit">see below</ref>
```

where you presumably don't want the title to be substituted. This seems perfectly reasonable to me, so presumably those particular ref elements should not be replaced with ptr elements when we switch over; only the ones which have a `child::title[@level='a']` should be converted to pointers. Is that right?

The other question is what should happen if there is no target div element, or if there is one but it has no `child::head`. Should we fail the build immediately, or just add some sort of warning?

**Comment by martindholmes** [comment]
@JanelleJenstad @nvatcher I've now converted all ref elements which contained title elements and were pointing at documentation divs into ptrs. You still have the option to use a ref element if you want custom text that's going to become the link, but otherwise just use a ptr and the title should be filled in automatically at build time.

**Comment by martindholmes** [comment]
@JanelleJenstad @nvatcher If you're happy with this, please close the ticket, otherwise let me know what more is needed.

**Comment by JanelleJenstad** [comment]
@martindholmes: We're happy. Thanks very much!
