### ISSUE TITLE
Anthology status report handling of pages not intended to be published

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#100]
If editors create pages in the anthology folder, the assumption of the anthology build process is that those pages should be included in the anthology itself, so they show up with warnings in the anthology build report when they don't have published status, even when they're not meant to be published yet and aren't linked from any menu or other page.

We need to rethink this to achieve several objectives:

 - Pages not intended to be published in the anthology at all need to be identified somehow (catRef?) so that warnings are not issued for them;
 - Where such pages exist, the included pages and menus need to be checked to ensure there are currently no links to them, and if links exist, an error needs to be raised in the anthology report;
 - The report needs to include an appendix which lists all pages marked not to be published, not as errors but just for information purposes.

**Comment by martindholmes** [comment]
Rethinking this, I'm wondering if it's just overkill. If you want to create a document which you're still working on but don't want to publish yet, you can just name it with the extension .xm_. That means you'll have to validate it manually, but it must be a fairly rare situation that you're coming up to the publication of an issue of an anthology, but you still have documents floating about that you don't want to publish yet.

@JanelleJenstad Can you give me an example of a real case of this, and run me through the logic of creating a document in the anthology that you don't want to publish in the next edition of the anthology?

**Comment by LEMDO-PM** [comment]
Add to anthology diagnostic a check to make sure that `<ptr>`s are linking to files that will be published and that are in the same edition.

**Comment by martindholmes** [comment]
@LEMDO-PM which `<ptr>`s do you mean? This ticket is about site pages like about pages; I think the origin of this ticket is that the anthology diagnostics are ignoring the `revisionDesc/@status` on anthology information pages and just assuming they're ready for publication. I haven't confirmed that yet, though.

**Comment by LEMDO-PM** [comment]
I think it was any pointers - we don't want to point from one file to a different file if the second file isn't published yet.

**Comment by martindholmes** [comment]
Oh, that's a completely different thing from this ticket. But I think this ticket is bogus anyway; the anthology diagnostics already check the published status of anthology pages as they should. So I don't know what the problem is here. Nobody should create an XML document inside the anthology folder for any other reason than to publish it at some point in the anthology. I'm going to close this.
