### ISSUE TITLE
Collation styling

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#101]
As we did last minute proofreads for the MoMS release, we had a few questions about styling on collations come up ([GitHub Issue 99](https://github.com/projectLEMDO/lemdoIssues/issues/99)) that I'll triage here:

- We are including annotations-only and collations-only pages in each anthology's edition page. This means that we'll want styling and processing for these pages.
- For collation popups: We would like `<rdg>` and `<lem>` to be styled the same (same font-family and font-size).
- For collations-only pages: 
1. We like the top border that Martin added over `<lem>` to distinguish between collations and would like to keep it.
2. We would like the font-family and font-size to match those in the popup.
3. We are hoping that Pat or Martin can come up with a great solution for displaying witness info on the collations-only pages.

**Comment by martindholmes** [comment]
I've added a fix to make rdg the same size as lem in popups, in rev 11980.

**Comment by pszpak** [comment]
Can you provide me with an example page on Jenkins of where this styling needs to be done?

**Comment by LEMDO-PM** [comment]
Two examples of collation-only pages: emdDEVI3_M_collation and emdH5_FM_collation both have collation pages linked to from their edition pages. The collation popups are in the associated modern files: emdDEVI3_M and emdH5_FM.

**Comment by pszpak** [comment]
I thought I'd be able to see the issue. Can you take a screen cap of it?

**Comment by LEMDO-PM** [comment]
Here are screenshots of the collation-only page and the same collation in the popup for emdDEVI3_M_collation.

![Collation-Only](https://user-images.githubusercontent.com/116194494/211414505-65579eff-7683-43a3-ae09-302d1d0c7763.png)
![Collation-Popup](https://user-images.githubusercontent.com/116194494/211414944-5469e8a3-20bd-4742-999e-f3a785ba3824.png)

Martin has made the <lem> and <rdg> elements the same size and added horizontal lines, but the font on the collation-only page and the popup seems to be different. The witness names in the collation-only page are sans-serif while the witness names are serif (we want the serif font for both) and the text appears to be in different fonts (we want the usual Alegreya serif font for both).

If you have a minute, feel free to pop over and we can take a look together. I'm in HCMC all afternoon :)

**Comment by pszpak** [comment]
Should be fixed as of 12080.
