### ISSUE TITLE
Allow birth, death, and gender elements

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#102]
We would like to add `<birth>`, `<death>`, and `<gender>` elements to use in PROS1. We haven't really developed PROS1 yet and we want to be set up to do so as we need better metadata capture for authors, printers, publishers, playhouse personnel, patrons, etc.

For `<birth>` and `<death>`, we would also like to add some of the suite of attributes that you created for MoEML: `@when-custom`, `@not-before`, and `@not-after`.

**Comment by martindholmes** [comment]
Elements added in rev 12001.

**Comment by martindholmes** [comment]
We need to figure out what the rather odd combination of custom and non-custom dating attributes is all about. Up to now, LEMDO only uses the standard `@when`, `@notBefore`, `@from` etc. attributes. If we're going to switch to using custom attributes and calendars as MoEML does, that's a fairly major change, and it comes with drawbacks:

https://www.researchgate.net/publication/287218344_Encoding_historical_dates_correctly_is_it_practical_and_is_it_worth_it

Meanwhile, I need to figure out why `<gender>` is not showing as available even though it's in the schema.

**Comment by martindholmes** [comment]
Figured it out. We had pinned our schemaSpec to P5 version 4.4.0 for some reason.

**Comment by martindholmes** [comment]
@JanelleJenstad @LEMDO-PM What's the plan for dating attributes? We currently don't use the custom dating attributes in LEMDO, I think on the basis that dates have not been particularly significant for this particular project and the messiness with Julian calendars is not worth poking at. Is that going to change?

**Comment by JanelleJenstad** [comment]
It's potentially very messy! We have:
- legacy files where there's no documentation about the treatment of dates or the source of the date
- transcribed documents
- critical paratexts
- modernized editions

I don't think it's feasible to devise a dating system that will allow us to capture all the possible calendrical scenarios and ambiguities we are likely to encounter. Furthermore, as we discovered with MoEML, even major sources like the ODNB tend to treat proleptic and ahistorical dates as facts, with the maddening result that we don't know what dates signify in secondary sources. (The Queen Elizabeth I example comes to mind yet again. She died on March 24, 1602 by her calendar but no historian ever says that she died in any year other than 1603. It's now "fact" that she died in 1603.)

Furthermore, our research questions thus far haven't depended on precise understandings of dates and calendars. For LEMDO, it's more important to acknowledge our sources; 

I think it's more important to:
- indicate the source of the date (not necessarily on the date element itself; the parenthetical bibl ref will suffice); 
- indicate at the anthology level how dates are treated ("dates have been transcribed as they appear in the source documents; dates in critical paratexts are quoted from secondary sources / have been normalized to proleptic Gregorian" or something like that)

**Comment by JanelleJenstad** [comment]
In short, it is worth having a suite of custom dating attributes for MoEML where we do documentary editions. LEMDO does not need them.

**Comment by martindholmes** [comment]
@JanelleJenstad @LEMDO-PM In that case, I believe this issue is complete, so I'll close it.
