### ISSUE TITLE
CodeSharing Tool for LEMDO

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#103]
This is truly a Blue-Sky issue. Is it possible to create a CodeSharing Tool like the one that used to run on MoEML? It would be enormously useful for LEMDO, both for internal use (to check consistency) and for editors to see lots of examples. IIRC, the CodeSharing Tool was written to work with eXist, which we no longer use.

**Comment by martindholmes** [comment]
We can't have CodeSharing without an eXist back-end, unless we write something analogous to staticSearch just to retrieve and render random blocks of XML. If CodeSharing had got a lot of use, I would have mourned its passing, but when anyone can learn the XPath to find any XML structure in the entire repo in Oxygen within an hour, it seems like overkill to run a special server for it. For internal consistency checking, Schematron and diagnostics are the tool of choice, and I think I'd rather spend time teaching useful XPath skills than writing another tool that helps people avoid learning simple and useful things.

**Comment by JanelleJenstad** [comment]
Agreed. Closing this ticket and looking forward to practicing XPath.
