### ISSUE TITLE
Add styling for semi-diplomatic transcriptions

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#105]
Please add styling for semi-diplomatic transcriptions (a.k.a. old-spelling or OS files). See the attached files for the feature request and an XML tree for semi-diplomatic transcriptions. Janelle has also emailed these to you.

I'm (Navarra) happy to look over this with you and answer questions either in HCMC (I'll be working in there on Mondays and Wednesdays) or via GitHub/Teams/email :-)

[FeatureRequest_CSSforOS.docx](https://github.com/projectLEMDO/lemdoIssues/files/10415321/FeatureRequest_CSSforOS.docx)
[OS_Texts_XML_Tree_body.pdf](https://github.com/projectLEMDO/lemdoIssues/files/10415326/OS_Texts_XML_Tree_body.pdf)

**Comment by pszpak** [comment]
Hey Navarra,

Let's get this done when you come in on Monday.

**Comment by LEMDO-PM** [comment]
References:
emdH5_Q1 (I did the code for this in the fall)
learn_encodeStyleCSS (intro documentation for encoders)
learn_encodeStyleDefault (more documentation on default styling for encoders)

These should apply only for things with `<catRef scheme="tax:emdEditorialTreatments" target="cat:letOldSpelling"/>`

**Comment by LEMDO-PM** [comment]
@pszpak, @martindholmes: is this expected fallout for the new styling?
![image](https://user-images.githubusercontent.com/116194494/212967281-2e2b842b-07c5-43fb-99ca-30de235961c9.png)

**Comment by pszpak** [comment]
No that was my error. It'll be fixed next build.

**Comment by LEMDO-PM** [comment]
Great, thanks!

**Comment by pszpak** [comment]
I'm going to close this, not because it is done but because it's a bit broad in scope. Let's break this down into individual (as much as possible) specific issues (like the page break issue or the list issue).
