### ISSUE TITLE
Remove added space before supplied

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#107]
There is a space being added before square brackets on supplied material (encoded in xml as `<supplied>`, turns into HTML `<span data-el="supplied">`). Please remove the added space. Example in emdFBFB_Q1#emdFBFB_Q1_sp434.

**Comment by martindholmes** [comment]
This is not a space; it's a margin-left setting from the CSS:

~~~~~
span[data-el="supplied"]{
	margin-left: .25rem;
}
~~~~~

on line 2035 of lemdo-dev.scss. It was added by @pszpak in rev 11219, with this message:

~~~~~
------------------------------------------------------------------------
r11219 | pszpak | 2022-11-02 11:37:19 -0700 (Wed, 02 Nov 2022) | 1 line

adds margins to deta-el supplied spans so they don't smash up against other words
------------------------------------------------------------------------
~~~~~

which I presume was in response to a request from someone else. @pszpak do you remember who asked for this?

**Comment by pszpak** [comment]
Space removed.
