### ISSUE TITLE
Add processing for resp in documentation

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#108]
Render local responsibility statements (i.e., values from `@resp` in the file itself) first in the credits tab in the side bar for documentation pages.

Please also add Navarra Houldin (HOUL3) as project manager to the respStmts for documentation pages.

**Comment by martindholmes** [comment]
First implementation committed in rev 12146. If all is working we can close this.

**Comment by martindholmes** [comment]
Seems to be working fine, so closing.
