### ISSUE TITLE
Add Schematron to require localCit

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#109]
Write Schematron that `<ptr>` must always have `@type="localCit"` when it is not a descendant of `<linkGrp>`. Keep in mind that we only use `@type="localCit"` when pointing within an edition, so the `@target` value will always include the play ID (emd...)

(Navarra can attempt this one)

**Comment by martindholmes** [comment]
@LEMDO-PM How are you doing on this one?

**Comment by LEMDO-PM** [comment]
@martindholmes There are four `<ptr>`s that aren't descendants of `<linkGrp>` that don't have `@type="localCit"` on them. I can fix those tomorrow or Friday and add the Schematron on Monday. This is what I currently have for the XPath: `//ptr[not(contains(@type, 'localCit'))][not(ancestor::linkGrp)]`, but I get an error if I try to add `descendant::` rather than `//` (something about an unexpected axis).

**Comment by martindholmes** [comment]
I would do not(@type = "localCit"). Why might that be better?

**Comment by LEMDO-PM** [comment]
Would that make it more specific/prevent it from potentially picking up any other @type values? It also makes it look neater.

**Comment by martindholmes** [comment]
It's a very minor thing and it really makes no difference, but I always think that [contains(@type, 'localCit')] is assuming the presence of @type. It won't generate an error, though.

Anyway, the more important thing is that you don't need descendant:: or // for a Schematron rule. You're writing a `@context` attribute, not an XPath to parse a document. The `@context` attribute is like an XSLT `@match` attribute. Schematron doesn't go looking for things; its context is just evaluated to see if it matches or not, at any given point in the document.

**Comment by LEMDO-PM** [comment]
@martindholmes I've written the constraintSpec and run the ant quickValidateSource (successful), but when I try to break the rule I don't get an error message. Could you please come over and take a look when you get a chance?

**Comment by LEMDO-PM** [comment]
Done! Committed with rev 12328. Closing this issue.
