### ISSUE TITLE
Add diagnostic for files that need proofing

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#11]
### Name of diagnostic: 
Remediated files that need proofing

### To list in the diagnostic:
All files that have `@status="IML-TEI_proofing"` on `<revisionDesc>`

**Comment by martindholmes** [comment]
Does this need a diagnostic? You can just right-click on data/texts and search for that status value to get a list of documents. Do we want to add more time to the build for that?

**Comment by JanelleJenstad** [comment]
Good point. We already have a Diagnostic that checks for this at the Anthology diagnostics level (i.e., files that don't have the @status="published"). That's probably a better place for it since my team does not want to do the proofing if we don't have to. 

Closing this ticket.
