### ISSUE TITLE
Add Schematron to require head element

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#111]
Write Schematron to require `<head>` as a child of `<div>` when the `<div>` has an xml:id. Exclude files if their `@status` on `<revisionDesc>` is `"prgGenerated"`, `"TCP-TEI"`, or `"IML-TEI"`.

**Comment by LEMDO-PM** [comment]
@martindholmes I'm getting errors when I try to ant quickValidateSource my Schematron for this. I'm going to comment it out for now so that I don't break everything. Is there any chance that you could take a look at it or we could take a look at it together to figure out where I'm going wrong? You can find it by searching ident="div.mustHaveHeadIfNotASSp".

We want this rule to apply to all divs that don't have any ASSp stuff in their xml:ids (so it needs an `@xml:id`, but shouldn't have ASSp numbers).

**Comment by martindholmes** [comment]
@LEMDO-PM The problem was that the sch:assert element was a following-sibling of the sch:rule rather than a child of it, which resulted in broken XSLT when the Schematron was compiled. I've fixed that, and made one other tweak -- I always avoid // in favour of descendant:: as a matter of policy, because // can cause problems in certain contexts. I'm testing now, and I'll commit if it works and if all files are valid against it.

**Comment by martindholmes** [comment]
Committed the change because I have to shut down and change locations. Build might break if there are any instances of this error.

**Comment by LEMDO-PM** [comment]
Thanks!!

**Comment by LEMDO-PM** [comment]
@martindholmes We're getting errors in the anthology search pages (e.g., qme_search, moms_search). There are empty divs in those files with `xml:id="staticSearch"`. What do those divs do/do we need them?

**Comment by martindholmes** [comment]
@LEMDO-PM Without those divs, there is no search. We'll have to make an exception for them. I'll add something to the Schematron to do that.

**Comment by martindholmes** [comment]
Done in rev 12187.

**Comment by martindholmes** [comment]
This turns out to be impractical, because of the many divs generated at build time.

**Comment by martindholmes** [comment]
I've removed the Schematron and added a diagnostic instead, in rev 12214. If all is well, this can be closed.

**Comment by LEMDO-PM** [comment]
Fantastic, thanks for that solution!

**Comment by martindholmes** [comment]
Closing now, since all seems to be well.
