### ISSUE TITLE
Write Schematron to disallow ab as a child of sourceDesc

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#112]
We do not want `<ab>` as a child of `<sourceDesc>`. People should use `<p>` instead. Please:
1. Replace `<ab>` with `<p>` when it is a child of `<sourceDesc>`.
2. Add Schematron to forbid `<ab>` as a child of `<sourceDesc>`.

**Comment by martindholmes** [comment]
@LEMDO-PM There's a better way to handle this than Schematron. We should modify the content model of sourceDesc to allow only the things we actually want in the configuration we want them. Right now, we have the following children of sourceDesc:

p
ab
bibl
msDesc
listWit
biblStruct (evil to be eradicated)
biblFull (why?)

We should decide which elements we want to allow, in which combinations, and write a proper content model in the ODD.

**Comment by LEMDO-PM** [comment]
That sounds good. I'm working my way through our biblStruct instances now, I'll see what I can do about biblFull once I've removed the evil biblStruct.
We currently seem to be using biblFull in sourceDesc when we pull metadata in from GitHub rather than encoding our own metadata.

**Comment by martindholmes** [comment]
@LEMDO-PM In order to make some progress on this ticket, I'm going to assume we're stuck with biblFull for now, and rewrite the content model of sourceDesc accordingly.

**Comment by martindholmes** [comment]
Completed in rev 12775. When biblFulls are all gone, that can be removed from the sourceDesc content model.

**Comment by LEMDO-PM** [comment]
Thanks @martindholmes! This one fell off my radar for a bit, I'll go in and remove them tomorrow (I only see six of them when I run XPath across the data folder, it shouldn't be a massive task for me to do).

**Comment by martindholmes** [comment]
@LEMDO-PM When you've done that, you could look at lemdo.odd, find the declaration of the sourceDesc content model, remove biblFull and rebuild the schema. A gentle intro to ODD content models. :-)

**Comment by LEMDO-PM** [comment]
@martindholmes I've gotten rid of biblFull in the data portfolio, but there are a few instances in the code/conversions/tcp portfolio. Do I need to/can I get rid of those as well?

**Comment by martindholmes** [comment]
If you want to removed biblFull from the schema, you will. Is there any reason to keep them?

**Comment by LEMDO-PM** [comment]
I don't think so, but I'm not sure what the files are doing there. One of them is currently full of validation errors (emdRho_Q1, which seems to be different from the emdRhoQ1 that lives in data/texts, has 567 errors). So I'm not sure what the fallout of me doing things to those files and committing them would be.

**Comment by LEMDO-PM** [comment]
Ah... I also see that I was getting an XPath successful message at the bottom of the screen before it was actually done. There are also a pile of biblFull elements in the working_files/LEMDO_F1 folder. I also have no idea what this folder is and these files all seem to have validation errors as well. I'm going to hold off on removing biblFull from the schema.

**Comment by JanelleJenstad** [comment]
I'm going to look into why we have two different Rho Q1 files. The <biblFull> in that file will have come from the EEBO-TCP transcription. 
The F1 folder contains a bunch of files that Joey (?) made from the EEBO-TCP transcription of the 1623 first folio. In the early days, we were wondering if it might be simpler to redo the semi-diplomatic transcriptions from EEBO-TCP than try to remediate what we'd inherited from the ISE. The answer turned out to be "no." I suggest we save that folder to the shared LEMDO drive and then remove the folder from the repo.

**Comment by LEMDO-PM** [comment]
Great. I'll move the LEMDO_F1 folder to the shared drive and delete.
