### ISSUE TITLE
Allow binary docs

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#113]
We need a place to store binary documents (e.g., PDFs) in the repo, a prefix for linking, and processing to make the link work.

**Comment by martindholmes** [comment]
Added a new prefixDef "bin:" in rev 12168.

**Comment by martindholmes** [comment]
Added a new folder data/binaries in rev 12169.

**Comment by martindholmes** [comment]
Remaining required changes done AFAICS by rev 12174.

**Comment by martindholmes** [comment]
We have our first test case in place, so by tomorrow we should be able to see whether the link in HW is correctly rendered, and whether the PDF itself is copied into the lemdo-dev and dre anthologies.

**Comment by martindholmes** [comment]
Working in the lemdo-dev build. Since we're not building DRE by default, I'll have to do a test build of it locally to see if the second part of the equation is working.

**Comment by martindholmes** [comment]
Tested, found a bug, fixed the bug in rev 12191. Closing this now.
