### ISSUE TITLE
Need a list of allowed extensions for non-image binaries

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#114]
Issue #113 allows editors to include and link to binary files such as PDFs, but we obviously need a highly-constrained list of file types that we're willing to allow. I'm inclined to say that the only file type we should allow is PDF, until we're given a strong case for a different type. Definitely no Office docs or anything like that; they can be turned into PDFs if required. @JanelleJenstad @LEMDO-PM can you think of any other type we should consider at this point?

**Comment by JanelleJenstad** [comment]
I agree. PDF only.

**Comment by LEMDO-PM** [comment]
PDF sounds good to me as well!

**Comment by martindholmes** [comment]
Fix committed in rev 12248. If all is well, this can be closed.

**Comment by martindholmes** [comment]
Added Schematron to enforce this in rev 12275. Closing now.
