### ISSUE TITLE
Style Dropcaps

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#115]
Please adjust the styling for dropcaps in files with catRef "letOldSpelling" so that wide letters such as 'W' aren't cut off by the box. For an example, see emdHam_Q2_sp1 on the lemdo-dev site.

Here is a picture of what is currently happening:
![Dropcap-Ham_Q2](https://user-images.githubusercontent.com/116194494/214728684-7a586fc9-9345-493f-a9ab-f610d70fe66f.png)

**Comment by pszpak** [comment]
Should be fixed on the next build.
