### ISSUE TITLE
Have quotation marks render for quote elements in modern text prose

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#116]
I noticed there are no quotation marks being rendered where expected in emd1HW_M_a4_s2_sp9. The word "Murder!" is wrapped in the `<quote>` element in the .xml file but looks like this on the site:
![image](https://user-images.githubusercontent.com/116194494/215228322-61d3189a-a6d3-47b3-b906-da5905328c96.png)

I looked at a few other instances of `<quote>` in modern texts and saw that quotation marks are not rendering in prose speeches (i.e., in when `<quote>` is a child of `<p>` and grandchild of `<sp>`). `<quote>` *is* rendering as quotation marks in verse speeches (e.g., in emdAYL_a2_s1_sp6).

Please change processing so that `<quote>` renders as quotation marks in both prose and verse speeches.

**Comment by martindholmes** [comment]
@LEMDO-PM @JanelleJenstad If I change the `<quote>` element to `<q>` (which I think is more appropriate here -- this is a non-existent person "quoting" another non-existent person -- then the quotes appear. However, if this is a genuine case for the `<quote>` element, then these are the relevant templates:

~~~~~
  <xd:doc>
    <xd:desc>The quote element should be rendered inline, and appropriate
    quotation marks should be supplied. This template is specifically designed
    to handle cases which are not handled by the more complext template below.</xd:desc>
  </xd:doc>
  <xsl:template match="quote[not(ancestor::cit)][ancestor::sp][descendant::lg|descendant::div|descendant::p|descendant::ab|ancestor::l]" mode="tei">
    <xsl:if test="not(@prev)">
      <xsl:text>“</xsl:text>
    </xsl:if>
    <xsl:apply-templates mode="#current"/>
    <xsl:if test="not(@next)">
      <xsl:text>”</xsl:text>
    </xsl:if>
  </xsl:template>

  <xd:doc>
    <xd:desc>
      <xd:p>Taken from MoEML, this template puts an xhtml:q element around a quoted bit of inline text AND places the trailing punctuation within the element.</xd:p>
    </xd:desc>
  </xd:doc>
  <xsl:template match="title[@level='a'] | quote[not(ancestor::cit)][not(ancestor::sp)][not(descendant::lg|descendant::div|descendant::p|descendant::ab)] | soCalled" mode="tei">
    <q>
      <xsl:call-template name="processAtts"/>
      <xsl:apply-templates mode="#current"/>
      <xsl:if test="following::tei:*|text()[1][self::text()] and matches(following::text()[1], '^[,\.]') and not(child::*[self::title[@level='a'] or self::quote or self::soCalled][not(following-sibling::text())]) and (not(ancestor::title[@level='a'] or ancestor::quote or ancestor::soCalled) or not(following-sibling::*))">
        <xsl:value-of select="substring(following::text()[1], 1, 1)"/>
      </xsl:if>
    </q>
  </xsl:template>

~~~~~

There's a lot of fine contextual distinction going on in the first of those templates, but one option would simply be to add "ancestor::p" to the end of that list; I've done that, and it now renders the quotes, but I'm a little concerned there might be some unwanted fallout, so watch out for anything odd with quotes. That change is in rev 12247.

**Comment by JanelleJenstad** [comment]
@LEMDO-PM @martindholmes : I agree that `<q>` is more appropriate here, for exactly the reasons you set out. 

We should tweak the rule, however. `<quote>` inside `<sp>` should be rendered with quotation marks. I think that means deleting `[ancestor::sp]` from the list of exclusions.

**Comment by martindholmes** [comment]
I believe this is working as expected, so I'm closing this.
