### ISSUE TITLE
Change to taxonomy categories required

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#119]
The term Old Spelling is now deprecated, so we should replace letOldSpelling and letModernSpelling with letSemiDiplomatic and letModernized. Obviously there will be huge downstream implications to this, so it needs to be planned carefully.

**Comment by LEMDO-PM** [comment]
@martindholmes, is this a case for XSLT? If so, could we do it together so that I can work on those skills?

**Comment by martindholmes** [comment]
I think it's more a case for search-and-replace, really, since the values concerned are unambiguous. I think we could search-and-replace these values throughout the repository and then see if a build works. However, timing will be tricky; we'll be touching many files that people are actively working on.

**Comment by martindholmes** [comment]
@LEMDO-PM Do you want to connect with editors and see if there's a good time to do this? We only need to worry about editors who are actively working on texts with these categories.

**Comment by JanelleJenstad** [comment]
@martindholmes and @LEMDO-PM : Let's work on finding a good time _after_ Feb. 10. Most of our editors and anthology leads are involved in the SSHRC PG this week and won't have bandwidth to plan for this.

**Comment by LEMDO-PM** [comment]
@JanelleJenstad is there a time that you think would work well for this? I'm in HCMC Monday and Wednesday for the next couple of weeks, but won't be in the lab for a few weeks starting April 12. It would be wonderful if we could do this before I'm away.

**Comment by JanelleJenstad** [comment]
Shall we do it this afternoon? If yes, I'll have to let the editors know to stay out of semi-dip files.

**Comment by LEMDO-PM** [comment]
@martindholmes are you available to do that this afternoon?

**Comment by LEMDO-PM** [comment]
Janelle has suggested that we do this next week instead so that we can give editors at least 24 hours notice. I'll be in HCMC all day Monday and Wednesday; do we want to do this Wednesday? Perhaps in the morning so that we don't interrupt the RA's workflow (unless we want to use this as a learning opportunity for them as well).

**Comment by martindholmes** [comment]
I was out this afternoon. First order of business is to check the CSS and XSLT to see where we use those values processing and styling.

**Comment by martindholmes** [comment]
Also this may break qme custom styles. Are we ready for that?

**Comment by LEMDO-PM** [comment]
No. In that case, we'll wait for QME to release before we do this.

**Comment by martindholmes** [comment]
@JanelleJenstad Can we tell QME that if they don't release by the end of the month, we're going ahead with this anyway, and their styles may need rewriting?

**Comment by LEMDO-PM** [comment]
@martindholmes What still needs done with this? I thought we had already changed to letSemiDiplomatic and letModernized. This is the textClass from emdFBFB_Q1 (which is going out with this release):
![image](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/c768b568-dc66-48a1-ab5c-93b07df4e065)
The styling is fine except for a couple of things that are weird across all anthologies (I've been working on these and should be done very soon). Or am I misunderstanding what needs done?

**Comment by martindholmes** [comment]
@LEMDO-PM You're right, I'd forgotten we did this. I must have intended to close the ticket and (even worse) forgot to record the fact that we did it on the ticket. I'm closing it now.
