### ISSUE TITLE
Anchors preceding terminal punctuation in print output

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#120]
It's quite common for editors to mark the location or end of an annotated section using an anchor placed between a word that's being annotated and some following punctuation, such as a period or a comma. This works well for the HTML output, where the span of text will be linked, and the punctuation will not form part of the link. But when creating PDF output, a footnote number is rendered at the point of the (only or final) anchor, meaning that you see a footnote number preceding the punctuation. This is generally viewed as inelegant in print documents.

Options:

1. Insist that editors move the final anchors to follow terminal punctuation. Not ideal, because they're typically commenting on the text, not the punctuation.
2. Build into the PDF rendering a pre-processing step that moves all anchors that precede punctuation so that instead they follow it. Not trivial, but definitely doable. Can we predict any unwanted fallout from this?
3. Something else???

**Comment by martindholmes** [comment]
This was handled in commits a few days ago: the anchors are now being moved in a pre-processing step in the PDF, and I believe all is working as planned, but I'll hand over to @LEMDO-PM to do a final check of the PDFs and confirm. If they all look good, this can be closed.

**Comment by LEMDO-PM** [comment]
Yes, this is working beautifully. Thanks! Closing now.
