### ISSUE TITLE
Make levels in multilevel lists more distinct

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#123]
When we have multilevel lists we would like a greater indent to distinguish between the levels of the list. I don't know if we should also have different bullet marks beyond the two that we use now. They currently look like this (see learn_linkingMechanisms on the lemdo-dev site):
![Multilevel List](https://user-images.githubusercontent.com/116194494/219206589-988d1371-b700-4fd0-85ec-025c03eb7bcf.png)

This example list is a bit of a beast (I believe currently five levels of nested lists...) and I will rework it, but it is a good example of what happens when we have lists inside of lists, which has popped up in a few places.

**Comment by pszpak** [comment]
Yes I agree this could use sorting out.

**Comment by martindholmes** [comment]
The default indent (--listIndentBornDig) is only 0.25rem, and the list markers are set inside the paragraph, which makes them harder to distinguish:

~~~~~
body[data-catrefs*="BornDig"] main ul, body[data-catrefs*="BornDig"] main ol, body[data-catrefs*="BornDig"] main div[data-el="list"] {
  font-family: var(--primarySerif);
  font-size: var(--paraFontSizeBornDigMobile);
  color: var(--paraFontColor);
  margin: var(--paraMargin);
  margin-left: var(--listIndentBornDig);
  list-style-position: inside;
}
~~~~~

list-style-type is disc for the top level, then circle for all the subsequent levels. I would recommend a bigger indent, moving the list markers outside the text block, and providing a series of distinct markers for (say) four levels.

**Comment by pszpak** [comment]
I've styled these nested lists (disc, square, circle, repeating to 4 levels, with more margin), but I think nesting beyond two levels is confusing. In the example given I would organize it with a series of sub-heading questions to organize the flow chart like meaning. Keep the lists to one level deep for the specifics. Like this:

## Are you linking to something in your own portfolio (your own edition)?

### YES?

- Is your file going to be published as a PDF?
- Are you pointing to a non-canonical reference that cannot be known until the PDF is generated (e.g., page or line numbers)?

If yes to the above, Use the `<ptr>` element and see "How to Encode Pointer Links" for instructions.

### No?

What are you trying to link to?

- An act, scene, or speech: use the `<ptr>` element and the xml:id of the act, scene, or speech.
- A specific point in a text: use the `<ptr>` element and a single anchor.
- A span of text (including a line): use the `<ptr>` element and two anchors.
- A paragraph in your own critical paratexts: use the `<ptr>` element and the xml:id of the paragraph.
- A figure in your annotations or critical paratexts: use the `<ptr>` element and the xml:id of the figure.

**Comment by JanelleJenstad** [comment]
Thanks for this helpful feedback, @pszpak! Your timing is perfect because @LEMDO-PM is revising the chapter this week.
