### ISSUE TITLE
Add default styling for castgroup with braces

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#125]
@martindholmes The encoding pattern isn't quite what I had on the whiteboard. To make the three containers, I've put a castGroup inside the castGroup element. Then we can style the child castGroup as a simple list. The second container is the metamark. The third container is the roleDesc. 

You'll find this encoding in lemdo/data/texts/douai/main/emdDouai_Mac.xml

```
<castGroup>
              <castGroup>
                  <castItem xml:id="emdDouai_Mac_malcolm">
                  <role>Malcolme</role>
              </castItem>
             <castItem xml:id="emdDouai_Mac_donalbain">
                <role>Donalbaine</role>
              </castItem>
              </castGroup>
            <metamark>}</metamark>
           <roleDesc>his sons</roleDesc>
          </castGroup>
```
Reassign to @LEMDO-PM for documentation after we have a plan.

**Comment by martindholmes** [comment]
I don't think we should really do default styling for this, because every case will be different. I think we have to supply the style on a case-by-case basis, no?

**Comment by martindholmes** [comment]
This is what I've gone with in this case, slightly modifying the encoding:

~~~~~
<castGroup style="display: flex; flex-direction: row; align-items: center;">
    <castGroup>
        <castItem xml:id="emdDouai_Mac_malcolm">
            <role>Malcolme</role>
        </castItem>
        <lb/>
        <castItem xml:id="emdDouai_Mac_donalbain">
            <role>Donalbaine</role>
        </castItem>
    </castGroup>
    <metamark style="transform: scaleY(3); transform-origin: center; margin: 0 1em;">}</metamark>
    <roleDesc>his sons</roleDesc>
</castGroup>
~~~~~

**Comment by martindholmes** [comment]
So what we're saying is: there's a row of three items, a castGroup, a metamark, and a roleDesc; they are vertically-aligned to the center; there's a line break between the two cast items; and the parenthesis is stretched. This is fairly plain and comprehensible, and it gives us the required output.

**Comment by martindholmes** [comment]
I think this is probably now a documentation issue; we have a good, simple, working example, and with documentation people can easily follow it.
