### ISSUE TITLE
Add styling for hungwords

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#129]
We would like to add basic styling for hungwords in our semi-diplomatic transcriptions. All files that these will appear in have a `<catRef scheme="tax:emdEditorialTreatments" target="cat:letOldSpelling">` in its `<textClass>`.

We are encoding two types of hungwords: turnunders (`<seg type="turnunder">` in TEI / `<span data-el="seg" data-type="turnunder">` in HTML) and turnovers (`<seg type="turnover">` in TEI / `<span data-el="seg" data-type="turnover">` in HTML).  There are examples of this in emdLeir_Q1 if you search for "It were not good to returne from whence we". "(came)" is a turnunder. We've got CSS from Ashley Howard that will hopefully work:

For turnunders: `position: absolute; margin-top:1.3em;`
For turnovers: `psoition: absolute; margin-top:-1.3em;`

We're essentially hoping to emulate hungwords in our early modern playbooks that appeared either on the line under (turnunders) or above (turnovers) the line that the rest of the sentence was on.

**Comment by martindholmes** [comment]
If you already have the CSS, that's all you need. The thing about these is that they're all different, so you can't have a single algorithm that handles them all. Their vertical position may usually be predictable, but their horizontal position is not. This isn't something that should have a special encoding and rendering method; it's just CSS you can add directly into the encoding, and what's needed is documentation explaining how it should work. Let's get together and identify some good examples -- there seem to be lots in emd1H4_Q1, for example -- and make them the basis of an explanation.

One question is whether we should use `<hi>` or `<seg>` for this. Both appear to be in use. Another is whether people should be inserting a parenthesis inside the hung element; that seems wrong to me, if it's not there in the original text.

**Comment by JanelleJenstad** [comment]
1. We do want a simple way of handling these. Not all anthologies are invested in getting the horizontal placement exactly right; our flagship anthology, DRE, does not want editors spending time on these matters. If we can process turnovers and turnunders in some fashion, anthologies always have the option to add inline CSS to override our default processing. See suggestions below.
2. Having look at the Guidlines' definitions for hi and seg, I believe that we want seg. We're identifying a chunk.
3. The parenthesis is typical of hungwords. Editors and RAs should not _add_ a parenthesis if it's not there, but it usually is.

Will Navarra's original suggestion work?
For turnunders: position: absolute; margin-top:1.3em;
For turnovers: position: absolute; margin-top:-1.3em;

**Comment by martindholmes** [comment]
The suggestion will lift the seg up or drop it down, but it won't move it backwards, so it'll look a bit weird. If you want a standard rendering, I would suggest moving it back at least 2em (margin-left: -2em;) so that it's clear that it's turned up or down because of space constraints. Otherwise it'll just look like a layout error, I think. 

If the line-spacing in the original is not standard, then the amount of the margin-top setting might have to be massaged a bit, but I don't think we have any variation in line-spacing in our texts; it doesn't seem to be something that falls into the diplomatic bit of semi-diplomatic.

**Comment by pszpak** [comment]
Navarra, maybe we can talk about this the next time your are in.

**Comment by LEMDO-PM** [comment]
@pszpak I'm in HCMC today and Wednesday, is there a time that would work for you?
