### ISSUE TITLE
Increasing the font size on play pages moves the popup to the left

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#13]
If you increase the browser font size on a play text, the popup box for notes and annotations moves over to the left for some reason.

**Comment by martindholmes** [comment]
Looks like this is intentional behaviour designed to move the popup to the middle of the screen when viewing on a device whose width will not allow for the play text to be alongside the popup. @JanelleJenstad , can you confirm that you're OK with this behaviour for now? The alternative is to keep it over on the right at all times, which seems a bit more intuitive to me; either way, it will end up obscuring the text because of space constraints, so I don't think moving it achieves anything.

**Comment by JanelleJenstad** [comment]
Keeping it on the right makes more sense to me.

**Comment by JanelleJenstad** [comment]
@martindholmes: Can we close this ticket now? I don't see a need for any action at the moment.

**Comment by martindholmes** [comment]
I haven't turned off the unwanted behaviour yet.

**Comment by martindholmes** [comment]
Done in rev 8275.
