### ISSUE TITLE
Make glosses in side pane the same font as other text

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#131]
Glosses from GLOSS1 that pop up in the side pane are showing in a different font (doesn't appear to be an Alegreya). Please change the styling so that it matches the font family of our other text.
Here's an example from when you click "canonical reference" in learn_encodeLinks_intro on the LEMDO-dev site.
![image](https://user-images.githubusercontent.com/116194494/223505643-2f1d8f37-10b9-46f6-9e1a-655d8b023c78.png)

**Comment by pszpak** [comment]
Done.
