### ISSUE TITLE
pb xml:id question

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#132]
Janelle and I were chatting about our `@xml:id` on `<pb>` elements and were wondering if it would be valuable to switch to adding them manually so that they appear in our Standalone XML. As they are currently are (being added in the build process), they aren't showing up in the Standalone XML.
We were also wondering if manually adding xml:ids for `<pb>` might speed up build time?

**Comment by martindholmes** [comment]
If you add them manually, then find a missing page, then you'll have to re-edit large numbers of them, which is not ideal. If you want to see them in the standalone, we could add them at that stage rather than at the HTML stage. But if they're entirely mechanical, is there value in their appearing in the standalone?

**Comment by LEMDO-PM** [comment]
This came up because one of our editors wants to link to a <pb> element in her semi-diplomatic transcription. I added an xml:id to the `<pb>`, which has worked for the link. In Teams, you said this is probably fine to do as long as the link works, which it does :-), and we weren't sure if there is any other value to having the mechanically added xml:ids in the standalone or to us manually adding xml:ids. This isn't a pressing issue though.

**Comment by martindholmes** [comment]
I would see no reason to proliferate xml:ids everywhere because we have one user who needed one link; surely it's better to say that if you want to link to a pb, by all means give it an xml:id.

**Comment by LEMDO-PM** [comment]
That sounds good to me. Thanks! I'll close this issue now.
