### ISSUE TITLE
Create pseudoelement for blank pages

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#133]
emd2H4_Q1.html
Add blank page as text

**Comment by pszpak** [comment]
I've styled this should be in next build, however would you like blank pages to look different from page breaks? This is what it looks like  now:

<img width="978" alt="Screenshot 2023-03-08 at 1 12 49 PM" src="https://user-images.githubusercontent.com/18728777/223851626-0c9f736b-1729-40c4-8d28-17873959b035.png">

**Comment by LEMDO-PM** [comment]
I like it -- I think that both blank pages and page breaks being lighter than the main text is very nice.

**Comment by JanelleJenstad** [comment]
Looks beautiful! Would it be possible to display the value of `@n` instead of the phrase "Phrase break"?

**Comment by pszpak** [comment]
What is @n?

**Comment by LEMDO-PM** [comment]
@pszpak That's the signature number that we add (from the weird `<div class="blank">` that you noticed earlier). It's the value of `data-n`. (A1v in the example below)
![N value](https://user-images.githubusercontent.com/116194494/223881966-70c85794-585e-43df-8ea3-254039cb864b.png)

**Comment by LEMDO-PM** [comment]
My screen reader does read the text from the pseudoelement, so there's our answer to the accessibility question for it :)

**Comment by martindholmes** [comment]
@pszpak To clarify what's needed, the `div.page[data-empty="true"]` will most likely have a child div which has a `data-n` attribute, which is what contains the signature or folio number that needs to be displayed. Example from your screenshot above:

~~~~~
<div class="page" data-empty="true">
  <div data-el="pb" class="blank" data-n="A1v" data-sig="A1v" data-pbnum="A1v"></div>
</div>
~~~~~

**Comment by martindholmes** [comment]
Change "Page break" to "Page beginning".

**Comment by LEMDO-PM** [comment]
Changed to "Page beginning" in rev. 13612

**Comment by LEMDO-PM** [comment]
I believe this is all done, closing issue.
