### ISSUE TITLE
Schematron for scheme and target values on catRef elements

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#138]
Please write Schematron to enforce the use of values for `@target` from the taxonomy represented by the value of the `@scheme` attribute on the `<catRef>` element. 

I've recently corrected the metadata in a number of files where the target value was from a different taxonomy than the one indicated by the scheme. The only consequence (AFAICS) is in the interface for the Static Search page. Taxonomies generate the boxes on the Static Search page, and the target values populate the box, so one ends up with weird search suggestions like "Play" under "Editorial Treatments." I noticed it first in the Douai anthology and made the corrections in the metadata, but it may well be elsewhere as well. 

I suspect this error arises from copy-and-paste metadata. In any case, I'd like folks to get it right.

**Comment by martindholmes** [comment]
This could be done with Schematron, but it would leave you waiting many seconds between edits before validation could happen in Oxygen. I think it's more suited to a diagnostic, so I'll add one.

**Comment by martindholmes** [comment]
New diagnostic added in rev 1773. It currently finds six instances.
