### ISSUE TITLE
Terminal punctuation disappearing

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#139]
I have a terminal period in emd1HW_M_a2_s1_sp21 that isn't showing up on the site. It's at the end of the speech and is encoded like this:
` <sp who="#emd1HW_M_Roger" xml:id="emd1HW_M_a2_s1_sp21">`
`<speaker>Roger</speaker>`
`<p>I may thank you for that. <anchor xml:id="emd1HW_M_anc_1051"/>No<anchor xml:id="emd1HW_M_anc_1052"/>, faith,<anchor xml:id="emd1HW_M_anc_1053"/> I look like an old proverb, <anchor xml:id="emd1HW_M_anc_1054"/><quote>Hold the candle before the devil</quote>.<anchor xml:id="emd1HW_M_anc_1055"/></p>`
               `</sp>`
(period after the closing `</quote>` tag and before anchor 1055).

**Comment by martindholmes** [comment]
Definitely a bug; probably due to the interaction of a quotation immediately followed by a period then an anchor.

**Comment by martindholmes** [comment]
Fixed in rev 12772.
