### ISSUE TITLE
Do we have any processing for overstrike?

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#142]
This encoding does not do anything in the HTML output:
`<del rend="overstrike" unit="char" quantity="1"/>`

Two questions:
1. Is this the encoding we are expecting to see for a semi-diplomatic transcription of a manuscript playbook where the scribe has scribbled out one or more characters (unit="char" with a quantity attribute) or should transcribers of manuscripts be using `@unit="em"` (as we do on the `<space>` element).

2. If this is the encoding we are expecting, can we insert a grey box?

This question is primarily for @martindholmes when he returns to work.

**Comment by LEMDO-PM** [comment]
@JanelleJenstad they should be using unit="char" (not "em") for `<space>` when dim="horizontal". See learn_encodeSpaceOS#learn_encodeSpaceOS_practiceHorizontal

**Comment by JanelleJenstad** [comment]
@LEMDO-PM or @martindholmes: Line and I remember a lengthy conversation in HCMC about how to capture the length of a horizontal `<space>` and the length of a `<del>` . The Douai Team *was* using cm. We pointed out that cm were meaningless in a digital context. Line and I think that we settled on "em" as the best value for `@unit` rather than "char", which runs against the documentation that @LEMDO-PM cited yesterday. 

We are using "em" as the `@unit` value in emdDouai_JC.xml and emdDouai_Mac.xml. Navarra or I would have changed "cm" to "em" in their files for them in March. So I think we decided to use "em".

I'd like to standardize the unit for `<gap>`, `<space dim="horizontal">`, and `<del>`. Can we three come to a consensus later this month and get it into the documentation?

**Comment by martindholmes** [comment]
Yes please. :-) 
Going back to the original request:

`<del rend="overstrike" unit="char" quantity="1"/>`

The value "overstrike" doesn't appear in our schema; did they mean "strikethrough"? Overstrike usually refers to typing (on a typewriter) one character over another, or printing one char on top of another in error or to get a combination that isn't available as a single glyph. Even in the case of "strikethrough", though, we'd expect some content inside the del element, surely, being the thing that was struck through?

**Comment by LEMDO-PM** [comment]
Note that `"char"` is the value that we want on `@unit` based on my conversation with Janelle today.

**Comment by JanelleJenstad** [comment]
Martin is right. I'm going to change all the "overstrike" values to "strikethrough". Then we'll revisit the processing question.

**Comment by LEMDO-PM** [comment]
@JanelleJenstad, I see in my email that we were going to do some investigating about having overstrike as an option for sections that are blotted or blackened. Did you get a chance to look into that?

**Comment by JanelleJenstad** [comment]
We won't be able to have a lot of nuance. Anything that is struck through with a line, overwritten with squiggles or loops, or blotted should be given the rendition:rnd_strikethrough. Processing should be the CSS strikethrough.

**Comment by JanelleJenstad** [comment]
I believe this issue is resolved.
