### ISSUE TITLE
Stylesheets not associated for LEMDO-dev

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#149]
It looks like our stylesheets for lemdo-dev aren't associated again. Can you please take a look into that?
![image](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/1e1a44a7-e5c8-4adb-8c65-8505da1ce863)

**Comment by martindholmes** [comment]
That was fixed yesterday; see also issue #150. Closing.
