### ISSUE TITLE
Tweak CSS for speaker

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#15]
The change from Alegreya-smallCaps to Alegreya for rendering `<speaker>` hasn't been as successful as I'd hoped. The outdenting is great. The size is too big now, though. 

Request:
Use a smaller point for the speech prefix than we are currently using. Keep the bold and the outdenting. Make it the same _size_ as the text of the speech. 

(This is a small task for _after_ the Wendat release.)

**Comment by martindholmes** [comment]
Done in rev 8277.
