### ISSUE TITLE
Make build break if stylesheet association is broken

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#150]
@martindholmes: What do you think about making a stylesheet association failure into a build-breaking thing? It would be good if we got a build break notification before an editor noticed and wrote to tell us. 

Current view of the lemdo-dev site:

<img width="697" alt="image" src="https://github.com/projectLEMDO/lemdoIssues/assets/5943608/94854242-e29a-421a-ba7c-4ff61130dde0">

**Comment by martindholmes** [comment]
I don't know why this ISN'T breaking the build; the word Error is right there, so the Jenkins log parser should fail the build. I'll look into it. Meanwhile @pszpak  is fixing the problem.

**Comment by martindholmes** [comment]
I see that the LEMDO config is designed NOT to fail the build on an error message. I presume this dates back a long time to when individual documents would generate errors regularly, but we still wanted the build to proceed. I've now changed this, so it will fail on this error, but this may also mean that it fails more regularly on other errors that have been ignored so far. We will have to watch for that and add specific exceptions to the Jenkins log parser for cases where we don't want a local failure to fail the whole build. Leaving this open till we know the consequences of the change.

**Comment by martindholmes** [comment]
This seems to have worked as we hoped; the first build broke because of the stylesheet issue, but the next succeeded after it was fixed. Closing.
