### ISSUE TITLE
Question about line rendering

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#152]
Proofreading a couple of supplementary texts, I've noticed that lines (`<l>` in TEI, `<div data-el="l">` in HTML) that aren't part of speeches are rendering in a smaller font size. Is there a reason for that? If not, can we change it to be the same size as our other text? (I'd love to help with this; I'll be back in HCMC starting next week, maybe we could do it then.)
Example from emdCym_BritonsBlenerhasset:
![image](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/3209b8e4-04e3-4751-b5f6-5bf6a66ecb17)

**Comment by martindholmes** [comment]
I think in this particular case it's because the excerpt is not tagged as what it is: a quote. It's not anything at all except some line elements, which means it gets the default font size, which is smaller than the font size for most content which is properly tagged. I'm going to test wrapping it in a quote to see if that fixes it.

**Comment by martindholmes** [comment]
@LEMDO-PM Yes, that was it; once properly tagged as a cit/quote, it renders in the regular font size. Do you have any other instances to look at?

**Comment by LEMDO-PM** [comment]
@martindholmes We also have emdPer_Appolonius.

**Comment by martindholmes** [comment]
@LEMDO-PM This is the same problem, isn't it? There's a bunch of verse lines which are not part of a quote or anything else. This text is very crudely tagged. I don't believe this is an issue, it's just a question of tagging that needs finishing. If someone puts random `<l>` elements inside their `<div>`s then they'll get default styling, not the fuller styling that comes with quotes, linegroups, paragraphs or other containers.

**Comment by LEMDO-PM** [comment]
@martindholmes The issue with this file is that it isn't a play (so not `<sp>`), and I don't think that all of the lines are really block quotes--the bulk of the text is verse (it's a very early novel). Should they be wrapped in `<lg>`?

**Comment by martindholmes** [comment]
I've added a hack for these orphaned lines from supp texts in rev 13646. If no bad fallout, this can be closed.
