### ISSUE TITLE
Add styling for editorial notes

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#153]
Editorial notes (`<div data-el="note" data-type="editorial">` in HTML, `<note type=editorial">` in TEI) are showing up in a different font. Add styling for them to match our usual font-family and size.

@martindholmes , @pszpak am I good to go into the lemdo-dev.scss file to do this tomorrow (May 18)?

**Comment by martindholmes** [comment]
OK with me. I'll be sedated.🙂

**Comment by LEMDO-PM** [comment]
> OK with me. I'll be sedated.🙂

I hope all is well!

**Comment by LEMDO-PM** [comment]
Change committed in r13361. I'll see how it builds, then close this issue.
