### ISSUE TITLE
Include contents of listWit in standalone collation page

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#155]
We would like to have the contents of the `<sourceDesc>` element (usually a `<listWit>` with child `<witness>` elements linking to BIBL1, sometimes `<listWit>` is a child of `<p>` with narrative about witnesses) to appear at the top of the standalone collation pages. See emdH5_FM_M_collation as an example.

**Comment by LEMDO-PM** [comment]
See also [Issue 156](https://github.com/projectLEMDO/lemdoIssues/issues/156)

**Comment by martindholmes** [comment]
Fix committed in rev 13761. If no bad fallout, this ticket can be closed.

**Comment by LEMDO-PM** [comment]
Awesome, thanks!!

**Comment by martindholmes** [comment]
Bad fallout, it seems. Will have to revert and start again.

**Comment by martindholmes** [comment]
Reverted to an earlier rev; need to start again with this one, unfortunately.

**Comment by martindholmes** [comment]
Another fix committed in rev 13827. Waiting for the build to see if there's any fallout.

**Comment by martindholmes** [comment]
All seems to be good, so closing.

**Comment by JanelleJenstad** [comment]
The generated witness list at the top of the collation looks lovely! Thank you!
