### ISSUE TITLE
Link to modern text from standalone collation page

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#156]
We would like for each collation in the standalone collation file to link back to the relevant point in the modern file.

See also [Issue 155](https://github.com/projectLEMDO/lemdoIssues/issues/155)

**Comment by martindholmes** [comment]
In rev 13551, collation symbols are now being provided with an id of the form `appMarker_app_1` so that we can later link to them.

**Comment by martindholmes** [comment]
Committed a fully-working implementation in rev 13565. Close if no bad fallout for the build.

**Comment by martindholmes** [comment]
Rev 13572 corrects an issue where multiple linking icons would appear. I think this is now working, but we'll wait to be sure.

**Comment by martindholmes** [comment]
Douai shows some collation entries that don't get links:

emdDouai_Mac_collation.html

I think this is because they're pointed at things which are not actually in the text proper, but I'm not sure yet.

**Comment by martindholmes** [comment]
No, I think it's because the last component in the app is a note.

**Comment by martindholmes** [comment]
Fix committed in rev 13603.

**Comment by martindholmes** [comment]
This now seems to be working everywhere, so closing.
