### ISSUE TITLE
Remove all-caps from speaker tags in semi-diplomatic transcriptions

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#157]
Speech prefixes are currently showing up as all-caps on the website. We don't want them to show up as upper case letters unless we type them as upper case letters in semi-diplomatic transcription files. The files should have the following `<textClass>` categories:
`<catRef scheme="tax:emdDocumentTypes" target="cat:ldtPrimaryText">`
`<catRef scheme="tax:emdEditorialTreatments" target="cat:letOldSpelling">`
`<catRef scheme="tax:emdBookFormats" target="cat:lbfQuarto">` **or** `<catRef scheme="tax:emdBookFormats" target="cat:lbfFolio">`
`<catRef scheme="tax:emdWorkTypes" target="cat:lwtPlay">`

The speech prefixes are encoded with `<speaker>` in TEI (`<span data-el="speaker">` in HTML).

**Comment by LEMDO-PM** [comment]
@pszpak See "KING." (should be King.) on the lemdo-dev site at emdH5_Q1.html#emdH5_Q1_sp2

**Comment by martindholmes** [comment]
@LEMDO-PM I don't see "KING" in that context; I see "King". Is this ticket now obsolete?

**Comment by LEMDO-PM** [comment]
Yes. I fixed that one and then forgot to close the ticket.
