### ISSUE TITLE
Add styling for labels in semi-diplomatic transcriptions 

### ISSUE THREAD

**Issue by mahaylagalliford** [projectLEMDO/lemdoIssues#160]
Please remove all caps from `<label>` and please centre `<label>` in semi-diplomatic transcriptions. (`<catRef target="letOldSpelling">`) 

`<label>` are encoded in HTML as `<div data-el="label" data-type="heading">`. 

Example: Please see THE LIFE OF HENRY THE FIFT in emdH5_F1.

**Comment by mahaylagalliford** [comment]
`<label>` should also be italicized by default.

**Comment by martindholmes** [comment]
@mahaylagalliford Have you checked with @JanelleJenstad or @LEMDO-PM on this? I would have thought that a global rendering for textual features defeats the purpose of a semi-diplomatic transcription.

**Comment by LEMDO-PM** [comment]
Yes, we're happy with this request. If there are texts that don't fit this format, people can add `<tagsDecl>`s, `@rendition`, or `@style`, but most texts should be captured reasonably well with this.

**Comment by LEMDO-PM** [comment]
I'm closing this issue as I've created [Issue 169](https://github.com/projectLEMDO/lemdoIssues/issues/169) which more accurately reflects what needs done.
