### ISSUE TITLE
Add styling to catch words

### ISSUE THREAD

**Issue by mahaylagalliford** [projectLEMDO/lemdoIssues#162]
Please remove italicization for catch words. Please text align right.

Catch words are encoded as `<span data-el="fw" data-type="catch">`.

Example: Please see emdH5_F1 search for "rendred you in Musique" (catch word= turne).

**Comment by martindholmes** [comment]
@mahaylagalliford Done in rev 13608. Note that this also removes italicization from other fw elements such as running titles, but that's what we want anyway, because those should be derived from renditions in the teiHeader, not specified in the rendering CSS.

**Comment by martindholmes** [comment]
This seems to be done.
