### ISSUE TITLE
render entrance centre in semi-diplomatic transcriptions

### ISSUE THREAD

**Issue by mahaylagalliford** [projectLEMDO/lemdoIssues#164]
Please render entrances as centre in semi-diplomatic transcriptions. 

Entrances appear in HTML as `<span class="stage entrance" data-el="stage" data-type="entrance">`. 

Please see example: emdH5_F1 search: Enter the two Bishops of Canterbury and Ely.

**Comment by LEMDO-PM** [comment]
We're going to want to add the @place attribute on all stage directions (including exits and entrances). I've added the styling for place. Alternatively, we should probably add this in the tagsDecl
