### ISSUE TITLE
rendering of exits in semi-diplomatic transcriptions

### ISSUE THREAD

**Issue by mahaylagalliford** [projectLEMDO/lemdoIssues#165]
Please render exits as inline-right in semi-diplomatic transcriptions.

Entrances appear in HTML as `<span class="stage exit" data-el="stage" data-type="exit">`.

Please see example: emdH5_F1 search for the first exit (appears after 'iudge our play').

**Comment by LEMDO-PM** [comment]
We're going to want to add the `@place` attribute on all stage directions (including exits and entrances). I've added the styling for place. Alternatively, we should probably add this in the tagsDecl
