### ISSUE TITLE
add padding after stage directions in semi-diplomatic transcriptions

### ISSUE THREAD

**Issue by mahaylagalliford** [projectLEMDO/lemdoIssues#166]
We would like padding added after stage directions in semi-diplomatic transcriptions 
`<catRef target=letOldSpelling>` when they are not a child of `<ab>`. 

We want the same amount of padding as is after speeches. 

Encoding in HTML is `<span data-el="stage">`. 

Please see example: emdMucd_Q1 search for: enter enuie.

**Comment by LEMDO-PM** [comment]
Based on discussion with Janelle I'm going to change this to remove padding after `<sp>` elements and do not add padding after `<stage>`
