### ISSUE TITLE
line beginnings not rendering in folios

### ISSUE THREAD

**Issue by mahaylagalliford** [projectLEMDO/lemdoIssues#167]
We would like `<lb>` elements to render as new lines in our folio semi-diplomatic transcriptions. 

These files will have catRef target="lbfFolio" and letOldSpelling. 

It looks like they are working in quartos.

**Comment by martindholmes** [comment]
@mahaylagalliford Could you give me an example text which has lbs that are not being rendered?

**Comment by LEMDO-PM** [comment]
@martindholmes emdH5_F1

**Comment by martindholmes** [comment]
@mahaylagalliford We have a comment in our XSLT which says:

`We ignore the old TLNs and QLN linebreaks for now since they will be deprecated in the near future.`

  
  The linebreaks in H5_F1 are all type="tln". If they're not actually tlns -- if they're real linebreaks in the witness itself -- then just get rid of the erroneous `@type` attribute and they should all render.
  
  This is the XSLT, for the record:
  
  ~~~~~
    <xd:doc>
    <xd:desc>We ignore the old TLNs and QLN linebreaks for now since they will be
    deprecated in the near future.</xd:desc>
  </xd:doc>
  <xsl:template match="lb[@type=('tln','qln')]" mode="tei"></xsl:template>
  
  <xd:doc>
    <xd:desc>Regular linebreaks (i.e. untyped linebreaks) should signify an
    actual linebreak in a text and so should be displayed as such.</xd:desc>
  </xd:doc>
  <xsl:template match="lb" mode="tei">
    <br/>
    <span>
      <xsl:call-template name="processAtts"/>
    </span>
    <!--We will have to account for line numbers somehow-->
  </xsl:template>
  ~~~~~

**Comment by LEMDO-PM** [comment]
@martindholmes I believe that should only be true in modern texts. We do want to retain `<lb>` elements, and we have been planning on retaining the `@type` values as well (we are remediating to be either "tln" for Shakespeare F1, "wln" for everything else).

**Comment by martindholmes** [comment]
@LEMDO-PM In that case there has been a clear policy change, which I wasn't aware of. But bear in mind that if we start rendering tlns now, there will be massive chaos. There are 34,690 old TLN links scattered through our texts, waiting to be remediated. I think this needs a proper plan of action, surely.

**Comment by LEMDO-PM** [comment]
@martindholmes Based on my discussion with @JanelleJenstad on Monday, we'll switch tln to wln for the folio texts.

**Comment by martindholmes** [comment]
@LEMDO-PM Is that a solution or a workaround? Are there non-folio texts with tlns that will need to be rendered? Do wlns get rendered?

**Comment by LEMDO-PM** [comment]
@martindholmes tlns (through line numbers) come from Hinman's folio. Things that have tln that aren't folio texts haven't been remediated yet. We're happy to use wln (witness line number) for the folio texts, because it's still an accurate phrase.

**Comment by martindholmes** [comment]
I'm assuming that there's no intention to try to render the line-numbers anywhere? They would clash with the ASSP system.

**Comment by martindholmes** [comment]
@LEMDO-PM Do we have a decision on this yet? Are all tlns to be converted to wlns?

**Comment by LEMDO-PM** [comment]
@martindholmes Yes, we can convert the tlns in semi-diplomatic transcriptions to wlns. Janelle and I will let the RAs know next week.

**Comment by martindholmes** [comment]
@LEMDO-PM Should I close this then?

**Comment by LEMDO-PM** [comment]
Yes, we can close this.
