### ISSUE TITLE
A.S.Sp. Pointer Linking in Semi-Diplomatic Transcriptions?

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#168]
We would like to use pointer elements to link to speeches and anchors in semi-diplomatic transcriptions. The speeches have xml:ids, but we do not add divs for acts or scenes.

Could you use the processing from the Sp. part of our A.S.Sp. linking to generate text (e.g., Sp.5) from `<ptr>` links pointing to semi-diplomatic transcriptions? Speech xml:ids are formatted as emdFilename_sp1 (e.g., xml:id="emdAHDM_Q1_sp70").

We will want to use this in emdAHDM_printingHouse to anchors in speeches in  emdAHDM_Q1

**Comment by LEMDO-PM** [comment]
Hmmm... this seems to be already working in some places... I'm going to take another look at the TEI file.

**Comment by LEMDO-PM** [comment]
The pointers are working in some places, but not in others. Compare the one at At emdAHDM_Q1.html#emdAHDM_Q1_anc_3 , where An example occurs at Sp740 (emdAHDM_Q1.html#emdAHDM_Q1_anc_11).

**Comment by martindholmes** [comment]
Fix committed in rev 13528. Close if no bad fallout or remaining instances. This required a rewrite of the ASSP discovery code; in semi-dip texts, the text structure is reorganized into pages at build time, which means that target anchors are no longer necessarily descendants of their original ancestor ASSP elements; we have to look along the preceding:: axis to find them.

**Comment by martindholmes** [comment]
I'm going to close this, since there are no further reports.
