### ISSUE TITLE
Change rendering of ident

### ISSUE THREAD

**Issue by nvatcher** [projectLEMDO/lemdoIssues#17]
We like the grey box, but would like to remove the italicization.

**Comment by martindholmes** [comment]
@nvatcher What ident, where? Example page? Any clues?

**Comment by JanelleJenstad** [comment]
We use <ident> through the documentation files to encode paths and filenames. See https://jenkins.hcmc.uvic.ca/job/LEMDO/lastSuccessfulBuild/artifact/products/lemdo-dev/site/learn_terminal.html for some examples

**Comment by martindholmes** [comment]
Thanks! Done in rev 8345.
