### ISSUE TITLE
Change `text[@type='standoff']` to `<standOff>`

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#171]
Our code predates the availability of the `<standOff>` element, so we are using  `text[@type='standoff']`. We should change this is standalone_import_module.xsl, then update any processing that depends on it (which may be substantial).

**Comment by martindholmes** [comment]
Preparatory notes on this:

We currently divide the `text[@type='standoff']/body` using divs; we have:

`div[@type='ographies']` containing `<listPerson>`, <listOrg>` etc. All these list elements can go directly into the `<standOff>` element.

`div[@type='annotations']` containing `<note>` elements. These could go directly into the `<standOff>` element, but it would be nice if we could group them somehow. `<listAnnotation>` is available, and it can contain `<note>` elements, so that seems like the best option.

`div[not(@type)]` containing `<listApp type="collations">`. `<listApp>` can go directly into `<standOff>`.

**Comment by JanelleJenstad** [comment]
Can we use the `<noteGrp>` element? https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-noteGrp.html

**Comment by martindholmes** [comment]
@JanelleJenstad `<noteGrp>` is not available in `<standOff>`, unfortunately. But since our notes actually are annotations, I think `<listAnnotation>` would be more accurate anyway.

**Comment by martindholmes** [comment]
I wonder if we should raise a ticket to make `<noteGrp>` a member of `model.standOffPart`, though?

**Comment by JanelleJenstad** [comment]
That's an excellent idea. Council is in the freeze phase for their upcoming release. Let's raise a ticket as soon as the release is out; we'll have a better chance of getting attention then.

**Comment by martindholmes** [comment]
First implementation of this committed in rev 16311. Waiting to see what Mr Jenkins makes of it.

**Comment by martindholmes** [comment]
Did a second pass through the XSLT and the schema to remove or refactor comments and other remaining references to the old encoding pattern. If all builds OK now, this ticked can be closed.

**Comment by martindholmes** [comment]
Closing this; I think it's done.
