### ISSUE TITLE
Rendition rnd:normal isn't working when on the stage element

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#175]
When an entire stage direction is in roman type, we've been putting `@rendition="rnd:normal"` on the `<stage>` element, but that doesn't seem to be working as the stage directions are still appearing in italic on the site. The rendition works correctly when we use it on the `<hi>` element. Here's an example of the encoding from emd1HW_Q2 in sp315:
`<stage type="delivery" place="plc-right-inline" rendition="rnd:normal">She <g ref="lig:longS_i">si</g>ngs.</stage>`
and how it looks on the site:
![image](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/8570475d-cbeb-4bfb-b943-c22dd17bbba8)
Can we make it so that rendition works when we put it on the `<stage>` element?

**Comment by martindholmes** [comment]
@LEMDO-PM This is an artifact of the CSS cascade. The arcane rules for styling stage-directions are very specific in the stylesheet, so they take precedence over any default renditions that you may apply. Basically, you can't have it both ways: you can't have simple defaults that will somehow end up overriding complicated selectors. However, a local `@style` attribute will do it:

~~~~~
<stage type="business" place="plc-right-inline" style="font-style: normal;">
                       She <g ref="lig:longS_i">si</g>ngs.
                   </stage>
~~~~~
That's what I've added for this case. A `<hi>` element inside the `<stage>` element will also work.

**Comment by LEMDO-PM** [comment]
Thanks, that sounds good.
