### ISSUE TITLE
Include stage directions with multiple type values in styling

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#176]
Stage directions in semi-dip texts with multiple type values aren't rendering in the correct font-size (unless one of the values is `"entrance"`). Use the * after data-type for each of the types in the SCSS folder here: `span[data-type="delivery"], span[data-type="sound"], span[data-type="business"], span[data-type="setting"], span[data-type="location"], span[data-type*="entrance"]`

**Comment by LEMDO-PM** [comment]
Also check that SDs have the same font colour as the rest of the text.

**Comment by JanelleJenstad** [comment]
Just checking in on this ticket. I think you have completed it?

**Comment by LEMDO-PM** [comment]
Yes, this is done. Closing now.
