### ISSUE TITLE
Link to GLOSS1 not working as expected

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#178]
We've linked a technical term to GLOSS1, but the link is taking me somewhere else entirely when I click on it.

The issue is coming up in learn_terminal. In the second sentence, the word "Terminal" is wrapped in `<term>` with an `@ref` attribute pointing to a term in GLOSS1. It's encoded like this:
`<term ref="gloss:TERM1">Terminal</term>`. I checked, and TERM1 is the correct xml:id for "terminal" in GLOSS1.

When I click the link on the website, it brings me to the final div of learn_terminal (xml:id="learn_terminal_further"). I'm not sure why this is happening or if the same thing is happening with other links to GLOSS1.

**Comment by LEMDO-PM** [comment]
Update: There is another term linking to GLOSS1 that **is** working as expected in the following paragraph. It is encoded the same way as above: `<term ref="gloss:SUBV1">Subversion</term>`.

**Comment by martindholmes** [comment]
@LEMDO-PM The link is working perfectly for me. It pops up the definition of "terminal". Is it possible you have JavaScript turned off, or you haven't super-reloaded the page, or you're loading a local built copy of the document without running a local web browser?

**Comment by LEMDO-PM** [comment]
Weird! Super-reloaded and it is now working. I'm not sure why that happened. Thanks!

**Comment by martindholmes** [comment]
@LEMDO-PM I think one possibility is that you clicked the link so quickly after loading the page that the JS that turns the links into popups was still running. Initially the link would have been to an item in the appendix, but the JavaScript turns it into a call to show a popup and then hides the appendix. So the link may have taken you down to the appendix, which then disappeared. That could only happen if you loaded the page and then immediately clicked on the link.
