### ISSUE TITLE
Split quotes with `@next`/`@prev` are not rendering correctly

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#18]
See quotes split across lines in emdPer_Appolonius; the desired output is a single opening quote and a single closing quote. This should be handled by the XSLT template on l. 244 of xhtml5_templates_tei_module.xsl, but it's not happening.

**Comment by JanelleJenstad** [comment]
We have decided to transcribe quotation marks and tag them with `<pc>`. I have made a to-do item in Teams/LEMDO/Documenters to document this.
