### ISSUE TITLE
Add height and width attributes to graphics

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#184]
Please add the `@height` and `@width` attributes to the `<graphic>` elements across the QME collection (data/anthologies/QME and various plays in data/texts).

**Comment by martindholmes** [comment]
For Leir, we're waiting on the links being fixed -- they mostly use the old static: prefix pointing at stuff on the NFS server rather than images in our repo.

**Comment by martindholmes** [comment]
@JanelleJenstad Still waiting on the Leir links to do this one. Should I just close the ticket for now?

**Comment by JanelleJenstad** [comment]
Keep it open, please. I just pinged Peter with a list of all the image links that need to be corrected.

**Comment by martindholmes** [comment]
Still waiting on fixes in Leir_M_annotation.

**Comment by martindholmes** [comment]
I think this must be obsolete, since Leir is now published, so I'm closing it.
