### ISSUE TITLE
Fix styling in semi-dip when stage is followed by fw 

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#186]
When we have a `<stage>` element as the final thing before `<fw type="sig">` or `<fw type="catch">`, the stage direction and catchword overlap.
Please change the margins so that doesn't happen.
E.g. from emdFBFB_Q1:
![image](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/436181c3-50b5-442a-a425-dff2e23d6852)
HTML:
![image](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/44e1ac5f-3a98-4c5f-935b-1fc9a3642e2f)
XML:
![image](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/4d7895a9-8854-4465-af3d-66c30c77eb0c)

**Comment by LEMDO-PM** [comment]
@pszpak I'm not sure how to do this one and I'm not back in HCMC until July 30. If you get a chance to take a look at it before then, great! If not, maybe we can work on it together when I'm back.

**Comment by pszpak** [comment]
I'll get to it today.

**Comment by pszpak** [comment]
I changed this by moving the last span absolutely until it looked okay, but this only happens if the specific order of spans you described above is present.  Let me know if it's not what you wanted or it causes style problems elsewhere.

`span[data-place*="right"] + span[data-el="fw"][data-type="sig"] + span[data-el="fw"][data-type="catch"]`

**Comment by LEMDO-PM** [comment]
That sounds great! It only seems to be an issue when there is that specific order of things. Thank you!!!

**Comment by LEMDO-PM** [comment]
@pszpak This is what's appearing now:
![image](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/aec74217-14db-4267-92fd-af722fe7e558)
But we'll want it to look more like this (I'm not sure why the stage direction is lower in this situation... I think we want the stage direction moved up rather than the fw moved down):
![image](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/e113c955-3376-4d5d-81ea-507a8a3925b2)
I added styling in the inspector view to move the` span[data-place*="right"]` thing up 1.5rem (top-margin: -1.5rem;) and removed the bottom-margin on the `span[data-el="fw"]`

**Comment by pszpak** [comment]
If we do this inline on a per case basis the html would look like this:

`<span data-el="fw" data-type="catch" data-rendition="#rnd_italic" class="rnd_italic" style="position:absolute; right: 0;">Enter</span>`

`<span data-el="stage" class="stage exit" data-type="exit" data-place="plc-right-inline" data-asl="0.0.152.1" data-sln="0.0.sp138.1" data-csln="sp138.1" style="position: absolute; right: 0; margin: auto 0; bottom: 0;">Exit.</span>
`

**Comment by martindholmes** [comment]
@LEMDO-PM I no longer see a problem with this:

emdFBFB_Q1.html#emdFBFB_Q1_sp129

Is there still work to do, or can it be closed?

**Comment by LEMDO-PM** [comment]
It can be closed. I'll do that now :)
