### ISSUE TITLE
Add processing for orgName

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#187]
We've noticed that, although a hyperlink seems to appear for `<orgName>` elements, nothing happens when we click them. You can see an example of that in the metadata popup for emdFBFB_GenIntro in the "Source" section (LEMDO Team is wrapped in `<orgName ref="org:LEMD1">`).
We would like the processing to be similar to persName, where there is a popup on the right which shows the info from ORGS1.

**Comment by JanelleJenstad** [comment]
Once this job is done, you can test it on data/anthologies/qme/about/qme_acknowledgements.xml, where there are multiple organizations tagged with `<orgName>`

**Comment by martindholmes** [comment]
Fixed in rev 14972. The JavaScript has apparently never known anything about orgNames; presumably they were added to the mix after the JS for popups was written. If the build is OK, this can be closed.

**Comment by martindholmes** [comment]
All good. Closing.
