### ISSUE TITLE
Please turn this logo black

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#189]
We have a logo for UofT Centre for Drama, Theatre & Performing Arts, but it's transparent and the white text won't show up on the light yellow background of the QME website. Please turn the text on this logo black instead of white.
![UofTLogo](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/931b9f93-9bb0-4bd5-9abf-e6cd3ff18b0a)
(If you're on light mode, the image doesn't show up here because it is white, but it's just above this line of text)

**Comment by pszpak** [comment]
H
![centre-for-drama-header](https://github.com/projectLEMDO/lemdoIssues/assets/18728777/fbdd03cb-428e-4f4c-9846-b8f87163330e)
ow's this?

**Comment by LEMDO-PM** [comment]
That's perfect! Thank you!!!!
