### ISSUE TITLE
Please make transparent

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#190]
Please cut this image so it's just the logo and also make the logo transparent. Thanks!
![poculi_logo](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/b12543de-ec97-4d61-b353-8815db57f7bd)

**Comment by pszpak** [comment]
![tei](https://github.com/projectLEMDO/lemdoIssues/assets/18728777/a9280f17-fe97-4c87-b251-da83482a48d0)

**Comment by pszpak** [comment]
The other one is not a quick fix I'll get to it tomorrow.

**Comment by LEMDO-PM** [comment]
Thanks!!
