### ISSUE TITLE
Add degree sign to characters available from Ctrl + Shift + Space

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#192]
We need to be able to insert degree signs with some frequency. Please add it to the Ctrl + Shift + Space drop-down menu (and please remind me what we call that feature).

Character: °
Unicode: U+00B0

**Comment by martindholmes** [comment]
Done. The feature is Code Templates, and it's available in Options  / Preferences, and search for Code Templates. You can also now insert the degree symbol with Control + Shift + 0.
