### ISSUE TITLE
Metadata panel is too small when QME adds page images

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#195]
In [qme/site/emdSel_Q.html](qme/site/emdSel_Q.html), the metadata panel is pushed over and the text is cut off. 

I think it's because there are image thumbnails in this text, which makes the central text panel wider. It's not a problem in any other QME files, none of which have image thumbnails.

Also of note: in the lemdo-dev rendering (/lemdo-dev/site/emdSel_Q.html), the metadata is similarly cut off, but a slider bar is present so that one can scroll across the metadata. 

Perhaps the problem is that QME's SCSS has disable the slider bar?

<img width="231" alt="image" src="https://github.com/projectLEMDO/lemdoIssues/assets/5943608/c3c5ddd1-e540-41e2-904c-ee47e55ed4b6">

**Comment by martindholmes** [comment]
As far as I can see Firefox doesn't show this problem; it's limited to Chrome-based browsers.

**Comment by LEMDO-PM** [comment]
Pat's fixed this. I'm going to close this issue.
