### ISSUE TITLE
Periods disappear when they're after ptr

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#196]
When we have a `<ptr>` followed by a period at the end of a sentence, the period disappears.

E.g., learn_validate#learn_validate_further

Encoding: `<p> ... <ptr target="doc:learn_commit"/>.</p>`

Output: 
![image](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/fb83716e-d066-4a1d-bb57-df5e93a250cf)

**Comment by martindholmes** [comment]
Fix committed in rev 15905. Let's look out for any unexpected fallout, but if nothing emerges in the next little while, this can be closed.

**Comment by martindholmes** [comment]
@LEMDO-PM I see no problems with this now -- can you check, and if all is good, close this?

**Comment by martindholmes** [comment]
I'm going to assume this is OK and close the ticket.
