### ISSUE TITLE
Documentation metadata

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#198]
We want some metadata from the `<teiHeader>` included in every documentation page, but not all of it. This is the algorithm by which you decide which should be included and which should be ignored:
Do not include:
- `<title>` element--we only want the title that we put in the first `<head>` element in each documentation `<div>`
- `<respStmt>` elements--we only want to give credit to the people that are defined in the `@resp` attribute in the documentation `<div>`. These values point to xml:ids defined in the `<teiHeader>` of the ODD file.

*Do* include:
- `<sponsor>` element
- `<funder>` element
- `<editionStmt>` element
- `<publicationStmt>`--we do already have a `<publisher>` element being generated, but we want to replace it with the more robust one in the ODD file.
- `<seriesStmt>`
- `<sourceDesc>`--we already have a `<sourceDesc>`, but we want to replace it with the one in the ODD file.
- `<encodingDesc>` (and children `<p>` and `<editorialDecl>` elements)

Also please include all of the above elements' descendants.

Janelle is open to the long term solution of changing documentation files to be rooted on TEI and have their own teiHeaders rather than how they currently are (rooted on divs).

**Comment by martindholmes** [comment]
First attempt committed in rev 15907.

**Comment by martindholmes** [comment]
Fix breaks the build, I think -- something to do with those accursed default attributes. Workaround committed in 
rev 15909.

**Comment by martindholmes** [comment]
Working well, so closing.

**Comment by martindholmes** [comment]
Reopening this because `<sponsor>` is not being handled, mostly because it has no content in the vast majority of cases.

**Comment by martindholmes** [comment]
And closing again because the bug is actually not related to documentation and the inclusion of metadata, it's the rendering of it. We need a new ticket.
