### ISSUE TITLE
`<sponsor>` is ignored when creating the metadata table

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#199]
I think this is the case because it was not used when the original code was written, but also because it's almost always empty, consisting only of a `@ref` pointing to an `<org>`. It's not clear what should be done with it at all -- get output the name of the org? @JanelleJenstad and @LEMDO-PM, could you tell me how you want this to be acted on? Then I can add it to the rendering.

**Comment by martindholmes** [comment]
Fix committed in two commits, second being 16111. Waiting to see if the build succeeds.

**Comment by JanelleJenstad** [comment]
It's building fine. We need @pszpak to style the output. Right now, it's displaying in a serif font. We use our sans serif font in the metadata panel.

<img width="141" alt="image" src="https://github.com/projectLEMDO/lemdoIssues/assets/5943608/6934559c-6e01-42f5-867d-851857579a32">

**Comment by pszpak** [comment]
Can you provide me with an example page where it is rendering with serif? I'm looking at Jenkins and see sans in the metadata panel.

**Comment by JanelleJenstad** [comment]
Have a look at this page: https://jenkins.hcmc.uvic.ca/job/LEMDO/lastSuccessfulBuild/artifact/products/lemdo-dev/site/emdAWW_edition.html.  I see serif for the Sponsor element in the metadata panel (and in all other metadata panels). I'm on Chrome at the moment. 

<img width="224" alt="image" src="https://github.com/projectLEMDO/lemdoIssues/assets/5943608/abf2449a-0af1-4d9d-a425-02cc8e2ebc10">

**Comment by pszpak** [comment]
I think I fixed it now.
