### ISSUE TITLE
Tweak rendering of marginal notes

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#20]
Sorry -- this one is about supplementary texts :-( 

Have a look at emdH5_Holinshed.html.

At some point, we decided to encode authorial/marginal notes in supplementary texts with `<note type="marginal">` and to render them as pop-ups. 

The documentation learn_annotationsSupp.html#learn_annotationsSupp_marginal reads as follows:

> Generally, you will exclude marginal notes in the early modern text from your supplementary materials. However, if a marginal note (whether beside or below the text block) in your source text is important to your argument, you may capture it in your supplementary document using the [<note> ](https://jenkins.hcmc.uvic.ca/job/LEMDO/lastSuccessfulBuild/artifact/products/lemdo-dev/site/lemdo_spec_note.html)element with the value "marginal" on the @type attribute. You may capture marginal notes whether the supplementary doccument is functioning as a born-digital paratext or as a primary document (with either "letMixed" or "letModernSpelling" or "letOldSpelling"). LEMDO will render these notes as pop-up notes, regardless of their place on the original page.

But we aren't in fact rendering things that way. 

I do note that emdH5_Holinshed has an encoding problem, in that there are editorial notes inside marginal notes. Obviously, I'll have to get creative and do something that avoids nested refs. But the properly encoded marginal notes are not rendering either.

**Comment by martindholmes** [comment]
@JanelleJenstad If you want these marginal notes to be rendered as popups, we'll have to decide what the reader will click on in order to see them. What would you prefer? We can't use numbers, because the editorial notes use the numbering system.

**Comment by JanelleJenstad** [comment]
[Margin: text of note]

**Comment by JanelleJenstad** [comment]
Let's use a manicule as a clickable symbol. 
At the top of the pop-up, put "Marginal Note"

**Comment by martindholmes** [comment]
OK, so plan of work here:

Process `note[@type='marginal']` just like `note[@type='editorial']` and friends, but put it into a separate list which does not interleave with the others in the standalone XML. Give them their own number-sequenced ids, and add the prefix "[Marginal note]". In place of footnote numbers in the text, use the manicule (after checking how/if it works with our current font set).

**Comment by martindholmes** [comment]
@JanelleJenstad I've implemented this in rev 9724, using Unicode U+261B BLACK RIGHT POINTING INDEX for the manicule. I doubt it will work very well or look very good. In MoEML, what we have is a custom interface font with manicule characters in it, but I don't think it's a good idea to add yet another font just for this. I'm also not really sure that it's the right character; it will be sitting in the middle of the text, pointing at nothing, which is surely confusing. I think we should revisit that choice.

**Comment by martindholmes** [comment]
I believe all work on this is complete.
