### ISSUE TITLE
Links from collation page not appearing in Douai anthology

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#200]
The links from the standalone collation page to the associated file are not appearing on the Douai pre-release site. They **are** working on the LEMDO-dev site for the Douai editions. Can you please go in and add the stuff that needs added to make that work on the Douai site as well?

Follow up question: Is there meant to be a similar linking mechanism from standalone annotations to the associated file? Or not yet?

**Comment by LEMDO-PM** [comment]
The links are also working from the published QME site.

**Comment by martindholmes** [comment]
@LEMDO-PM I think this is their fault; they've written CSS in their CSS file which hides the collation symbol:

`background-color: var(--hand1) !important;`

**Comment by martindholmes** [comment]
This is being handled via email. It may not be important to the team to have links from the collation page back into the text.

**Comment by JanelleJenstad** [comment]
This issue is imbricated with the DSMP's "Original" reading mode. We can't fix it without messing up their Original reading mode, which takes precedence. 

@LEMDO-PM: Please remove then stand-alone annotation and collation links from the edition pages. They'll still be built with the edition, but there's no longer an invitation to look at the pages and notice that they don't link back to the text.

**Comment by comesaignol** [comment]
Hello there,
I've added a little line of CSS to handle this.
* I confirm that the symbol for collation does not appear in the 'default' mode of our semi-diplomatic edition. This is a feature named 'original' reading mode.
* With this new CSS line, the symbols do appear 'by default' on the collation page.
Thank you for pointing this out!

**Comment by JanelleJenstad** [comment]
@comesaignol: The symbols appear to take one to the top of the file, rather than to the relevant anchor point.

**Comment by martindholmes** [comment]
@comesaignol If you'd like some more detail on how you could fix this, let me know.

**Comment by LEMDO-PM** [comment]
Looks good! Thanks @martindholmes !! Closing this now
