### ISSUE TITLE
Douai anthology page numbers go over pseudoelement for page beginnings

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#203]
The Douai anthology have styled their page numbers to be larger than they are on the LEMDO-dev site. This makes it so that the number overlaps with the pseudoelement for the next page beginning when there is no other content on that page:

![image](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/a52950d6-1fea-4565-8d0f-43663f01d891)

We don't want these things to overlap, but like where the page numbers are in all other cases. Is it possible to make there be more white space between the two page beginning pseudoelements when the only thing in between them is the page number? In those situations, the HTML looks like this:
`<div data-el="pb">`
`      <span data-el="fw" data-type="pageNum">132</span>`
`</div>`

I think that the spacing that we use for blank pages (shown in the image above) would work really well.

**Comment by pszpak** [comment]
Can you shoot me a link to a good example page?

**Comment by LEMDO-PM** [comment]
It's on the Douai dev site on the emdDouai_JC page. I'll send you a link in Teams.

**Comment by pszpak** [comment]
There are a few ways of doing this, but I the best way is using the existing css and modifying it in the douai.scss file that will then override lemdodev.scss. That means increasing the white space between div.page elements when span[data-el="fw" is within the div.page to accommodate the bigger page numbers.

`@supports selector(:has(*))
body[data-catrefs*=letSemiDiplomatic] div.page:has(span[data-el=fw]) {
margin-top: 3rem;
margin-bottom: 2rem;
}`

Which renders like this: 

<img width="964" alt="Screenshot 2024-02-06 at 10 33 30 AM" src="https://github.com/projectLEMDO/lemdoIssues/assets/18728777/e03d1806-2aaf-442a-826b-3040052eaf74">

**Comment by LEMDO-PM** [comment]
Oo great!! Thanks :)

**Comment by LEMDO-PM** [comment]
Fix looks good! Closing this now
