### ISSUE TITLE
Douai hamburger menu has broken link

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#204]
There is a broken link in the Tools section of the Douai hamburger menu. The collation symbol is in an HTML `<a>` element, but I don't think it actually should be/needs to be a link. @comesaignol, can you please take a look at it? It seems to show up on all pages of the Douai pre-release site.
![image](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/26b52c41-8c67-4d32-b610-e336a87b44fc)

**Comment by martindholmes** [comment]
@comesaignol  I'd suggest using the same approach as you use for other legend items, creating a div for the symbol, and making it an inline block with a fixed size. You might need to add a fixed size to the img tag too, to constrain the svg.

**Comment by martindholmes** [comment]
@comesaignol @LEMDO-PM I'm planning to pick this one up tomorrow if nobody else does.

**Comment by martindholmes** [comment]
Fixed in rev 17063. Closing this.
