### ISSUE TITLE
Accomodate for multiple type values in styling for SDs in modern texts

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#205]
In modern texts, we want the styling that we have to apply even when there is more than one `@type` value. Currently, styling only applies when there is more than one value and one of the values is `"entrance"`.

I will make this change after Douai is released. @JanelleJenstad, I'm including you on this so that you can give the okay. Are you happy with this change? I don't think it will cause any unwanted fallout.

Currently what's happening:
![image](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/8c06115d-182d-428f-9c5e-4d86ad913c04)
(from H5_FM)

What happens with the proposed change:
![image](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/6f141ee8-4e53-4746-9729-163e1fbdd81b)
(note that this also is on a different line than the other SD... that's coming from a different change that I'll put in a separate GH issue)

Note to self: To change this, add * after `data-type` in our modern text SD styling. Search
`span[data-type="delivery"]` to find this styling.

**Comment by JanelleJenstad** [comment]
I'm all in favour. Please go ahead after Douai is released.

**Comment by JanelleJenstad** [comment]
This issue may or may not be related. I'm noticing font size variations between prose and verse in _Mucedorus_ in the LEMDO Classroom anthology. 

<img width="452" alt="image" src="https://github.com/projectLEMDO/lemdoIssues/assets/5943608/f984b933-7f6e-4e6d-a286-509d2e9d02ea">

**Comment by martindholmes** [comment]
@Janellejenstad I just checked this, and the computed font size for both speech text and stage directions in prose and verse speeches is identical: 19.44px.

**Comment by JanelleJenstad** [comment]
@martindholmes is right. _Mucedorus_ looks fine now. 

@LEMDO-PM: Please go ahead now with your proposed fix.

**Comment by LEMDO-PM** [comment]
Fix committed rev. 17372.

**Comment by martindholmes** [comment]
@LEMDO-PM I think you can close this now.
