### ISSUE TITLE
Put stage directions on different lines

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#206]
Mahayla noticed that when there are multiple `<stage>` elements in a row and none of them have `@type="exit"` they all appear on the same line:
![image](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/bda0098e-8291-4711-9173-9732733b128f)
(e.g. from Civi_M)

She would like them all on different lines. We can do this by adding this in the SCSS file after the modern text SD styling:
`span[data-el="stage"] + span[data-el="stage"]{
  display: block
}`
(search for `span[data-type*="entrance"]`)

The change would look like this:
![image](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/832c7b94-72fa-48c0-b0a2-6fe91b65f682)

I can do this after Douai releases, but I want to be careful that it doesn't have any fallout. I would like to a) get @JanelleJenstad 's approval to make sure it's what we want for the project, b) put the stage direction styling for modern texts into a section that applies only to modern texts (i.e., wrap all of the relevant styling in `body[data-catrefs*="letModernized"]{  }`), c) run a local build and check that everything looks correct--this will also need a search in the repo to see where there are instances of this happening both in and out of `<sp>`.

**Comment by martindholmes** [comment]
Just to chime in: @LEMDO-PM this looks like a good solution and your code looks solid to me.

**Comment by JanelleJenstad** [comment]
Please go ahead, @LEMDO-PM!

**Comment by LEMDO-PM** [comment]
Fix committed rev. 17372.

**Comment by martindholmes** [comment]
I've just added an adjustment to my overlap code to stop it from interfering with this. By tomorrow it should be working as planned.

**Comment by martindholmes** [comment]
This is working, so I'm going to close it. Thanks @LEMDO-PM!
