### ISSUE TITLE
Links to hands defined in HANDS1.xml are not correctly handled in HTML rendering

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#207]
The hand: prefix can be used to link to items appearing in the HANDS1.xml file to provide documentation on a scribal hand. At build time, these should be turned first into links such as e.g. HAND1.xml#DOUH1 (which is happening); the source data for the hand should be imported into the standalone file (which is not happening); and the rendered page should turn the link into a local link to the item, which in turn should be massaged by JS into a popup. So:

1. Need to incorporate hand data into the standalone XML file.
2. Need to process that data out to the appendix of the HTML file.
3. Need to process the in-page link from HAND1.xml#DOUH1 to #DOUH1.

**Comment by martindholmes** [comment]
Stage 1 implemented in rev 17071.

**Comment by JanelleJenstad** [comment]
Thanks! I was just looking at this error in the broken links report.

**Comment by martindholmes** [comment]
Stage 2 implemented in rev 17073.

**Comment by martindholmes** [comment]
Stage 3 completed in rev 17074.

**Comment by martindholmes** [comment]
If all of the hand-related internal link errors disappear from the Douai internal link diagnostics, then this has been successful and can be closed.

**Comment by LEMDO-PM** [comment]
The errors are cleared :-) Closing this now.
