### ISSUE TITLE
Display for funder in the metadata panel

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#208]
We would like `<funder>` elements in the `<titleStmt>` of files to show up in the metadata panel on the website. Janelle wants it to be second last in the metadata panel, immediately above the license.

**Comment by martindholmes** [comment]
Fixed in rev 17364. If all looks good, this can be closed.

**Comment by LEMDO-PM** [comment]
![image](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/9f53a89a-11e8-4438-bc12-e295c5619ca7)
Is it possible to make each `<funder>` show up on its own line?

**Comment by JanelleJenstad** [comment]
Agreed that we need a new line for each funder.

**Comment by martindholmes** [comment]
Fix committed in rev 17439. Look at emdFBFB_M to confirm.

**Comment by LEMDO-PM** [comment]
Looks great! Thanks :) I'll close this now.
