### ISSUE TITLE
Write schematron to prevent block quotations outside paragraphs.

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#21]
The issue: Some files (esp. critical paratexts that were first encoded in XWiki markdown) have this structure:

`<p>`Intro to quotation.`</p>`
`<cit><quote/><bibl/></cit>`
`<p>`Commentary on quotation`</p>`

It's valid TEI, so there's nothing in the schema that prevents this encoding. But block quotations should really be inside paragraphs, with a proper introduction to the quotation and a following sentence or two of analysis. 

Schematron would enforce this encoding model:

`<p>`Intro to quotation.
`<cit><quote/><bibl/></cit>`
Commentary on quotation`</p>`

I'm not sure how to construct the Schematron rule. Perhaps `<cit>` must be a child of `<p>` in `ldt:ldtBornDigParatext`

Schematron message to read: "Block quotations must be contained inside paragraph (p) elements."

**Comment by martindholmes** [comment]
@JanelleJenstad there are 597 examples of cit elements interleaved with p elements -- you can use this XPath to find them:

```
//cit[quote][preceding-sibling::*[1][self::p] or following-sibling::*[1][self::p]]
```
So it's a bit early for Schematron, and perhaps even for a diagnostic. How do you want to approach this?

**Comment by JanelleJenstad** [comment]
Nicole will go through the lemdo/data/text directory to find and amend those. When she's done, we'll let you know that we're ready for a Diagnostic and possibly Schematron.

**Comment by JanelleJenstad** [comment]
Nicole is just starting on this work now.

**Comment by nvatcher** [comment]
I've finished amending those instances that the XPath found.

**Comment by JanelleJenstad** [comment]
Thanks @nvatcher! @martindholmes: We're now a GO for this bit of Schematron.

**Comment by martindholmes** [comment]
Thanks @nvatcher! Schematron added in rev 9428. Closing the ticket.
