### ISSUE TITLE
Allow TEI as child of TEI in files with target value of cat:ldtPrimaryParatext

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#210]
To implement the idea of having multiple child `<TEI>` elements to accommodate the multiple paratexts in a playbook, we will need to allow `<TEI>` as a child of `<TEI>` in files with a `<catRef>` `@target` value of `cat:ldtPrimaryParatext`. 

Please let me help when you update the ODD file. This update strikes me as being interestingly unstraightforward. :-)

**Comment by martindholmes** [comment]
@JanelleJenstad There's actually no need to change the schema; we never disallowed this in the first place. The big problems here, as usual, are usage/documentation, and rendering. :-)

**Comment by JanelleJenstad** [comment]
It came up as invalid when I tried it last week. I just tried again and it's fine. Sorry! I'm closing this ticket. Will open another one for processign when the time is right.
