### ISSUE TITLE
Need a focus style for main menu items

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#212]
@pszpak and I noticed that although the main menu items are focusable, they don't have a focus style, so you can't tell you're tabbing through them. Another useful feature would perhaps be a skip-to-content link.

**Comment by pszpak** [comment]
Committed a change. Should be there on next successful build.

**Comment by pszpak** [comment]
The skip link stuff I'll do tomorrow.

**Comment by martindholmes** [comment]
@pszpak Check with @Navarra-Houldin to see the tab behaviour in Firefox on the Mac. It's tabbing through the menus, then up to the browser UI components, then back down to the menu, and so on; no way to tab through the anchors. I hope we don't have to add a tab index attribute to every anchor; that'll bump the page-weight considerably.

**Comment by pszpak** [comment]
This is because macOS does not enable keyboard navigation by default. Settings > Keyboard navigation.

<img width="722" alt="Screenshot 2024-04-24 at 9 24 10 AM" src="https://github.com/projectLEMDO/lemdoIssues/assets/18728777/d329968c-0013-4e74-b558-c5114707d6c9">

**Comment by pszpak** [comment]
This is a system wide setting, however, it can be enabled just in safari (but only safari):

<img width="830" alt="Screenshot 2024-04-24 at 9 35 55 AM" src="https://github.com/projectLEMDO/lemdoIssues/assets/18728777/e0f35810-4481-4174-aea7-00f087a4c394">

**Comment by pszpak** [comment]
Chrome has it enabled by default. For some reason Firefox depends on the system wide setting.

**Comment by martindholmes** [comment]
I was able to get Firefox to work properly on the Mac using Firefox's own settings. But I think it's fair to say that anyone who depends on keyboard navigation is going to have these settings turned on already. I think we can close this now.
