### ISSUE TITLE
Add beta watermark to documentation files

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#217]
Because we'll be publishing a beta site with some documentation still under review, we want to add an `@ana` value (I would propose `"beta"`) to put on all documentation that is still under review. We then want that ana value to trigger a beta watermark.

This one is fairly urgent, as we want to release LEMDO Beta on May 7.

Once we have the value, I'll add it to all of our documentation files (excluding the ones that are completely done).

**Comment by martindholmes** [comment]
I've made a start on this, but for some reason the `@ana` values are being lost in the build process for most documents, and I'm not sure why. Once that's solved, the solution (add 'draft' to `@ana`) will work.

**Comment by martindholmes** [comment]
Working as of rev 17480. Close if no further tweaks required.

**Comment by LEMDO-PM** [comment]
Looks great!
