### ISSUE TITLE
Fix right-inline styling in semi-diplomatic transcriptions

### ISSUE THREAD

**Issue by mahaylagalliford** [projectLEMDO/lemdoIssues#219]
As discussed in a meeting today, in the semi-diplomatic transcriptions of the folio texts, the value `plc-right-inline` on the `stage` element is not rendering where we want it. The two texts I have been remediating and proofing (Mac_F1 and JC_F1) have instances of this issue. 
Please update the styling to reflect the encoding.

**Comment by LEMDO-PM** [comment]
add margin-top: -1.8rem to styling for place*="right"

**Comment by mahaylagalliford** [comment]
From JC_F1.
![GitHub_issue_jenkins](https://github.com/projectLEMDO/lemdoIssues/assets/112907741/6fb91486-2700-4d86-81ad-bb513c413691)

**Comment by mahaylagalliford** [comment]
plc-centre is also rendering on its own line even without an `<lb>`.
![Screenshot 2024-05-09 at 12 06 10 PM](https://github.com/projectLEMDO/lemdoIssues/assets/112907741/278c801e-71d4-4713-b31e-58a0f58b1912)

**Comment by martindholmes** [comment]
@mahaylagalliford You can only centre something if it's in a line by itself; if it's in amongst other pieces of text on a line, then it's not centred in the justification sense of the word. it probably just has left and right margins that place it in a particular location in the line.

**Comment by LEMDO-PM** [comment]
No worries, I've got a plan for this. We want something that looks similar to what people expect based on where things show up in the text block of the original book. The semi-dip.scss file is my next priority.

**Comment by LEMDO-PM** [comment]
Should be done
