### ISSUE TITLE
Include funder element in header module

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#22]
For some editions, we need to indicate in the XML the source of the funding (e.g., SSHRC). The obvious way to do it is to use the TEI `<funder>` element, which is designed precisely for this purpose. (Whether or not we display this information in the edition metadata is an open question. @JanelleJenstad will follow up later.)

```
<!--MODULE: HEADER-->
                  <moduleRef key="header"
                             include="abstract authority availability biblFull catDesc catRef category change classDecl distributor edition editionStmt editorialDecl encodingDesc fileDesc handNote idno licence listChange listPrefixDef normalization notesStmt prefixDef profileDesc projectDesc publicationStmt rendition revisionDesc seriesStmt sourceDesc sponsor tagsDecl taxonomy teiHeader textClass titleStmt"/>
```
Add `<funder>` to this list in ODD file and regen schemas.

**Comment by martindholmes** [comment]
@JanelleJenstad I saw this while I was working on the schema and just implemented it so it's done. The wrinkle is that if you want to use `<funder>` in `<editionStmt>`, you must have an `<edition>` element preceding it; you can't mix `<p>` or `<ab>` elements with `<funder>`. It's one of those content models where you get either a stricter structure or a loose model.pLike collection, but not both. I'll leave the ticket for you to close in case there's anything else to do on it, such as documentation and examples.

**Comment by martindholmes** [comment]
@JanelleJenstad Should I close this now?

**Comment by JanelleJenstad** [comment]
Closing. Thanks for adding `<funder>` to the schema!
