### ISSUE TITLE
Douai annotation underlines don't show up on Safari

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#220]
Douai annotation underlines don't show up on Safari. They **do** show up on other browsers (we looked at Firefox and Chrome).

**Comment by martindholmes** [comment]
@comesaignol Do you want to deal with this? If not, just remove yourself from the ticket and I'll handle it.

**Comment by martindholmes** [comment]
Nothing from @comesaignol ??? Ping???

**Comment by JanelleJenstad** [comment]
@martindholmes: Let's just go ahead. @comesaignol must be busy with other things.

**Comment by martindholmes** [comment]
Fix committed in rev 18232. If all is well, close this.

**Comment by LEMDO-PM** [comment]
Looks good! Closing now
