### ISSUE TITLE
Gap not rendering correctly

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#221]
Used element `<gap>`, ellipses aren't being rendered in emdTim_M_collation

![image](https://github.com/projectLEMDO/lemdoIssues/assets/116194494/0a0949f1-5f94-45b6-aea3-9252b77da078)

**Comment by martindholmes** [comment]
Is this supposed to be a gap or a space? Rendering will depend to some extent on the attributes supplied, but of the two elements, only `<space>` has mechanisms for rendering a physical space based on the `@line`, `@unit` and `@quantity` attributes. `<gap>` will be rendered as `' […] '` if `@reason="sampling"`.

**Comment by LEMDO-PM** [comment]
It was an encoding error. The editor mentioned this at the end of the last webinar and I made the issue to remind myself to look at the encoding vs. rendering. Fixing it now!

**Comment by LEMDO-PM** [comment]
Committed
