### ISSUE TITLE
Add Schematron for trailing punctuation in name tags

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#222]
There are lots of cases of e.g. trailing commas included in `<persName>` tags; Find and fix all these, then add a Schematron rule to prevent them.

**Comment by martindholmes** [comment]
Refining this a bit, we should catch all cases of names with trailing comma, semicolon, or colon; and we should catch cases where a final period is not preceded by a capital letter (i.e. someone's initials). There are many, many bad instances to catch before we can add the Schematron. Tags such as gloss and term should also be included.

**Comment by JanelleJenstad** [comment]
Refining the refinement: 
"we should catch cases where a final period is not preceded by a capital letter (i.e. someone's initials)" -- We will have cases where `persName` wraps around names like these ones: Boba Fett, Jr. or Boba Fett, Esq.  So our rule cannot be looking for capital letters before periods.

**Comment by martindholmes** [comment]
Good point. I've added a Schematron rule to catch commas, but right now it's ignoring `<ref>` elements because there are too many existing errors to fix. We can refine later; we can probably add a bunch of different punctuation marks, even if we can't frame a rule that catches periods.

**Comment by martindholmes** [comment]
Fixed all the commas in refs. Can't auto-fix the periods, because of course there are a lot of cases where it's reasonable to have a period, such as abbreviations.

**Comment by martindholmes** [comment]
In rev 19419 I've added more Schematron and fixed one remaining case. I think we've done all we can do mechanically at this point, so I'm closing this.
