### ISSUE TITLE
For text-level diagnostics/stats, expand some abbreviations prior to doing word-counts

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#223]
These are suggested expansions to be carried out on speeches prior to doing word-counts:

~~~~~
’[Tt]is : it is
[Ii]s’t : is it
’[Tw]ould : it would
’[Tt]will : it will
’[Tt]was : it was
’[Tt]were : it were
[Ww]hat’s : what is
[Tt]hat’s : that is
[Ww]here’s : where is
[Tt]here’s : there is
[Hh]ere’s : here is
[Mm]ay’t : may it
[Ll]et’s : let us
[Aa]n’t : and it (if it?)
’[Ff]aith : in faith
’ll : \swill
i’ : in\s
i’th' : in the\s
o’th’ : of the\s
th’ : the\s
[Tt]' : to
’[Ss](blood|lids?|light|life|ave) : God's blood etc.
[Bb]’ : be
[Ww]i’ : with

’twixt, ’tween, think’st, etc. : no need to expand, because no impact on word-count.
~~~~~

**Comment by JackWilton1594** [comment]
You'll run into ambiguity with possessive 's', though it would be good to capture X's : x is/has. You may want to check the tables in the DRE Ed Guidelines under "Contractions and elisions" for further examples.

**Comment by martindholmes** [comment]
Will do. Possessives don't need expanding, and they're all ...’s or ...s’, I think -- what would they collide with?

**Comment by JackWilton1594** [comment]
They won't need expanding, but not all instances of 's' will be possessive. E.g. Harry's could be possessive or "Harry is" or "Harry has".

**Comment by martindholmes** [comment]
@JackWilton1594 I don't think there's any way to distinguish "Harry is" from "Harry's [possessive]" [possessive] without attempting to build syntax trees to parse the text, and that's not really feasible for EM English poetic texts. So you'll have to make a decision there as to whether we expand all of them to is/has or none of them. The other option would be to tag them all to indicate what the expansion is, which seems overkill really.

**Comment by JackWilton1594** [comment]
Agreed, so we'll live without is/has.

**Comment by martindholmes** [comment]
As of rev 17907, I've added the expansion of contractions prior to word-counting, and I've also added counts of distinct words as opposed to tokens. Closing this one in favour of #224.
