### ISSUE TITLE
Change Pilcrow

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#227]
Please change the pilcrow to make it more clearly a link.

Example from learn_oxygenProject

<img width="912" alt="image" src="https://github.com/projectLEMDO/lemdoIssues/assets/116194494/aad8a314-4431-4d19-939a-30a71acd6974">

**Comment by JanelleJenstad** [comment]
Pat has sent a lovely design via Teams. @pszpak: Please go ahead and implement.

**Comment by pszpak** [comment]
I've added the styling and the svg to the repo. It's also been validated. This is what needs to be changed:

What is there now:

` <a href="#learn_docPreface">¶</a>`

Replace with this pattern:

` <a href="#learn_docPreface" aria-label="Link to section">
                                    <svg class="chain-link" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 32 32" focusable="false" aria-hidden="true">
                                      <circle cx="16" cy="16" r="16" fill="#979797"/>
                                        <path stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.333 16.833a4.166 4.166 0 0 0 6.284.45l2.5-2.5a4.167 4.167 0 0 0-5.892-5.891l-1.433 1.425m1.875 4.85a4.167 4.167 0 0 0-6.284-.45l-2.5 2.5a4.167 4.167 0 0 0 5.892 5.891l1.425-1.425"/>
                                    </svg>
                                 </a>`

**Comment by martindholmes** [comment]
Added to build in rev 18063.

**Comment by martindholmes** [comment]
Working. Closing.
