### ISSUE TITLE
Make right-margin counting features in PDFs switchable... 

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#228]
...between line numbers and speech numbers. DRE intends to use ASSP-style speech numbers only, but there is some possibility that another project will want print output with line numbers.

One concern is that currently we only number every fifth speech in the margin; if we're going to remove line numbers, should we switch to numbering every speech? @JanelleJenstad @jackwilton1594 what do you think?

**Comment by martindholmes** [comment]
Fix committed in rev 18079. By default we now get ASSP with every speech number, but without line-numbering; if the flag -DnumberLines=true is passed to ant, we get the old behaviour. If nothing bad emerges, this can be closed.

**Comment by JanelleJenstad** [comment]
@JackWilton1594 Please check PDFs. If you are happy, close the ticket.

**Comment by JackWilton1594** [comment]
@JanelleJenstad Forgive my ignorance, but where (in terms of directory) is the output for the PDFs?

**Comment by JanelleJenstad** [comment]
They are in the anthologies slot on Jenkins: https://jenkins.hcmc.uvic.ca/job/LEMDO-anthologies/lastSuccessfulBuild/artifact/products/. Note that they are large PDFs and can be slow to open.

**Comment by martindholmes** [comment]
@JackWilton1594 @JanelleJenstad Are we done with this ticket?

**Comment by JanelleJenstad** [comment]
The PDFs look great to me with every speech numbered. Thanks!
