### ISSUE TITLE
Figure out cast list in semi-diplomatic

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#229]
Godly Queen Hester has a cast list on the title page, but our practice of wrapping a cast/character/actor list in ab doesn't work on title pages. Wrapping it in characterList also isn't allowed. Please look into how we want to encode cast/character/actor lists in semi-dip (note that we have successfully encoded them in MM_F1 and WT_F1 using ab, please let us know if we need to update those based on new decisions)

**Comment by JanelleJenstad** [comment]
`castList` is allowed inside `titlePart` as follows:

`<titlePage>
           <docTitle><titlePart></titlePart></docTitle>
           <titlePart>
              <castList>
                 <castGroup>
                    <castItem>The Prologue</castItem>
                    <castItem>King Ahuer</castItem>
                 </castGroup>
                 <castGroup>
                    <castItem>Pryde</castItem>
                 </castGroup>
              </castList>
           </titlePart>
        </titlePage>`

I'm happy with this encoding, but would like to add a new allowed value for `@type` on `titlePart` 
I'll loop back and add it to the ODD file.

**Comment by JanelleJenstad** [comment]
The LEMDO team has a meeting about castLists in July.

**Comment by LEMDO-PM** [comment]
Marking this as done
