### ISSUE TITLE
`<label type="heading">` should not appear in modern texts, and should not be styled

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#230]
Right now, `<label type="heading">` is used as a replacement for `<head>` in semi-dip texts; when this happens, it inherits styling from the SCSS around line 1760 which among other things upper-cases it, which is clearly wrong. At the same time, there are a few stray usages of this in modern texts, where it actually should be a `<head>` or `<trailer>`. So @Navarra-Houldin  and I suggest:

1. Fix all instances in modern texts (`//TEI[descendant::catRef[contains(@target, 'odern')]][descendant::label[@type='heading']]`).
2. Update the SCSS to remove all styling; that should be done with `<rendition>` elements, presumably, and will be different across texts.

The usage of `<label>` is rather backwards: we tend to use plain `<label>`  (without `@type`) in modernized texts for headings, and we use `<label type="heading">` in semi-dip texts where we're in theory trying to avoid categorizing this as e.g. headings. ??? We need revisit this.

**Comment by JanelleJenstad** [comment]
Reassigning to @LEMDO-PM to make sure we revisit this issue soon.

**Comment by martindholmes** [comment]
I believe this is release-blocking because it causes a misrepresentation of the typographical appearance of headings in semi-dip texts.

**Comment by martindholmes** [comment]
@JanelleJenstad @LEMDO-PM Since there's a release coming up, I think we should address this.

**Comment by LEMDO-PM** [comment]
It's on the list for DRE pre-freeze. I expect to get to this one around mid-November.

**Comment by LEMDO-PM** [comment]
@JanelleJenstad and I took a look and have decided that if something is typographically set as a heading it's fine to make the claim that it is a heading. It's no different than encoding a speech prefix as  a `<speaker>`
