### ISSUE TITLE
Standardize indents for shared lines

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#232]
Shared verse lines are tagged with `<l part="value">`. Allowed values are I, M, and F (for initial, medial, and final). We would like to standardize (or change) the way these shared lines are indented in our rendering. 

- @part="I": aligned left (as normal for verse)
- @part="M": indent one tab for each medial line, no matter how many medial parts there are
- @part="F": indent two tabs

**Comment by martindholmes** [comment]
There's no such thing as a tab in HTML, though. We'll need a value that can be used in CSS -- ems for instance.

Also, if you have (say) five parts, and you indent the fourth one three "tabs", then the final part only two, it'll look a bit weird. Wouldn't it be better to indent all medials one "tab" (5em?) and the final one two "tabs"?

**Comment by JanelleJenstad** [comment]
Yes, that's exactly what we want. All medial lines should be indented 5 em. And the final line 10 em.

**Comment by martindholmes** [comment]
Right now we have 10em for medial and 20em for final. @LEMDO-PM is editing the file right now I believe, but I'll assign it to them and they can change lines 2831 and 2835 or thereabouts when ready.

**Comment by JackWilton1594** [comment]
5 em for medials and 10 em for final lines should work.

**Comment by martindholmes** [comment]
Done in rev 18230.

**Comment by martindholmes** [comment]
I think we're done here.
