### ISSUE TITLE
DRE/NISE: padding before and after SDD on their own lines (modern text)

### ISSUE THREAD

**Issue by JackWilton1594** [projectLEMDO/lemdoIssues#234]
SDD on their own line in the modern text should have padding before and after.

Some instances are rendered nicely; here, for example, from H5:
![Screen Shot 2024-06-06 at 15 49 10](https://github.com/projectLEMDO/lemdoIssues/assets/4774420/0b17f6dd-e2e8-4649-be6d-4f717b122224)

But many others bunch too closely to the following line, as in these examples from 1HW:
![Screen Shot 2024-06-06 at 15 46 42](https://github.com/projectLEMDO/lemdoIssues/assets/4774420/303f606e-6b55-43ad-a3e0-c6b58463c410)
![Screen Shot 2024-06-06 at 15 46 14](https://github.com/projectLEMDO/lemdoIssues/assets/4774420/dae71077-2bba-4f3b-a121-31ba981a9a70)

... and/or to the previous line, as in this example from H5:
![Screen Shot 2024-06-06 at 15 50 02](https://github.com/projectLEMDO/lemdoIssues/assets/4774420/94546a42-0da5-4c60-af91-b6839da4ea61)

I think the amount of padding should be the same before/after.

**Comment by JanelleJenstad** [comment]
@LEMDO-PM: Further to our in-person discussion: if we are doing something different for entrances, let's not. Entrances should have the same padding before and after. There's no guarantee that the entrance has anything to do with the next speaker.

**Comment by LEMDO-PM** [comment]
@pszpak We want equal margin on either side of stage directions. We want to make sure that stage directions inside speeches are inline. In the HTML, the inline ones should all be `<span data-el="stage">` elements that are children of either `<div data-el="p">` or `<div data-el="l">` (or descendants of `<div data-el="sp">`).

**Comment by pszpak** [comment]
Committed to lemdo-dev.scss:

```
/*Stage direction*/
span[data-el="stage"] {
  display: block;
}

:is([data-el="p"], [data-el="sp"])>span[data-el="stage"] {
  display: inline;
}
```

**Comment by pszpak** [comment]
I'm going to close this. Let me know if it needs to be reopened if the change is not satisfactory.
