### ISSUE TITLE
DRE/NISE: shift indent for speeches in modern texts

### ISSUE THREAD

**Issue by JackWilton1594** [projectLEMDO/lemdoIssues#236]
Is it possible to shift the indent for speeches in modern texts by 1.5 or 2 ems?

**Comment by martindholmes** [comment]
@JackWilton1594 Do you mean the left margin? If so, do you mean shift it left, or right? There are consequences either way, because shifting it left leaves not enough room for the ASSP speech numbering, while shifting it right has consequences for small-form-factor devices, and would probably require all of the responsive-design CSS to be rejigged.

**Comment by JackWilton1594** [comment]
Apologies -- I meant shift it to the right just a smidge...
-- 
Dr Brett Greatley-Hirsch
Associate Professor of Renaissance Literature and Textual Studies

School of English, University of Leeds, Woodhouse Lane, Leeds LS2 9JT
...
Coordinating Editor, Digital Renaissance Editions

Co-editor, Shakespeare (Routledge)
http://www.notwithoutmustard.net

**Comment by martindholmes** [comment]
@JackWilton1594 1.5 or 2ems is quite a bit, really. In a screenshot like this:

![H5](https://github.com/projectLEMDO/lemdoIssues/assets/2412617/cb623413-f1cb-4e0e-93bf-17a366fa2d88)

the layout looks pretty good to me; is there a context in which something is overlapping? Would you want to move the entire speech including the speech number and speaker name, but not stage directions, or just the actual speech itself, leaving the speaker name and speech number as they are?

I'm just trying to get a sense of what problem we're aiming to solve.

**Comment by JackWilton1594** [comment]
Too small an indent looks like a mistake in the rendering – that it's meant to be aligned but wasn't. A slightly larger indent will also make it quicker to scan from speech to speech (granted that the a/s/sp link does some of that work). This doesn't have to be a universal fix – as long as we can style it differently for DRE/NISE, I'm satisfied.

**Comment by martindholmes** [comment]
lemdo-dev has 
~~~~~
@media only screen and (min-width: 768px) {
  span[data-el="speaker"] + div, span[data-el="speaker"] ~ div, body[data-catrefs*="Primary"] article div[data-el="label"] + div span[data-type*="entrance"] {
    padding-left: 0.5rem;
  }
}
~~~~~

which adds 0.5rem of padding to the left of each element following the speaker, meaning in the screenshot above, the speech lines. Turning that off looks OK to me; as you say, the speech link nicely delimits the speeches. Increasing it, on the other hand, makes it easier to distinguish the speech from the speaker and stage directions.

@JanelleJenstad Should we change this in lemdo-dev, and if so, do we eliminate it or make it bigger? Overriding it for DRE is easy, but if this is an improvement we should probably make it the default.

**Comment by JanelleJenstad** [comment]
Let's make it the default for lemdo-dev please.

**Comment by martindholmes** [comment]
Changed to 1rem in rev 18229.

**Comment by martindholmes** [comment]
Closing, assuming everyone is happy with this change.
