### ISSUE TITLE
Find solution to overlapping marginal stage directions

### ISSUE THREAD

**Issue by scspiteri** [projectLEMDO/lemdoIssues#240]
Some texts have stage directions on both the right and left margins. Because our rendering puts all stage directions in the right margin, they end up overlapping. We need a rendering solution for this.

![Screenshot from 2024-06-07 10-34-01](https://github.com/projectLEMDO/lemdoIssues/assets/171739042/7aaa638c-16bf-4e31-be2b-e3e0b3bfb6d3)
![Screenshot from 2024-06-07 10-33-36](https://github.com/projectLEMDO/lemdoIssues/assets/171739042/6870db6f-7263-4e23-a982-61a63ad79ff0)

**Comment by martindholmes** [comment]
We have a float colliding with absolute positioning here. I think this is one for @pszpak. This will find it:

~~~~~
search.html?q="Moste noble prynce"&Editorial Treatments=Semi-diplomatic transcription
~~~~~

**Comment by pszpak** [comment]
Is this still an issue? I'm not seeing this on the built site I just pulled from Jenkins.
<img width="814" alt="Screenshot 2024-06-10 at 8 41 17 AM" src="https://github.com/projectLEMDO/lemdoIssues/assets/18728777/6d5bbdac-371e-47f1-8068-3409a77fa8b1">

**Comment by JanelleJenstad** [comment]
I know that @LEMDO-PM did some styling for Sofia and that they have been working on the semi-dip stylesheet. I'll leave it to @LEMDO-PM to answer when they are back at work.

**Comment by martindholmes** [comment]
@LEMDO-PM Do we still need to do anything here?

**Comment by LEMDO-PM** [comment]
No, we've added inline styling. This shouldn't come up frequently, and where it does will likely be in texts that need a fair bit of inline style anyhow.
