### ISSUE TITLE
Check semi-dip SCSS for handling of choice elements

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#242]
Hi @pszpak: I believe something is wrong in @LEMDO-PM's .scss rendering of the `<choice>` element. An editor has pointed out that the semi-diplomatic file is rendering speeches on top of each other. The problem seems to occur when there is a `<choice>` element in the file, although that might be coincidental rather than causal. Would you please have a look a the .scss files for lemdo-dev? We cannot wait until @LEMDO-PM returns from holiday. Thanks!

Image below is from [emdJoc_BL.html]
![image](https://github.com/projectLEMDO/lemdoIssues/assets/5943608/be2e6fdc-7b75-4441-8931-6df777e309a0)

**Comment by pszpak** [comment]
I committed a change that makes the text no longer overlap. 
<img width="843" alt="Screenshot 2024-07-03 at 1 59 46 PM" src="https://github.com/projectLEMDO/lemdoIssues/assets/18728777/142796e1-f4dd-40d6-8d9d-c5c8e039b023">

**Comment by JanelleJenstad** [comment]
Thank you!

**Comment by pszpak** [comment]
This may have had unintended consequences elsewhere, so if are things suddenly are out of place in semi-diplomatic files this could be the culprit.

**Comment by martindholmes** [comment]
I think we would have noticed if there were any fallout from this, so I'm closing it.
