### ISSUE TITLE
Add new XSLT to Oxygen

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#245]
We have a perfectly functioning XSLT for numbering paragraphs in critical paratexts: `lemdo/code/utilities/numberParagraphs.xsl`

I'd like it to be added to the menu of transformations in Oxygen but don't know how to do that. Would you (@martindholmes) please teach me how?

**Comment by martindholmes** [comment]
I thought Navarra had already done that?

**Comment by JanelleJenstad** [comment]
Mahayla and I aren't seeing it in the Oxygen Tools menu.

**Comment by martindholmes** [comment]
There's also add_ids_to_paras.xsl -- is that different?

**Comment by JanelleJenstad** [comment]
add_ids_to_paras.xsl was written by you in Spring 2023. I've just tested it. It works. 

Navarra wrote another one in August: numberParagraphs.xsl

They both work, but neither is available in Oxygen. I'm agnostic on which one we add.

**Comment by LEMDO-PM** [comment]
I'll do this on Friday

**Comment by martindholmes** [comment]
@LEMDO-PM @JanelleJenstad I'm going to unassign myself from this ticket because I think @LEMDO-PM has it in hand.

**Comment by LEMDO-PM** [comment]
Done.
