### ISSUE TITLE
Supplied exit SDD not rendering right-aligned in Modern text

### ISSUE THREAD

**Issue by JackWilton1594** [projectLEMDO/lemdoIssues#248]
Hello hello,

There's a supplied exit SD in the Fane modern text that isn't being rendered flush right:

<img width="718" alt="Screenshot 2024-07-25 at 14 20 10" src="https://github.com/user-attachments/assets/9a5238cc-2974-47d6-abc4-53ac2b079e95">

Here's the code:
`<stage type="exit"><supplied>Exit Regera.</supplied></stage>`

Any ideas?

Thanks!
B

**Comment by JanelleJenstad** [comment]
Over to @martindholmes. Please align any `<stage>` with `@type="exit"` flush right, whether it's supplied or not.

**Comment by martindholmes** [comment]
That's a CSS thing, which Pat and Navarra have been working on. I think it should go to them.

**Comment by JanelleJenstad** [comment]
Reassigning to @pszpak and @LEMDO-PM

**Comment by pszpak** [comment]
I have it rendering like this. Is this is what you want?
<img width="751" alt="Screenshot 2024-07-31 at 2 07 42 PM" src="https://github.com/user-attachments/assets/196a53a5-b4e3-446d-84c0-25288769b52c">

**Comment by JackWilton1594** [comment]
Perfect!
-- 
Dr Brett Greatley-Hirsch
Professor of Renaissance Literature and Textual Studies

School of English, University of Leeds, Woodhouse Lane, Leeds LS2 9JT
...
Coordinating Editor, Digital Renaissance Editions

Co-editor, Shakespeare (Routledge)
http://www.notwithoutmustard.net

**Comment by pszpak** [comment]
Change committed.
