### ISSUE TITLE
PDF: Italicize the play title on the title page

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#250]
@JackWilton1594 would like to italicize the title on the title page of the PDF, and in the Table of Contents.

**Comment by JanelleJenstad** [comment]
How would we do that? Add `<hi rendition="rnd:italic">` to the part of the text node of `<title>` that we want to output in italics?

**Comment by JanelleJenstad** [comment]
It seems like a reasonable request, but there's no way for the processor to recognize titles inside the text node of the `<title>` element unless we tag them somehow.

**Comment by JanelleJenstad** [comment]
@JackWilton1594: We'll need to discuss, make a decision, and then assign the ticket back to Martin if there's anything we need him to do.

**Comment by martindholmes** [comment]
I think I can make the title italic in any specific location in the title page or preliminary material if necessary; that content is basically picked out of the metadata where it's needed. I don't think there would be any need to add tagging in the XML source.

**Comment by JanelleJenstad** [comment]
Consensus achieved: We will not italicize on title pages. Closing this ticket.
