### ISSUE TITLE
PDF: Remove the play title preceding chapter headings and running headers

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#251]
The play title is prepended to paratext titles, including the Acknowledgements, and appears in running headers; presumably it should be removed from all such contexts.

**Comment by JanelleJenstad** [comment]
Yes, it should be removed from all such contexts. We _could_ do something with the `<titleStmt>` that would allow us to indicate the title of the component in the print environment. Right now, we have `<title type="main">` for the online title and `<title type="short">` for the mobile title. Could we add `<title type="print">`?

**Comment by JanelleJenstad** [comment]
@JackWilton1594: We'll need to discuss, make a decision, and then assign the ticket back to Martin if there's anything we need him to do.

**Comment by JanelleJenstad** [comment]
Related to #256

**Comment by JanelleJenstad** [comment]
Let's get rid of the URL on the verso. Put the play title on the verso and the critical paratext title on the recto. The `<head>` element in the critical paratext _does_ not include the play title, so the action required here is _removing_ the instruction to add the play title to ther paratext title.

**Comment by martindholmes** [comment]
Done in rev 19221. @JackWilton1594 @JanelleJenstad Can you check you're seeing what you want to see once all the builds have completed?

**Comment by martindholmes** [comment]
Since no objections have come in, I'm going to close this.

**Comment by JackWilton1594** [comment]
@martindholmes In the case of AHDM, the play title is still being prepended to the Acknowledgements:
 
![Screen Shot 2024-08-22 at 10 31 17](https://github.com/user-attachments/assets/9f698e93-c79a-4d17-906f-d9b2a16664a5)

Is this because it's appearing _after_ the text?

**Comment by martindholmes** [comment]
@JackWilton1594 The title of the actual document is "An Humorous Day's Mirth: Acknowledgements". It's not being inserted by the PDF build. 

The play title is also prepended to every crit article in the H5 collection, so it appears everywhere there.

I suspect that people want that title to appear on the website so that it's clear what the article is about. If we need to use a different title for the PDF build, then we'll have to set up a system where people can provide their preferred title for the article when it becomes a PDF chapter, and then use that in the PDF build in preference to the current title. I'll raise a separate ticket for that.
