### ISSUE TITLE
PDF: Footnotes in headings

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#254]
When we originally designed the PDF, it was decided that the appearance of footnote numbers inside headings was ugly, and therefore anchors are moved outside headings early in the build process, being shown instead at the beginning of whatever the first piece of content following the heading. I think this happens around line 194 of latex_preprocess_module.xsl. @JackWilton1594 suggests reversing this policy and including footnotes in headings (the example given is Scene 1 in AHDM).

**Comment by martindholmes** [comment]
Note that simply dropping the anchors back into the header breaks the PDF build, so there's probably a considerable amount of work to do here if this policy does change.

**Comment by JanelleJenstad** [comment]
I don't recall aesthetics being the motivation for our decision to move anchors outside the headers in the LaTeX build process. There's something in LaTeX that made it difficult (perhaps impossible?) three years ago to put the note numbers on headers. If anything has changed, we should put the note numbers on the headers if possible. 

The alternative is to try to pin those annotations to a different place in the XML. For example, we could move the location information that Elly has provided to an annotation at the end of the first stage direction in a scene.

**Comment by JackWilton1594** [comment]
> The alternative is to try to pin those annotations to a different place in the XML. For example, we could move the location information that Elly has provided to an annotation at the end of the first stage direction in a scene.

Just for the print, you mean?

**Comment by JanelleJenstad** [comment]
Consensus achieved. We will use the onlineOnly and printOnly features to create two sets of notes. Any notes on `<head>` elements will have to be onlineOnly. @LEMDO-PM: Please remind @JanelleJenstad that she needs to write up some documentation for this.  

Example: 
`  <note type="annotation" target="doc:emdAHDM_M#emdAHDM_M_anc_2553" targetEnd="doc:emdAHDM_M#emdAHDM_M_anc_2554">
               <note type="label">Scene 1</note>
               <note type="commentary" subtype="onlineOnly">Setting: the private garden of Labervele’s wife, Florila. <ref target="doc:emdAHDM_emStaging#emdAHDM_emStaging_CloseWalkScenes">See a fuller discussion of the <soCalled>close walk</soCalled> scenes.</ref></note>
            </note>

            <note type="annotation" target="doc:emdAHDM_M#emdAHDM_M_anc_1" targetEnd="doc:emdAHDM_M#emdAHDM_M_anc_2">
               <note type="label">Enter</note>
               <note type="commentary" subtype="printOnly">Setting: the private garden of Labervele’s wife, Florila.</note>
               </note>`
