### ISSUE TITLE
PDF: Change rendering of ASSP references?

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#255]
@JackWilton1594 suggests:

"Rather than "ScX SpY" for internal citations, can we not use "X.SpY"? I'm just thinking ahead to other editions where they use acts as well as scenes, and "AcX ScY SpZ" looks especially clunky (as opposed to "X.Y.SpZ")"

We've had quite a lot of discussion over how to render these pointers, and made some changes very recently, so I think this is a policy decision. Any changes should also provide guidance for the alternative system which we still maintain just in case, which uses act/scene/line numbering.

**Comment by JanelleJenstad** [comment]
@JackWilton1594:  I'm agnostic. There's some logic to expanding the act/scene reference in the running header (if we can make room) and being more economical in the prose. See #256.

**Comment by JanelleJenstad** [comment]
Consensus achieved. We will leave things as they are. Stand down red alert.
