### ISSUE TITLE
PDF: Entrance SDs are wrongly indented at the beginning of scenes

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#258]
@JackWilton1594 says:

"Some entrance SDD (especially opening SDD) are indented whereas others are flush left. They should all be flush left to align with the SPP. For example AHDM Scene 9."

As far as I can see, SDs at the beginning of a scene are always indented, but those in the middle are not. It's not clear to me whether this was a design feature or is accidental, so I'm asking for consensus on this one before looking for something to change.

**Comment by martindholmes** [comment]
Added a fix in rev 19053, although we may reverse this if consensus is not in favour. It's on line 279 of latex_templates_module.xsl.

**Comment by JanelleJenstad** [comment]
I'm happy to see all SD in the modern text be aligned flush left. I'm not sure that we intended the opening SD in a scene to be indented.

**Comment by JanelleJenstad** [comment]
Assigning back to @martindholmes to implement. Please align all SD in the modern text flush left _except_ for `<stage type="exit">` which should be aligned right.

**Comment by JackWilton1594** [comment]
I think this has been fixed by the removal of the notes anchored to scene divisions that were being pushed onto the opening stage directions. For whatever reason, the floating footnote was indented. Everything looks fine now! :)
