### ISSUE TITLE
PDF: Use bold for act/scene divisions

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#259]
@JackWilton1594 suggests:

"Can we use bold weight for the act/scene divisions? "

I assume this means bold text for the Act and Scene headings. Easily done, I think, if there's a consensus.

**Comment by JanelleJenstad** [comment]
I agree, so we have achieved consensus. Please make it so.

**Comment by martindholmes** [comment]
It is so, as of rev 19109.
