### ISSUE TITLE
DRE: annotation pop-up cut-off by navigation bar

### ISSUE THREAD

**Issue by JackWilton1594** [projectLEMDO/lemdoIssues#261]
Hi team!

I've noticed that the navigation bar cuts off any annotation pop-ups (to edited text and to about pages) when scrolled to the top of the page. For example:

![Screen Shot 2024-07-31 at 11 08 34](https://github.com/user-attachments/assets/16a20f44-127f-446f-9344-14004d4e4f28)
![Screen Shot 2024-07-31 at 11 07 56](https://github.com/user-attachments/assets/27109e5b-ea2c-4b8c-954a-d895b7f8b115)

Is there a way to float the annotations above the navigation bar or, preferably, add some padding from the top of the window?

I checked, and this isn't an issue with QME.

Cheers,
Brett

**Comment by martindholmes** [comment]
I think it's just that the DRE banner is taller than the LEMDO and QME banners, so the offsets for following content will need to be adjusted. The CSS is:

top: calc(var(--topBarHeight));

so I expect the topBarHeight variable has not been overridden in the DRE CSS. @LEMDO-PM should be able to do that.

**Comment by martindholmes** [comment]
I've committed a tentative fix in rev 19374. It wasn't as simple as changing the topBarHeight variable, since that's used in all sorts of other calculations; a modification of the first grid-template-row in the page-wrapper ruleset seems to have fixed it.

**Comment by martindholmes** [comment]
@JackWilton1594 I claim this is fixed. Reopen if you still see any problems.
