### ISSUE TITLE
PDF: Add cover art to builds

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#264]
There will need to be two products from the PDF build: one will be a download-ready PDF that has the covers just inserted at the beginning and the end, and the other will be a cover-free PDF that's designed to have a proper cover with a spine, for printing. The former will be the first product. My initial thought is this:

1. Each cover is formed into an individual PDF, the front consisting of the full-page image followed by an empty page verso, and the back being the reverse. These are added to the portfolio repository with specific filenames based on the XML, so that the build can find them.
2. After the main PDF build, a second process uses a command-line too to concatenate the three PDFs.

This might be simpler that trying to integrate the full-page images into the PDF build itself, where the default margins and offsets will get in the way of running the image right to the edge, and it will make editing the images easier.

**Comment by JackWilton1594** [comment]
@martindholmes Where should I leave the front and back cover PDFs for the build? Also, naming conventions?

**Comment by martindholmes** [comment]
@JackWilton1594 Are they PDFs or images?

**Comment by JackWilton1594** [comment]
@martindholmes PDFs. Can be spreads (like attached) or individual pages (front, back, spine):

[H5-NISE.pdf](https://github.com/user-attachments/files/16566625/H5-NISE.pdf)

Will need ISBNs to generate the appropriate barcodes, of course. And to generate with or without printers' marks.

**Comment by martindholmes** [comment]
Yes, we'll need detached covers, and we'll also need the one-piece for the printer to include bleeds and crop marks. Do we have a final decision on the book size? These are the current dimensions, as agreed with the previous publisher:

paperheight=9.5in, paperwidth=6.625in, inner=0.75in, outer=0.75in, top=0.75in, textheight=7.75in

If we stick with those, we'll need crops and bleeds added outside on the print version; conventionally bleeds are 0.125in I think. For print, we'll also need to know the paper weight and get a guide from the printer to calculate the spine width based on the chosen paper weight.

**Comment by martindholmes** [comment]
I think we can ask the library to get us the isbns any time, can't we? We need to incorporate them into the front matter too. There's other metadata that's still missing from the first couple of pages.

**Comment by martindholmes** [comment]
and of course the text for the back cover too!

**Comment by JanelleJenstad** [comment]
I've just written to our copyright librarian to request ISBNs for H5, AHDM, and HW.

**Comment by JackWilton1594** [comment]
Hi @martindholmes, I've placed individual PDF pages for the covers (front, back, spine) in a directory named "covers" for each HW, H5, and AHDM. @JanelleJenstad is working on the content for the inner pages.

**Comment by martindholmes** [comment]
@JanelleJenstad @JackWilton1594 In rev 19355 I've added a build step which creates a second PDF with the covers, and it seems to be working, but it looks like these covers are not the same page size as our documents. For the H5 cover, for instance, pdfinfo tells me its dimensions are:

432 x 648 pts

which is pretty small and is not a standard paper size. Our books are building with these page dimensions:

paperheight=9.5in, paperwidth=6.625in

which themselves are not a standard paper size; I don't know where they came from originally, but presumably from a publisher at some point. We need the print publisher to specify a size for us, then we need to get all the cover images resized to match. If we ourselves are the publishers, then we need to research an appropriate page size for the content we have, which minimizes waste and therefore cost, and that means liaising with a printer.

**Comment by martindholmes** [comment]
In rev 19357, I've reconfigured our paper size to 6 x 9 for the sake of standardization, and the covers seem to match better now. Let's see how we feel about that paper size.

**Comment by JackWilton1594** [comment]
We inherited the dimensions from the (abandoned) partnership in Nevada, where (I believe) they were printing 6 x 9 and interior pages were 5.5 x 8.5 with .5" outer margins and 5/8" inner margins.

**Comment by JackWilton1594** [comment]
I'm happy to redesign the covers to suit whatever size we want or need. Just let me know :)

**Comment by martindholmes** [comment]
6x9 seems to work perfectly with the covers. Let's see what the printers have to say about paper size. I do like 6x9; it's a good compromise between readability and portability.

**Comment by martindholmes** [comment]
I think this one is done.
