### ISSUE TITLE
PDF: Replace text with LEMDO Hornbook logo on title page

### ISSUE THREAD

**Issue by JackWilton1594** [projectLEMDO/lemdoIssues#266]
Please replace the text on the title-page with the LEMDO Hornbook logo:
[hornbooks-logo-black.pdf](https://github.com/user-attachments/files/16677859/hornbooks-logo-black.pdf)

It should be (re)sized to no larger than a third of the page width and centered.

I can also supply in EPS format if preferred.

Thanks!
B

**Comment by martindholmes** [comment]
@JackWilton1594 Do you mean replace the text on the actual first page (which currently says only e.g. "Henry V"), or do you mean replace some text (which text?) on the full title page (the third page)?

**Comment by martindholmes** [comment]
In rev 19353 I've added it to the first title page, but keeping the play title as well, pending further info.

**Comment by JackWilton1594** [comment]
@martindholmes The half-title page:

![half-title](https://github.com/user-attachments/assets/0f96c321-55fc-439a-8d35-40c9a4fd7016)

**Comment by martindholmes** [comment]
Done in rev 19372. OK to close?

**Comment by JackWilton1594** [comment]
Looks good! :)
