### ISSUE TITLE
Need rendering for nested speeches

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#276]
In rev 19910, we implemented support for nested speeches in semi-dip texts (specifically, sp is now allowed as a child of sp/ab in semi-dip encoding). This will need rendering support; I think all that's required will be CSS rules that specify that such nested speeches, along with their speaker and ab child elements, are to be display: inline.

**Comment by LEMDO-PM** [comment]
Should be good :)
