### ISSUE TITLE
Fix the way that pointers to speeches in Prologue-like things render in the critical paratexts.

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#28]
Related to Issue #27. The same fix might do for both.

Fix the way that the **pointers from critical paratexts to speeches in prologue** render in the parenthetical citations. E.g., see [emdSel_staging](https://jenkins.hcmc.uvic.ca/job/LEMDO/lastSuccessfulBuild/artifact/products/qme/site/emdSel_staging.html) where it has “link” instead of Prol.#.

**Comment by martindholmes** [comment]
I think this is a red herring, just like #27: the encoding in emdSel_M appears to be wrong.
