### ISSUE TITLE
Correct use of OS in error message

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#281]
Please change this error message: "ERROR: Quotations are not allowed in text, except in OS texts. Use  the proper element (quote, q, soCalled, or title for example)."

New message: "ERROR: Quotations are not allowed in text, except in semi-diplomatic texts. Use  the proper element (quote, q, soCalled, term, or title for example)."

**Comment by martindholmes** [comment]
Done in rev 20370.

**Comment by JanelleJenstad** [comment]
Thanks!
