### ISSUE TITLE
Suppress display of short title in metadata pane. 

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#282]
Currently, we are displaying the text node of `<title type="short">` in the metadata pane with the label `Short title`

@LEMDO-PM and I are thinking that this information is not helpful, especially if we aren't doing anything with it for the mobile app. It's a holdover from the ISE's mobile title. 

Let's keep the information in the file but NOT display it in the metadata pane.

**Comment by martindholmes** [comment]
Fixed in rev 20559.
