### ISSUE TITLE
Links don't show up in some parts of metadata. Is this expected?

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#285]
In our metadata, links don't seem to appear in the Sponsor(s) or License/availability sections. They do show up in other sections (e.g., Source, Funder(s)). Is that intentional/expected?

E.g., this is what we get:
![image](https://github.com/user-attachments/assets/10088c88-25d8-46a2-958f-48fdb3c1cb68)
from this encoding:
`<availability>
               <licence from="2024-12-16" resp="pers:JENS1 pers:GREA1 pers:NEVI1 pers:MARD1" corresp="anth:dre"/>
               <licence from="2024-12-16" resp="pers:JENS1 pers:GREA1 pers:NEVI1 pers:MARD1" corresp="anth:lemdo"/>
               <p>Unless otherwise noted, intellectual copyright in DRE Anthology pages is held by the Co-Coordinating Editors, <persName ref="pers:GREA1">Brett Greatley-Hirsch</persName>, <persName ref="pers:JENS1">Janelle Jenstad</persName>, <persName ref="pers:MARD1">James Mardock</persName>, and <persName ref="pers:NEVI1">Sarah Neville</persName>. Copyright on the TEI-XML markup is held by the <orgName ref="org:UVIC1">University of Victoria</orgName> on behalf of the <orgName ref="org:LEMD1">LEMDO Team</orgName>. The content and TEI-XML markup in this file are licensed under a <ref target="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC BY-NC_ND 4.0 license</ref>. This file is freely downloadable without permission under the following conditions: (1) credit must be given to the authors/editors, DRE, and LEMDO in any subsequent use of the files and /or data; (2) this availability statement must remain in the file; (3) the content cannot be adapted or repurposed (except for quotations for the purposes of academic review and citation); and (4) commercial uses are not permitted without the knowledge and consent of the authors/editors, DRE, and LEMDO. Neither the content nor the code in this file is licensed for training large language models (LLMs); ingestion into an LLM, or any use in any artificial intelligence applications; such uses are considered to be commercial uses and are strictly prohibited.</p>
            </availability>`

**Comment by martindholmes** [comment]
Fixed in rev 20469. Sorry about that.

**Comment by martindholmes** [comment]
If nothing breaks in the next build, this can be closed.

**Comment by LEMDO-PM** [comment]
Thanks! The font is a different style and size now... is that something for you or me to take a look at?

**Comment by martindholmes** [comment]
Looks good to me. Closing.
