### ISSUE TITLE
Italicization of titles

### ISSUE THREAD

**Issue by nvatcher** [projectLEMDO/lemdoIssues#31]
Titles used as the title at the top of a page should not be italicized. For Documentation, these are the first `head` element. For other files, these are in the `front` of `text`. And for still other files, I think we might be using something from the `titleStmt`.

**Comment by JanelleJenstad** [comment]
@martindholmes: I've never liked the italicization of page titles. It's really out of step with how books and websites handle their own titles (as opposed to titles of things they cite). It was part of Pat's initial design, I think, and it's been on my mind for ages to have you or Pat change it. We can punt this one to next week's design work, though. I didn't know if it was a processing thing or a design thing.

**Comment by martindholmes** [comment]
@JanelleJenstad It was a design decision, and if you just turn it off, the result looks really crappy. I think a different font will need to be chosen, and there's all the other stuff that will need to be tweaked, such as letter-spacing and font size. I'll assign this to Pat.

**Comment by martindholmes** [comment]
I've invited Pat to join the project so we can assign this to him.

**Comment by pszpak** [comment]
I'm on it.

**Comment by martindholmes** [comment]
@pszpak @nvatcher Are we done with this?

**Comment by martindholmes** [comment]
OK, I'm closing this.
