### ISSUE TITLE
Punctuation after text tagged with term

### ISSUE THREAD

**Issue by nvatcher** [projectLEMDO/lemdoIssues#32]
The placement of punctuation after things encoded with `<term>` is not right. Commas and periods should be inside the added quotation marks.

Eg. https://jenkins.hcmc.uvic.ca/job/LEMDO/lastSuccessfulBuild/artifact/products/lemdo-dev/site/learn_quickStartTEI.html#learn_quickStartTEI_terminology

**Comment by martindholmes** [comment]
@nvatcher It's notoriously difficult to do this mechanically. I have code from other projects that will do it, but it means rewriting every XSL template that handles a text node to handle this special case, and realistically that's not going to happen. If you want punctuation to appear inside the term element's quotes, then put it in the term element.

As a side note, I've always thought it's both illogical and ugly for style guides to specify that punctuation should be enclosed in quotations when it's nothing to do with the quotation. It's a silly American idea which Brits don't usually adhere to (https://slate.com/human-interest/2011/05/logical-punctuation-should-we-start-placing-commas-outside-quotation-marks.html). Let's just not do it.
