### ISSUE TITLE
Documentation on quotations should link to documentation on block quotations

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#34]
learn_encodeQuotations does not mention or link to learn_blockQuotations, which means that if you end up at the former trying to figure out how to do the latter, you'll concoct a bit of a hack which will break things, as happened yesterday. These two pages should be interlinked.

**Comment by JanelleJenstad** [comment]
I've moved this documentation into the chapter on Quotations and added it to the intro page ToC. 

I'm working on revising the Quotations chapter today (inspired by this ticket). It will all be sorted out by the end of the day.
