### ISSUE TITLE
Processing of titlePage etc.

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#36]
There is a good argument for the use of the titlePage element and its descendants in modern spelling texts as a set of conceptual elements, as long as the incidental features such as linebreaks and random font size changes are not retained.

Therefore we need to fork the processing of titlePage etc. based on the value of the tax:emdEditorialTreatments catRefs. For letOldSpelling we would keep the current processing; for letModernSpelling we would process differently, making all child elements into generic blocks. For letMixed, we would raise an error with Schematron.

**Comment by JanelleJenstad** [comment]
We need this feature for the MoMS release because mayoral pageant books have title pages that we want to retain in the modern text.

**Comment by martindholmes** [comment]
@JanelleJenstad What are the elements we want to support in titlePage in a modern text? This is what I'd suggest:

docAuthor docDate docEdition docImprint docTitle byline titlePart figure

I believe this should give all editors enough latitude to create a meaningful titlePage, and we would render all of these elements as blocks, and decide on a standard CSS ruleset for each one (so the font sizes, font styles, and alignment might differ between them, for example).

**Comment by JanelleJenstad** [comment]
pubPlace, publisher (children of docImprint, so maybe don't need to explicitly included).

**Comment by JanelleJenstad** [comment]
`<titlePage>`: center [all child elements inherit centering]
`<titlePart type="main">`: large font
All other `<titlePart>`: normal font

I wouldn't do anything else.

**Comment by martindholmes** [comment]
So the steps would be:

1. Specify the contexts in which titlePage should now be allowed.
2. Check for Schematron which would preclude the use of titlePage in these contexts.
3. Decide whether we need separate processing for letModern contexts, or whether all the differences in rendering can be handled with CSS.
4. Choose a sample file to act as a pilot for this.
5. Make any changes required to processing and/or CSS.

@JanelleJenstad, I see we have an example in emdTEMP3_M. Is this a good one to get started with?

**Comment by martindholmes** [comment]
First implementation created in rev 10177. @JanelleJenstad can you take a look at emdTEMP3_M and let me know if that looks as you imagined?

**Comment by JanelleJenstad** [comment]
Thanks @martindholmes! This implementation looks very nice! I will ask Mark Kaethler what he thinks. If he's happy, I'll close the ticket.

**Comment by martindholmes** [comment]
@JanelleJenstad any word from Mark? Can we close this?

**Comment by martindholmes** [comment]
Closing this because no response from MK.

**Comment by JanelleJenstad** [comment]
I like the new title page rendering and so does Mark. Thanks for fixing it!
