### ISSUE TITLE
Customization of att.placement and Processing of place Attribute

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#37]
For details of the Feature Request and notes on the 2022-07-19 impromptu meeting, see: https://uvic.sharepoint.com/:w:/r/sites/PRJLEMDOO/Shared%20Documents/General/4_FeatureRequests/[FeatureRequest_placeAttribute](https://uvic.sharepoint.com/:w:/r/sites/PRJLEMDOO/Shared%20Documents/General/4_FeatureRequests/FeatureRequest_placeAttribute.docx?d=wd46cf7b75cdf4059bed057ee29906caf&csf=1&web=1&e=ygYzaE).docx?d=wd46cf7b75cdf4059bed057ee29906caf&csf=1&web=1&e=ygYzaE

**Comment by JanelleJenstad** [comment]
### Teams Comment from @martindholmes:
It's slightly more complicated than we thought, and I misread the ODD file elementSpec for speaker; it doesn't have @place after all (yet).

What we have is two distinct sets of values for @place: in att.placement, there are 19 values:

top-right, top-left, top-centre, bottom-centre, bottom-left, bottom-right, margin-left, margin-right, opposite, overleaf, above, centre, right, below, left, end, inline, inspace, overwritten

and in the override on @stage, there are only 12:

margin-left, margin-right, above, centre, right, below, left, below-left, below-right, inline, inline-right, inline-left

Since @place is also used already on fw and note, we should probably attempt to unify these values into a single coherent list that will work everywhere. Do you think that's possible?

### My reply: 
 Yes, I do. One of my "to do" items is to very carefully rationalize and merge the two lists of values, changing encoding across the project as necessary. 

In the notes section of the FR, there's a list of the two lists of values (from att.placement and elementSpec for <stage>). I think the RAs and I can spend some time tomorrow in our scheduled OS meeting talking about how to rationalize the <valList>s. 

Thanks for pointing out that we need to think about @place on <fw> and <note> as well. 

Action item for @martindholmes: Make a single entry in TAXO1 using a <valItem> that is in both lists -- let's say @place="margin-right".

Once I have rationalized them all and have a complete list of values with definitions, then I'll build out the list of values in TAXO1.xml, make the changes to the already-encoded files, and let you know that we can engage the processing.

**Comment by martindholmes** [comment]
See issue #38.

**Comment by martindholmes** [comment]
@JanelleJenstad I think we got our wires crossed here; we ended up with two tickets. I've implemented and commented out an XSLT function to regenerate the values for any valList of `@place` where the valList has `@mode="replace"`, and I've also converted the largest collection of values for `@place` in the current ODD file into a taxonomy with `@xml:id="emdPlacement"`. At this point it's over to you to check and complete that taxonomy, and then to let me know so I can uncomment the processing and we can rebuild the schema from the taxonomy values.

**Comment by JanelleJenstad** [comment]
@martindholmes: Update on this ticket: The OS team and I have checked and completed the new `@place` taxonomy. We will have to do a bunch of find-and-replace things on the same day that you uncomment the processing. I suggest that we do it on a day when I'm in HCMC with at least one of @nvatcher or @Navarra-Houldin.

**Comment by martindholmes** [comment]
@JanelleJenstad Is this ticket complete now? I think the only values of `@place` now in use are those which come from the new taxonomy. I suggest we close this ticket.

**Comment by martindholmes** [comment]
@JanelleJenstad Can we close this now?

**Comment by martindholmes** [comment]
Ping @JanelleJenstad Can we close this?

**Comment by JanelleJenstad** [comment]
Yes, it's all done. Closing.
