### ISSUE TITLE
Stage directions with multiple values in `@type` may not be rendered properly

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#43]
Peter C points out that this kind of stage direction:

emdSel_M.html#emdSel_M_s5

is not rendered as it should be in italics. This is probably because it has multiple values in `@type` (which is probably not good from a TEI point of view either).

**Comment by martindholmes** [comment]
Added a fix for this in rev 9977. If it's now working, close the ticket.

**Comment by JanelleJenstad** [comment]
I can't tell if it's fixed! The whole site is looking weird and there's a stylesheet message at the top. Screenshot below. 

![image](https://user-images.githubusercontent.com/5943608/181863421-89134ac1-b869-423f-bc78-6911aa986475.png)

**Comment by martindholmes** [comment]
Fixed now, and the stage direction is correctly rendered in italics.
