### ISSUE TITLE
Fix rendering of gap element in critical paratexts.

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#47]
When an editor quotes a primary or secondary source in a critical paratext and chooses to omit some material from the quotation, our encoding protocol is this:

`<gap reason="sampling">`

At the moment, we have no rendering for this encoding. We would like to have the `gap` element replaced with `[…]` please.

Ask @Navarra-Houldin for examples if necessary.

**Comment by Navarra-Houldin** [comment]
`<gap reason="sampling">` **is** rendering as an ellipsis character in the PDF. It is **not** rendering as an ellipsis character on the website.

**Comment by martindholmes** [comment]
Fix committed in rev 10841. If all is well, this can be closed.

**Comment by martindholmes** [comment]
Looks good. Closing.
