### ISSUE TITLE
Tweak rendering of block quotations in PDF

### ISSUE THREAD

**Issue by Navarra-Houldin** [projectLEMDO/lemdoIssues#50]
Looking at the PDF of H5 we note that block quotations are not rendering consistently in the general introduction. Compare the speech that begins with "So when this loose behaviour I throw off" with the speech that begins with "On, you noble English,". The former has extra vertical space before it, but the encoding is the same for both quotations.

The quoted dialogue (beginning with "Then call we this the field of Agincourt,") is not being treated as other block quotations (the underlying encoding is different and is supposed to be different).

The placement of the `<bibl>` is inconsistent. Some render inline with the quote, some render below.

**Comment by martindholmes** [comment]
That vertical space is a very weird one; the LaTeX code I'm generating in both cases is identical, so it must be the LaTeX processor that's introducing extra vertical space. I have no idea what to do about that.

**Comment by martindholmes** [comment]
The bibls that render below the quote do so because the quote has block elements in it (sp and/or p).

**Comment by martindholmes** [comment]
I've committed a workaround for what seems to be a Xelatex bug resulting in the empty line, in rev 10659.

**Comment by martindholmes** [comment]
Closing this since it seems to be working OK now.
