### ISSUE TITLE
Add processing for emphasis in PDFs

### ISSUE THREAD

**Issue by Navarra-Houldin** [projectLEMDO/lemdoIssues#52]
While in H5_GenIntro, we noticed that `<emph>` is not doing anything in the PDF. We want material wrapped in `<emph>` to render in bold, like it does in the HTML.

**Comment by martindholmes** [comment]
@Navarra-Houldin Are you sure you want emphasis in bold? In print documents it's usually italics.

**Comment by martindholmes** [comment]
@Navarra-Houldin I've committed a fix in rev 10483 which renders emphasized text in italics. I tried bold, but it just looks wrong in a print document. We probably need a policy on this, but common advice says that if you're using a serif font (as we are in the print text), you should use italics, but if it's a sans-serif then bold may be better. Other advice says to use italics for mild emphasis and bold for strong, or not to use any emphasis at all (common advice for academic writing). @JanelleJenstad, what do you think?

**Comment by JanelleJenstad** [comment]
Oh, this solution is lovely! I hadn't thought we'd be able to render <emph> in different ways. The serif/sans-serif distinction is perfect.

**Comment by martindholmes** [comment]
I haven't implemented that; it would be really difficult to do, I think. But the PDF is almost entirely in serif anyway, so the italic default should work. If you want to implement the font distinction on the website, then it might be worth asking Pat how practical it would be.

**Comment by martindholmes** [comment]
Italics working in PDFs. Closing now; please re-open if you really think bold is better.

**Comment by Navarra-Houldin** [comment]
@martindholmes, it looks wonderful, thank you!
