### ISSUE TITLE
Question about type attribute values on stage element

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#53]
@martindholmes : You asked us not to put multiple values on `@type` on `<stage>`. For long stage directions that do multiple things, does it make sense to break them up into multiple `<stage>` elements, each with its own `@type` value? It makes sense to us as encoders, but we're wondering if your processing is expecting multiple stage directions in a row.

` <stage type="entrance">Candidoos wife, </stage><stage type="setting">in her shop,  </stage><stage type="entrance">and the
            <lb type="wln" n="1654"/>two Prentises.</stage>`

**Comment by martindholmes** [comment]
Don't nest these things. That's not the solution to this. It'll break the rendering and be impossible to process properly. And it's also not really the truth, surely? Are there such things as nested stage directions?

`@type` is by definition a single value: "Attributes using this datatype must contain a single ‘word’ which contains only letters, digits, punctuation characters, or symbols: thus it cannot include whitespace." A thing can only belong to one type. If we need multiple values, then a different attribute is required. `@ana` would be one obvious option. If you want to stick with @type, then your taxonomy will have to include individual values representing each combination which can exist, which is possibly impractical.

**Comment by JanelleJenstad** [comment]
In the example, they are not nested. They are serial stage elements. If you don't like this encoding, then I see two possibilities:
1. We create a value `"mixed"` that we can use on `@type` when the stage direction contains a number of different types. 
2. We take up your suggestion of creating combination values: entranceLocation, entranceBusiness, etc.

**Comment by martindholmes** [comment]
Sorry, I misread the code there. A sequence of distinct stage elements is fine, but stage elements are usually rendered as blocks, so these would all appear on separate lines in the modernized view. That would look a bit weird, wouldn't it?

**Comment by JanelleJenstad** [comment]
@martindholmes: Mahayla was successful in her JCURA application, which is based on a research question about stage directions. So the first part of her JCURA will be to think through `@ana` versus `@type` and make an encoding recommendation. We'll leave this ticket open while we think about it during your vacation.

**Comment by martindholmes** [comment]
Congratulations Mahayla! 

I think `@type` is very crude; it's only really useful for mutually exclusive values, but real life doesn't tend to be that simple. @ana lets you combine values from the same and different taxonomies, so you get to work out your ontologies with some subtlety and then use them however you need to.

**Comment by JanelleJenstad** [comment]
@mahaylagalliford and I are already leaning towards `@ana`
I can add it to the ODD file myself, but we probably don't have default processing for `<stage>` with an `@ana` attribute. 
We can everything ready to go (i.e., a plan for a find-and-replace) before you return from the UK.

**Comment by martindholmes** [comment]
There's a fair amount of code that'll have to change for this, because we have special attribute processing for `@type` and some convoluted CSS for the various stage types, so when you have the plan ready, we'll have to set aside a few hours to do the work.

**Comment by martindholmes** [comment]
@JanelleJenstad Where are we at with this? Is a taxonomy ready yet?

**Comment by mahaylagalliford** [comment]
@JanelleJenstad and I are still engaging with the academic scholarship around stage directions, dictionaries, and taxonomies as well as exploring potential TEI alternatives to clarify our approach to encoding stage directions in semi-diplomatic transcriptions. We are still leaning toward `@ana` at this time as it allows us more specificity. At this point in the research, we are finding many more questions than answers and therefore we are not ready to implement a taxonomy yet.

**Comment by martindholmes** [comment]
I'm going to close this ticket since it doesn't have a directly actionable component right now.
