### ISSUE TITLE
Two-line annotation rendering not quite right

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#54]
When annotations span multiple lines, the output is supposed to provide a single vertical line to the left of those lines, instead of underlining the linked text inline. This works perfectly except in the case of annotations which span only two lines; in that case, the relevant text in the first line is underlined, and the vertical line only begins to the left of the second line. See for example emdH5_FM.html#emdH5_FM_a1_s1_sp3.

**Comment by martindholmes** [comment]
On second thoughts, after looking at this, I began to wonder whether it was actually a bug; I thought that perhaps the intention was that when a block annotation begins in the middle of a line, then only that part of the line that is part of the annotation would be underlined, and then any subsequent lines would get the left-hand block line, because if both lines got the block line, then it would appear that the annotation applies to the entirety of the first line. However, that can't be the case because there are cases where the full block gets its left line even when the initial annotation anchor is not at the beginning of the line, as here:

emdH5_FM.html#emdH5_FM_a1_s1_sp12

where the annotation anchor is between "The" and "strawberry". So there's some inconsistency, and that's clearly a problem.

**Comment by JanelleJenstad** [comment]
I think it would be better to run the vertical line along the full height of the lines even if only a part of the line is annotated. The consistency will help our users and the interface itself will teach them what to expect (i.e., that a vertical line means an annotation spans a line break).

**Comment by martindholmes** [comment]
I'm sure that's the original intention, but it's just not working for some cases of two-line annotations, but not all. That's a bit puzzling. I'm going to look at it today.

**Comment by martindholmes** [comment]
I've confirmed that the difference between the processing of the two example annotations is NOT due to the fact that one is `@type='gloss'` and the other `@type='commentary'`.

**Comment by martindholmes** [comment]
The sp12 example linked above covers three lines (I didn't think it did before; maybe it has been edited). So it's no longer a good comparison. I also found a case of an annotation covering two lines which includes all of the first line and part of the second; this also suffers from the same problem in reverse (the first line gets the marginal line but the second-line fragment gets an underline):

emdH5_FM.html#emdH5_FM_a1_s2_sp10

This shows where two full lines are annotated, and the behaviour is as expected:

emdH5_FM.html#emdH5_FM_a1_s2_sp24

This is another example where the annotation begins in the middle of the first line and spans an additional two lines, and the behaviour is as expected (all three lines have the marginal stripe):

emdH5_FM.html#emdH5_FM_a2_s4_sp8

I can't find any cases of two-line annotations with one line being only partly annotated where the rendering is correct, which at least suggests that there's a single bug. So to summarize:

If anchors begin at the beginning of the first line and end at the end of the second, we see correct behaviour.
If anchors begin and end in the middle of lines but the number of lines spanned is more than two, we see correct behaviour.
If a single line has anchors at the beginning and end of it, we see correct behaviour.
But:
If an anchor begins in the middle of one line and spans to the end of the next, or begins at the beginning of one line and partially into the next, we see the error; only the complete line gets the marginal stripe, while the other gets an underline for the included words.

**Comment by martindholmes** [comment]
Fix committed in rev 10480. If all is well with Mr Jenkins, we can close this ticket.

**Comment by martindholmes** [comment]
Looks good. Closing.
