### ISSUE TITLE
Tweak Broken Link Diagnostics for Documentation Index

### ISSUE THREAD

**Issue by Navarra-Houldin** [projectLEMDO/lemdoIssues#56]
We have links to the documentation index showing up as urgent broken links in Diagnostics. Those links are rendering and functioning correctly in the HTML output. Can you please tweak diagnostics so that they don't show up as broken?

Here is an example from learn_repoStructure.xml with how they are encoded:

`<p>... For more information on our documentation, go <ref target="doc:learn_docGuide">here</ref></p>`.

Here is the diagnostics:
![image](https://user-images.githubusercontent.com/105087684/190018006-3e6c72b8-b4df-4f69-a0bb-716b1e431338.png)

**Comment by martindholmes** [comment]
Fixed in rev 10671.
