### ISSUE TITLE
Tweak processing of entrances.

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#59]
`<stage type="entrance">` is not rendering the same way as the other stage directions. Please adjust processing so that it gets the same treatment as all other stage directions.

Example:
![image](https://user-images.githubusercontent.com/5943608/191080595-bf601e2b-2cc1-4e86-b496-3c3ea8d25fd2.png)

**Comment by martindholmes** [comment]
Fix committed in rev 10666: entrances are now treated identically to exits. This seems to be a change in editorial policy, so I'm waiting for confirmation before closing the ticket.

**Comment by martindholmes** [comment]
Confirmed, so closing.
