### ISSUE TITLE
Adding `@ana` for documentation divs

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#6]
The requirement here is to make the attribute `@ana` available on the `<div>` element with multiple possible values taken from the emdAudiences taxonomy. We don't want to introduce the default `@ana` to the schema because it's then available everywhere, and we have to keep deleting it all over the place, so what I've done today is:

1. Explicitly deleted the att.global.analytic module from the schema. (It contains only `@ana`).
2. Create a new module "lemdo" in our schema where we can create custom versions of standard TEI things.
3. Added a classSpec "att.lemdoAnalyticAudience" which contains a custom `@ana` attribute whose valList is populated at schema build time from the emdAudiences taxonomy.
4. Made the `<div>` element a member of att.lemdoAnalyticAudience.

This gives us the custom `@ana` attribute on the div element, and allows us to add it to other elements if we need to, while also allowing us to create other versions of `@ana` for specific purposes as we need them.

We don't yet have any plans for how this should be processed, other than that we would like to create lists of documentation pages for each audience.

**Comment by martindholmes** [comment]
@JanelleJenstad @nvatcher Can you test this out and start adding some values so that we can experiment with processing? Also, should I be adding a Schematron rule that prevents the use of this attribute when the `<div>` element is not in a documentation file?

**Comment by JanelleJenstad** [comment]
@martindholmes: I've tested it by adding <code>@ana</code> to the root divs of 14 files. I've also added two space-separated values in two cases. Works great!

Files with <code>@ana</code> on root div:
data/documentation/
learn_BIBL1.xml
learn_accessingRepository.xml
learn_annotations.xml
 learn_anthStatus.xml
 learn_anthologies.xml
learn_anthologyAboutPages.xml
learn_apparatusIntro.xml
learn_blockQuotations.xml
learn_buildAnthology.xml
learn_convertingTCP.xml [two values]
learn_convertingTLNsToAnchors.xml [two values]
learn_docCreate.xml
learn_docEncode.xml
learn_docEncode_credit.xml

**Comment by martindholmes** [comment]
Next step: what do we do with these values?

**Comment by JanelleJenstad** [comment]
**Next obvious steps:** 

1. Add a **new search category** to lemdo-dev/site/search.html. Call it: "Documentation Audiences" and list all the values.

2. Make a pre-populated search link from each of the Quickstarts. (Is that possible? It looks to me as if the Static Search is looking for a word or phrase _in_ documents. It doesn't seem to be set up to give a list of documents that have a certain type. 

- Quickstart for Encoders (learn_quickStart_encoder) should have a search link to all the documentation with <code>@ana="encoder"</code>

-

**Comment by martindholmes** [comment]
1. Is doable, but it means there will be a filter which only applies to a subset of documents. That might be a bit confusing for users.
2. Easy -- do a search using only a filter, and copy the URL. That's your link.

**Comment by JanelleJenstad** [comment]
1. I think we can frame (1) to avoid confusion.
2. Won't that mean that we have a link from the published documentation on lemdo.uvic.ca to the Jenkins site search?

**Comment by JanelleJenstad** [comment]
We are trying to document the use of the new '@ana' values. This egXML is triggering an invalidity when we have the xmlns attribute on the root div in the example. If we remove the xmlns attribute, the example is valid. But then the example is patently wrong. '@valid' value of false/true doesn't make a difference. 

```
<div xml:id="learn_docEncode_audience_examples">
        <head>Examples</head>
       <egXML xmlns="http://www.tei-c.org/ns/Examples" valid="false">
            <div xmlns="http://www.tei-c.org/ns/1.0" xml:id="learn_HAND1" resp="or:odd_JENS1_wtm or:odd_VATC1_wtm" ana="audEncoder audEditor">
                <head>Title of Page</head>
                <p><!-- Other divs, paragraphs, and examples follow. --></p>
            </div>
        </egXML>
    </div>
```
We've left you an xml comment in learn_docEncode_audience.xml

**Comment by martindholmes** [comment]
You can't link to the Jenkins search from a document intended to be published on the site.

We should probably have a protocol for linking to a search URL which replaces all the URL component with a prefix (search:), and then consists of the (escaped) query component of the URL. That would be easy to set up.

**Comment by martindholmes** [comment]
Why re-apply the TEI namespace in the div in your example? The point of an egXML is that it moves all of the descendant elements into the example namespace. This is probably what you want:

~~~~~
<div xml:id="learn_docEncode_audience_examples">
        <head>Examples</head>
       <egXML xmlns="http://www.tei-c.org/ns/Examples" valid="false">
            <div xml:id="learn_HAND1" resp="or:odd_JENS1_wtm or:odd_VATC1_wtm" ana="audEncoder audEditor">
                <head>Title of Page</head>
                <p><!-- Other divs, paragraphs, and examples follow. --></p>
            </div>
        </egXML>
    </div>
~~~~~

**Comment by JanelleJenstad** [comment]
We've followed your recommendation for the encoding of our egXML. -- DONE

"We should probably have a protocol for linking to a search URL which replaces all the URL component with a prefix (search:), and then consists of the (escaped) query component of the URL. That would be easy to set up." --> Please go ahead with this :-)

On the "Search" page, we suggest a box that says "Search Documentation Only." Put the drop-down menu for audience types in that box. I think that will be very clear.

**Comment by martindholmes** [comment]
OK, I'll set up the search. But as soon as I've created that search control, any documentation files which don't contain `@ana` attributes will not show up in search results. There are 180 documents without the attribute at the moment; are you OK with having them disappear from the search results when someone uses these controls, or should we wait until the `@ana` values have all been added?

**Comment by martindholmes** [comment]
On the issue of the prefixDef: having looked at it, we don't want to go there. It is straightforward if you're only using filters, as long as the filters don't happen to have spaces in their captions (many do), but for most cases the problem is that you would have to supply the contents of a query string in the pointing attribute, which leads to all sorts of issues with escaping and unescaping because that attribute data type is a xs:anyURI. I think if our purpose is to list documents or sections that match a specific `@ana`, then a conventional category listings page is the way to do it.

**Comment by nvatcher** [comment]
> OK, I'll set up the search. But as soon as I've created that search control, any documentation files which don't contain `@ana` attributes will not show up in search results. There are 180 documents without the attribute at the moment; are you OK with having them disappear from the search results when someone uses these controls, or should we wait until the `@ana` values have all been added?

Okay, let's wait until we've added those attributes. We will let you know when we've finished doing that.

**Comment by martindholmes** [comment]
@nvatcher Any progress with this?

**Comment by JanelleJenstad** [comment]
Still adding them as we go.

**Comment by martindholmes** [comment]
All root documentation divs now have `@ana`, and there's a Schematron rule requiring it. I've also updated processing to ensure they survive through to the standalone XML phase, and some code to create staticSearch meta tags from them. Now waiting to see if that works as expected, and at that point we can see how well they work in the search page.

**Comment by martindholmes** [comment]
This does not appear to be working, in that the staticSearch meta tags are not being created. Looking into it now. Looks like `@ana` attributes do not survive to the standalone XML phase.

**Comment by martindholmes** [comment]
Committed a fix for this in rev 11245. If all is well, this can be closed.

**Comment by martindholmes** [comment]
Seems to be working. Closing.
