### ISSUE TITLE
Display annotations in head elements in PDF

### ISSUE THREAD

**Issue by Navarra-Houldin** [projectLEMDO/lemdoIssues#60]
Notes in annotation files that point to anchors wrapped in the `<head>` element in modern files are not rendering in the PDF output. Please tweak so that they do show up.

Encoding in the modern file:
`<head><anchor xml:id="emdH5_FM_anc_87"/>1.1<anchor xml:id="emdH5_FM_anc_88"/></head>`

Encoding in the annotation file:
`<note type="annotation" target="doc:emdH5_FM#emdH5_FM_anc_87"
               targetEnd="doc:emdH5_FM#emdH5_FM_anc_88">
               <note type="label">1.1</note>
               <note type="gloss">Location: the royal court.</note>
</note>`

**Comment by martindholmes** [comment]
Fix committed in rev 10665: we move the footnote number to the next line of text, which is usually a stage direction. The content of head elements is constructed in PDFs, so the content which is being annotated doesn't actually exist in the output.

**Comment by martindholmes** [comment]
@Navarra-Houldin Could you take a look at the output and see if it works OK for you?

**Comment by Navarra-Houldin** [comment]
@martindholmes  It looks good to me! Thanks :)

**Comment by martindholmes** [comment]
OK, closing this. Thanks @Navarra-Houldin !
