### ISSUE TITLE
Render thumbnail page images like DVPP

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#64]
Rather than have a fancy lightbox thing as we do now (which isn't working properly), we should try following the simple approach of DVPP to load full-scale images into thumbnail sizes and then expand them on mouseover. Page-weight may be an issue, so this should be experimental, and we may have to use generated thumbnails instead.

**Comment by martindholmes** [comment]
I've implemented a quick-and-dirty version of this in revs running up to 11422, and I'll now bring in Pat to clean it up. @pszpak, take a look at emd1HW_Q1.html to see an instance. Feel free to do anything you like to make it better.

**Comment by martindholmes** [comment]
I'm going to take myself off this ticket, since it's all with Pat now.

**Comment by pszpak** [comment]
Done.

**Comment by JanelleJenstad** [comment]
Thank you!
