### ISSUE TITLE
Make XInclude for Links to Authority IDs

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#65]
Please make an XInclude to add the IDNO Authorities `<div>` in TAXO1.emd (xml:id="emdIdnoTaxonomy") to learn_editionBibliography#learn_editionBibliography_links

**Comment by martindholmes** [comment]
@LEMDO-PM Can you give me a bit more detail? I don't understand the request, and I don't think we use XInclude anywhere in the project -- I don't want to use it if we can possibly avoid it.

**Comment by LEMDO-PM** [comment]
@martindholmes We want to add a table that pulls the information from TAXO1 like we do in our taxonomies documentation chapter (for example, the table [here](https://jenkins.hcmc.uvic.ca/job/LEMDO/lastSuccessfulBuild/artifact/products/lemdo-dev/site/learn_taxoDocType.html#learn_taxoDocType_bornDigital) which is encoded like this: `<?taxonomy-table ref="ldtBornDig"?>`). That way the table stays up-to-date without us needing to go in to manually change it all the time.

**Comment by martindholmes** [comment]
Ah, that's a processing instruction. Will do.

**Comment by martindholmes** [comment]
Added in rev 11071. If all is well, we can close this.

**Comment by martindholmes** [comment]
Seems to be working. Closing this.
