### ISSUE TITLE
Marginal stage directions need to be floated right

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#67]
Both left and right marginal stage directions (@place = ('margin-left', 'margin-right') ) should be rendered floated to the right, so they don't overlap with speech numbers etc.

**Comment by martindholmes** [comment]
Note that this has been impacted by the change to the `@place` attribute; the new values would be "plc-right-margin" and "plc-left-margin". We need to be sure that we do want to move all of these over to the right, since we now also have some rules regarding where exits and entrances should be rendered, so I'm assigning this to JJ and NH to get proper guidance on it. Perhaps nothing actually needs to be done at this point.

**Comment by JanelleJenstad** [comment]
Anything with plc-left-margin should be moved to the right margin in the processing. We already have documentation for editors explaining why we shift things to the right margin.

**Comment by martindholmes** [comment]
Are we sure that entrances with plc-left-margin should be rendered in the right margin even though they're entrances?

**Comment by JanelleJenstad** [comment]
Good question. 
Anything with plc-left-margin that does _not_ have `@type="entrance"` should be rendered in the right margin. 
Anything with  `@type="entrance"` should be rendered left and aligned with the textblock, regardless of its plc- value.

**Comment by LEMDO-PM** [comment]
@martindholmes , we have decided that `@type="entrance"` should be rendered in the centre in semi-diplomatic transcriptions. We have also decided that `@place` should override `@type`.

Janelle, Mahayla, and I will look at mapping out some basic renditions for the great number of `@place` values and will send those to you and Pat when we are done doing so.

**Comment by pszpak** [comment]
Can you tell me what the code of the built element will look like and point me to a page where I can see the html for these elements? For example:

`<div data-el="salute">`

Is the build out version for openers.

**Comment by LEMDO-PM** [comment]
These will be for semi-diplomatic transcriptions for anthologies other than MoMS (so not the biggest priority). There's an example in emdAHDM_Q1_sp90 (text reads "_Then hee / reades._") and another in emdAHDM_Q1_sp244 (text reads "_Then he of- / fereth to / draw._").

The barebones html that should be true for all of them seems to be `<span data-el="stage" data-place="plc-right-margin|plc-left-margin">`, but there are also `@class` and `@data-type` attributes that will have different value depending on the type of stage direction (e.g., business stage directions will have `@class="stage business"` and `@data-type="business"`).

**Comment by martindholmes** [comment]
@JanelleJenstad @LEMDO-PM I have no idea where this ticket is headed, if it's still relevant. Can we re-frame the request and figure out what needs to be done, if anything?

**Comment by LEMDO-PM** [comment]
@martindholmes We would like to add styling so that all `<stage>` elements with `@place="plc-right-margin"` or with `@place="plc-left-margin` to float to the right. This will only appear in semi-diplomatic transcriptions (i.e., files that have this `<catRef>`: `<catRef scheme="tax:emdEditorialTreatments" target="cat:letOldSpelling"/>`).

This is one of the tasks that is part of the semi-diplomatic transcription styling that Pat has been putting in place.

**Comment by martindholmes** [comment]
@pszpak If you go to emdAHDM_Q1.html#emdAHDM_Q1_sp90 (speech 90 in AHDM_Q1 on Jenkins) you will see a stage direction "Then hee reads", which has this structure:

~~~~~
<span data-el="stage" class="stage business" data-type="business" data-place="plc-right-margin" data-asl="0.0.104.1" data-sln="0.0.sp91.1" data-csln="sp91.1">
  Then hee
   <br><span data-el="lb" data-clb="14"></span>reades.
</span>
~~~~~

The key flags are `data-el="stage"` and `data-place="plc-right-margin"`. This combination should cause the stage element to float right.

HOWEVER (looping in @JanelleJenstad) I believe this particular example has an extra TEI lb element. The encoding is:

~~~~~
...di<g ref="g:longS">s</g>paire not of chil<pc force="weak">-</pc>
               
               <lb/>
               <stage type="business" place="plc-right-margin">
                  Then hee
                  <lb/>reades.
               </stage>
               
               <lb type="wln" n="216"/>dren, loue with the...
~~~~~

If the stage element is to be floated, there is in fact only one linebreak between chil- and dren. Can you confirm?

**Comment by JanelleJenstad** [comment]
@martindholmes: You are right about the extra <lb/>. I've removed it. Thank you for noticing!
