### ISSUE TITLE
Remove indents from verse speeches

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#69]
In modern texts, speeches encoded as verse are rendering with an indent in front of the first line. This isn't happening to prose speeches. Please change it so that there is no indent before the first line of speeches.

Here is an example from [emdSel_M 1Sp4] with an indent before the 'P':
![Selimus Indent](https://user-images.githubusercontent.com/116194494/199101032-a6a4dc20-df97-476c-ad91-29abaebec688.jpg)

It is encoded like this:
`<sp who="#emdSel_M_Mustaffa" xml:id="emdSel_M_s1_sp4">
               <speaker>Mustaffa</speaker>
               <l>Perhaps you think Mustaffa will revolt</l>
               <l>And leave your grace and cleave to Selimus,</l>`

Here is a prose speech from [emdSel_M 20Sp5] (no indent):
![Selimus No Indent](https://user-images.githubusercontent.com/116194494/199101642-9b14323d-0a9d-4211-bd95-16a1dc1a6d9a.jpg)

It is encoded link this:
`<sp who="#emdSel_M_Bullithrumble" xml:id="emdSel_M_s20_sp5">
               <speaker>Bullithrumble</speaker>
               <p>Good lord, sir, you are deceived. My name’s Master Bullithrumble. <stage type="delivery"><supplied>Aside</supplied></stage> This is some cozening conicatching crossbiter`

**Comment by martindholmes** [comment]
I believe PS has now fixed this.
