### ISSUE TITLE
Fix breaking vertical lines for annotations

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#70]
When a vertical line for an annotation goes across two speeches or across a stage direction and a speech (even if the annotation itself isn't on both the stage direction and the speech - see the first example below), the line is breaking. Please change processing so that the lines don't break.

Example from Selimus 2 Sp1 (annotation spans multiple lines, one line contains a stage direction that isn't included in the annotation itself):
![Broken vertical line](https://user-images.githubusercontent.com/116194494/199103613-99a37df3-c352-4dbd-adf2-32bccd997b62.jpg)

Example from TTR3 2 Sp28 (annotation spans across 2 speeches):
![Broken line TTR3](https://user-images.githubusercontent.com/116194494/199103955-7a0cb126-4dcf-49aa-8085-687284cd273e.jpg)

**Comment by martindholmes** [comment]
I believe this is now fixed.
