### ISSUE TITLE
Remove `<head>` from the content model of `<listBibl>`

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#71]
We would prefer that a heading for a biblio list be encoded as a head in a containing div, and not as a head inside a listBibl.

**Comment by JanelleJenstad** [comment]
@martindholmes: I've tidied the encoding and made sure there are no `<head>` elements inside `<listBibl>`. You are clear to revise the content model.

**Comment by martindholmes** [comment]
I found a bunch more this morning in 

data/anthologies/emee/entries/emee_childbirth.xml
data/anthologies/moms/credits/moms_sources.xml
data/texts/TTR3/crit/emdTTR3_Bibliography.xml

Fixed those. Now I'll make the schema change.

**Comment by JanelleJenstad** [comment]
Thanks for catching those!

**Comment by martindholmes** [comment]
Change to schema committed in rev 11248. Validated everything first, but you never know. If this build succeeds, we can close the ticket.

A bit more on the rationale here: It's never clear at what level of the document a listBibl might appear. We have a reliable system for figuring out what HTML element (or in the PDF what font size) should be generated when processing heads in divs, but allowing them in listBibl would be for greater complexity in the processing, and gain us nothing.

**Comment by martindholmes** [comment]
All looks good. Closing.
