### ISSUE TITLE
QME credits the LEMDO Team, but the ORGS file is not included in the anthology so the link fails

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#72]
Two options spring to mind:

1. Quick-and-dirty: include the ORGS file automatically.
2. Better: include orgs via a pruning process that eliminates any that are not linked in the anthology.

**Comment by JanelleJenstad** [comment]
I vote for the better option.

**Comment by martindholmes** [comment]
Initial fix committed in rev 11734. If this works, we can close the ticket, but there is some better remediation to be done in the hcmc:idSequence function, which makes simplistic assumptions about how our prefixDefs work.

**Comment by martindholmes** [comment]
This is working, so I'm closing the ticket.
