### ISSUE TITLE
Add rendering for <gloss>

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#73]
Please add quotation marks around things tagged with <gloss>, but exclude GLOSS1 from that rendering (we don't want the definitions in GLOSS1 to be wrapped in quotation marks).

**Comment by martindholmes** [comment]
There is a discussion on this ticket in Teams; it's by no means as simple as it seems, and doing what's asked on this ticket will make more things worse than things better. On pause for the moment.

**Comment by martindholmes** [comment]
Team meeting today decided on adding quotes around glosses, so I've added gloss to the same template that handles q in rev 11457. We shall see where the chips fall.

**Comment by martindholmes** [comment]
@JanelleJenstad @Navarra-Houldin Is the output working for you? Can we close the ticket?

**Comment by LEMDO-PM** [comment]
@martindholmes Yes, that looks perfect. Thanks!
