### ISSUE TITLE
Fix rendering of pointers to act/scene numbers

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#75]
When we are pointing to scenes in plays with both acts and scenes, only the scene number is rendering in the HTML (not the act and scene number). Please change rendering so that the act and scene number both appear.

Example: [https://jenkins.hcmc.uvic.ca/job/LEMDO/lastSuccessfulBuild/artifact/products/lemdo-dev/site/emdH5_GenIntro.html#emdH5_GenIntro_p9](url)

Encoding:

`<p xml:id="emdH5_GenIntro_p9">The play’s second movement (<ptr type="localCit" target="doc:emdH5_FM#emdH5_FM_a2_s2"/> to <ptr type="localCit" target="doc:emdH5_FM#emdH5_FM_a2_s4"/>) examines the immediate implications of these different perspectives on Henry, the high stakes of committing to one view of the king, and the consequences of failing to choose the right view…</p>`

**Comment by martindholmes** [comment]
This looks like a misunderstanding; everything is functioning exactly as it's designed to do. Our rules say that when you point at something using localCit, the first thing we check is whether the element pointed to has an `@n` attribute; if it does, then that attribute should be used to form the text of the link. Only if there is no `@n` attribute should the ASSP pointer be parsed to construct a full reference. In this case, the pointed-at elements have the `@n` attribute:
 
`<div type="scene" n="2" xml:id="emdH5_FM_a2_s2">`
 
`<div type="scene" n="4" xml:id="emdH5_FM_a2_s4">`
 
If I remove the `@n` attributes from the target, everything works as expected.

I remember documenting this behaviour when we originally wrote the processing; that documentation seems to have been removed, and replaced by a general exhortation to add the `@n` attribute all over the place as part of regular encoding practice. I don't know what that would be done, but if that approach is followed, assp pointer processing will give sub-optimal link text.

**Comment by martindholmes** [comment]
My comment above is just wrong; the requirement for `@n` is specifically for anything that's going to be printed, because the print output doesn't use the ASSM scheme, it relies on `@n` attributes and line numbers generated at build time. So we do need these attributes for anything intended for print. I've now modified the HTML output generation so that it only uses the `@n` attribute when it contains something more sophisticated than a simple number, which I think should solve the problem.
