### ISSUE TITLE
Suppress examples coming from TEI into LEMDO's classSpec

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#76]
Our att.placement page ([https://jenkins.hcmc.uvic.ca/job/LEMDO/lastSuccessfulBuild/artifact/products/lemdo-dev/site/lemdo_spec_att.placement.html](url)) is pulling in examples from the TEI classSpec ([https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.placement.html](url)). These examples don't match our new vocabulary. Please suppress the incoming examples from TEI.

**Comment by martindholmes** [comment]
In rev 11382 I've switched the classSpec to `@mode="replace"` and copied in the descs from the P5 source. I think that'll do it, but we'll wait on the build to see.

**Comment by martindholmes** [comment]
Working, so closing.
