### ISSUE TITLE
Editorial Declaration gets handled differently from other metadata, with rendering consequences

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#77]
For an example, go to this page: products/moms/site/emdDEVI3_edition.html and click on About / Metadata. 

In the conversion to HTML,  `<editorialDecl>
            <p>This edition was edited according to the MoMS Editorial Guidelines.</p>
         </editorialDecl>` is turned into a `<html:div data-el="p">` because of the `<tei:p>`. The other metadata points are not wrapped in `<tei:p>` in the <tei:teiHeader> so they are just in the text node of the `<html:td>` element. And then they are subject to different rendering. 

![image](https://user-images.githubusercontent.com/5943608/202826163-df18c615-dab0-492a-a523-25026bffd0e4.png)

![image](https://user-images.githubusercontent.com/5943608/202825608-841a2e71-dbd0-47bc-b3af-247d37bcd5f2.png)

**Comment by JanelleJenstad** [comment]
Actually, Pat mentioned last week that he was going to write styling for pop-ups, so it may be that this problem is already fixed in Pat's new design.

**Comment by martindholmes** [comment]
Fixed in rev 11420. It's  not a Pat problem, it's an XSLT thing.
