### ISSUE TITLE
Display text node of editionStmt element in the metadata pane and tweak another row

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#79]
Please add a row to the metadata pane as follows:

1. label in LH column should be Edition; variable content in RH column should be drawn from the text node of `<p>` inside `<editionStmt>`

RELATED: We have a label for "Type of Text" but the RH column isn't being populated. Unless we can pull in the text node of the `<term>` element in TAXO  from tax:emdDocumentTypes, I suggest we suppress this row.

**Comment by martindholmes** [comment]
@JanelleJenstad I've implemented the editionStmt as of rev 11446. Re the "Type of text": it's trying to pull that info from `titleStmt/title[@type='alt']`. I can set it up so that it pulls from the taxonomy based on the first instance of `<catRef scheme="tax:emdDocumentTypes".../>`.

**Comment by martindholmes** [comment]
Incidentally, the labels used here in the left hand column are all hard-coded into the XSLT, which is a bad way to do things. I think we need a distinct XSLT module for captions, where they can be more easily maintained. I'll raise a ticket for that.

**Comment by JanelleJenstad** [comment]
Thank you! And thanks for noticing that we need to handle captions better.

**Comment by martindholmes** [comment]
OK, the Type of text value is now taken from the emdDocumentTypes taxonomy as of rev 11447. Closing this.
