### ISSUE TITLE
Check <elementSpec> for <ab> in lemdo.odd

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#8]
@martindholmes: We need to add a new value for `<p>`: `<p type="proseLetter`>

At the moment, there's no `<elementSpec>` for `<p>` because we just accept the incoming TEI `<elementSpec>`

I've written a tentative `<elementSpec>` in lemdo.odd and commented it out. 

Would you please check it and uncomment it if it's good to go?

**Comment by martindholmes** [comment]
@JanelleJenstad Are you sure a paragraph constitutes a prose letter? Assuming a letter is a missive, then it seems to me that it might have multiple paragraphs, rather than actual be a paragraph. Am I misunderstanding?

**Comment by martindholmes** [comment]
Also, `<p>` is not a member of att.typed, so the elementSpec as you've cast it won't work, unfortunately. We'd first have to add `<p>` to att.typed, which would be a non-compliant customization (which is OK, but worth noting), and then we could override it (and delete `@subtype` if we didn't need it). But I'm still not convinced that `<p>` is the right element here; as we've noted elsewhere, `<p>` has clear semantics, and being a letter isn't consistent with them. Should we be using `<ab>` instead?

**Comment by JanelleJenstad** [comment]
D'oh! Yes, it should be an `<ab>`. If we can get Council to allow nesting of `<ab>`, then the multiple blocks issue can be handled with `<ab>`s. 

I'll go back into the odd file and tweak `<ab>`.

**Comment by martindholmes** [comment]
When you add the attDef to the ab elementSpec, you might want to make the valList closed rather than open, otherwise people can make typos with the value and they won't get an error.

**Comment by JanelleJenstad** [comment]
`<attList>
                        <attDef ident="type">
                           <valList mode="change" type="closed">
                              <valItem ident="proseLetter">
                                 <gloss>A prose letter</gloss>
                                 <desc>Use this value to identify a prose letter in an OS or modern text.</desc>
                              </valItem>
                           </valList>
                        </attDef>
                     </attList>`

**Comment by JanelleJenstad** [comment]
Okay, I've updated lemdo.odd and committed it. Would you please check it at your convenience to make sure I've done it right?

I don't *think* we use `@type` on `ab` in any other way; if that's true, then `@mode="change"` is fine.

**Comment by martindholmes** [comment]
What you needed was just slightly different:

```
<attDef ident="type" mode="change">
                           <valList mode="add" type="closed">
                              <valItem ident="proseLetter">
                                 <gloss>A prose letter</gloss>
                                 <desc>Use this value to identify a prose letter in an OS or modern text.</desc>
                              </valItem>
                           </valList>
                        </attDef>
```

We have to use `@mode="change"` on the attribute itself, because it's already there (provided by ab's membership of att.typed), and because there is no valList in the attribute class definition of `@type`, we have to use `@mode="add"`.

But there's one further issue: we're already using `<ab type="setAsVerse">` and '`<ab type="setAsProse">` in e.g. Per and Sel; let me know whether I should add those values. Those files will be invalid if I commit the changes now.

**Comment by JanelleJenstad** [comment]
Drat! My first instinct `@mode="change"` then I went back and changed it to `@mode="add"`. Thanks for explaining!

`<ab type="setAsVerse">` and `<ab type="setAsProse">` are products of the IML-TEI conversion process. They are a means of recording temporarily the old `<MODE>` tag in IML. 

I suggest we keep them for now, but  add a `<constraintSpec>` to make them invalid in any file that doesn't have the `@status="IML-TEI"`

```
<valItem ident="setAsProse">
                                 <gloss>A stretch of text that had the MODE type of "prose" in IML. Do not use.</gloss>
                                 <desc>This value is a temporary value generated by the IML-to-TEI conversion process to capture the value of the MODE element in IML. It will be removed in the process of remediation. Do not use this value in your encoding.</desc>
                              </valItem>

<valItem ident="setAsVerse">
                                 <gloss>A stretch of text that had the MODE type of "verse" in IML. Do not use.</gloss>
                                 <desc>This value is a temporary value generated by the IML-to-TEI conversion process to capture the value of the MODE element in IML. It will be removed in the process of remediation. Do not use this value in your encoding.</desc>
                              </valItem>
                         
```

**Comment by martindholmes** [comment]
Turns out we have more values to worry about:
```
<ab style="position: relative; margin-top: 2em;" type="hungword">
               <stage type="exit">
                  <hi rendition="rnd:italic">(Exit Casbie</hi>.</stage>
            </ab>
```
(TTR3_Q1)

```
<ab type="literaryDivision">1.2</ab>
```
(Lr_FM and elsewhere)

**Comment by martindholmes** [comment]
@JanelleJenstad What I've done so far is to add the remaining values (hungword, literaryDivision, song) to the schema so that files are not invalid. I've also added a Schematron rule that catches legacy values when they're used on documents which are not IML-TEI (see below). However, I've had to comment it out because lots of documents use them. We'll have to decide how to handle this.

Schematron:

```
                      <constraint>
                           <sch:pattern>
                              <sch:rule context="tei:TEI[descendant::tei:revisionDesc/@status ne 'IML-TEI']/descendant::tei:ab[@type]">
                                 <sch:assert test="not(@type=('setAsProse', 'setAsVerse', 'hungword', 'literaryDivision', 'song'))">
                                    ERROR: The legacy values 'setAsProse', 'setAsVerse', 'hungword', 'literaryDivision', 'song'
                                    may only be used on ab/@type in documents whose status is IML-TEI.
                                 </sch:assert>
                              </sch:rule>
                           </sch:pattern>
                        </constraint>
```
Broken docs:

Sel_M
Per_Appolonius
FV_Q1
TTR3_Q1

**Comment by JanelleJenstad** [comment]
This is an excellent example of what Alexander Pope meant:

> A little learning is a dangerous thing ;
> Drink deep, or taste not the Pierian spring :
> There shallow draughts intoxicate the brain,
> And drinking largely sobers us again.

I will keep learning how to write ODD files. 

Meanwhile, I'm going to have a look at the broken docs you listed above.

**Comment by JanelleJenstad** [comment]
I have remediated the 22 instances of `<ab type="literaryDivision">` and REMOVED the `<valItem ident="literaryDivision"> `from the ODD file. 

One down...

**Comment by JanelleJenstad** [comment]
I'll press on with this one.

**Comment by martindholmes** [comment]
@JanelleJenstad @nvatcher  There are 24 remaining cases of ab[@type=('hungword', 'literaryDivision', 'song')]. Is anyone working on these?

**Comment by JanelleJenstad** [comment]
@JanelleJenstad: Get working on this :-)

**Comment by martindholmes** [comment]
@JanelleJenstad Should we just close this?

**Comment by JanelleJenstad** [comment]
No. Let's reassign to @LEMDO-PM, who is good at working these sorts of things into their workflow.

**Comment by LEMDO-PM** [comment]
I've fixed the four instances of <ab type="song"> that I found, but I didn't come across any instances of @type="literaryDivision" or "hungword". Does that seem right? I expect that people have been removing them as they remediate.

**Comment by martindholmes** [comment]
These remain:

emd3LL_Q1: hungword
emdAWW_F1: setAsProse, setAsVerse
emdDaP_Q1: hungword
emdHam_F1: setAsVerse
emdHam_Q1M: setAsProse
emdLC_Q1: hungword
emdLLL_Q1: hungword
emdLr_F1: setAsProse, setAsVerse
emdLr_Q1: setAsVerse
emdOWT_Q1: setAsVerse
emdPP_O2: hungword
emdR3_Q1: hungword
emdTro_Q1: hungword
emdWiv_F1: setAsProse, setAsVerse
emdWiv_Q1: hungword
emdWoB_Q1: hungword

(XPath: `for $t in //TEI[descendant::ab[@type=('setAsProse', 'setAsVerse', 'hungword', 'literaryDivision', 'song')]] return concat($t/@xml:id, ': ', string-join(distinct-values($t/descendant::ab[@type=('setAsProse', 'setAsVerse', 'hungword', 'literaryDivision', 'song')]/@type), ', '))`)

**Comment by LEMDO-PM** [comment]
@martindholmes, thanks! I've just committed after fixing/removing all of them.

**Comment by martindholmes** [comment]
Replacing this confusing trail of stuff with issue #93.
