### ISSUE TITLE
Display licensing information

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#81]
All the published files are licensed and have an availability statement. For example:
` <availability>
               <licence from="2022-11-15" resp="pers:JENS1" corresp="anth:moms"/>
               <p>Intellectual copyright is held jointly by the authors, Mark Kaethler and Janelle Jenstad. The XML file is licensed under a <ref target="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC BY-NC_ND 4.0 license</ref>, which means that it is freely downloadable without permission under the following conditions: (1) credit must be given to the authors, MoMS, and LEMDO in any subsequent use of the file; (2) the content cannot be adapted or repurposed (except for quotations for the purposes of academic review and citation); and (3) commercial uses are not permitted without the knowledge and consent of MoMS, the editor, and LEMDO. This license allows for pedagogical use of the critical paratexts in the classroom.</p></availability>`
               
 At the moment, we are not displaying that information anyone. Should we add it to the bottom of the metadata panel? @LEMDO-PM? @martindholmes?

**Comment by LEMDO-PM** [comment]
Yes, I think that it would be valuable to add it to the metadata panel.

**Comment by martindholmes** [comment]
Will do.

**Comment by martindholmes** [comment]
Done in rev 11496.
