### ISSUE TITLE
Generate elementSpec and Attribute Lists

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#82]
If possible, please write processing to generate a list of all elementSpecs in learn_elementsIntro.xml and processing to generate a list of all attributes in LEMDO's attribute classes in learn_attributesIntro.xml

**Comment by martindholmes** [comment]
Notes to self: to construct the list of elements, I was initially thinking that we would need to process the sequence of `div[child::head = 'Elements']/child:div[@type='refdoc']` items in the lemdo.lite.odd intermediate file; each of these defines a single element, so the list can be constructed from that collection. It is already processed in `documentation_to_elements_master.xsl`, but that may not be the ideal place to do this secondary process, which I think will have to be based on a processing-instruction. The lemdo.lite.odd file is not tracked in svn (quite rightly), so we may have to make this process a feature of the schema build process, injecting the results directly into the documentation source file. For attribute classes, we would similarly need to process `div[child::head = 'Attribute classes']/child:div[@type='refdoc']`.

However, the TEI Guildelines generates these lists using:

`tei:divGen[@type = 'elementcat']`
`tei:divGen[@type = 'attcat']`

each of which is processed by a template in common_tagdocs.xsl. So if we are able to add these to an appendix in our own ODD file, we may get these catalogues automatically, in some form or other. They might well require post-processing, but we can try it and see.

**Comment by martindholmes** [comment]
Did an initial test of `divGen[@type='attcat']` in rev 11689, but I'm expecting the result to be a bit of a mess.

**Comment by martindholmes** [comment]
I don't believe this approach will actually work in our context because of the complexity of our documentation processing. It might be cleaner to generate this content directly from the RELAXNG file.

**Comment by JanelleJenstad** [comment]
Thanks for trying it! If we can do it a different way for the LEMDO Beta release, that would be great.

**Comment by martindholmes** [comment]
Implemented based on the LEMDO RNG file today, in commits up to and including 11830. Let's see if it works OK.

**Comment by martindholmes** [comment]
I believe this is working fine, so I'm closing this.
