### ISSUE TITLE
Map current biblStruct contents onto standard LEMDO encoding

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#83]
There is some information captured in `<biblStruct>` elements in facsimiles. We want to retire the `<biblStruct>` element entirely. Janelle needs to figure out what we want instead. 
Then Martin will help Navarra figure out how to write XSLT to make this change.

**Comment by martindholmes** [comment]
@LEMDO-PM @JanelleJenstad I just checked this, and there are 72 biblStructs in the facsimiles file. All of them are in the sourceDesc of the header, and they are intended to be replaced not with bibls containing content, but with bibls pointing to entries in BIBL1. None of them seem to have enough actual information to construct a proper bibl entry in BIBL1, so I fear this may be just a grunt work thing. Here's a typical example:

~~~~~
<monogr>
                  <title>The Honest Whore, Part 1, Quarto 1</title>
                  <imprint>
                     <pubPlace>
                        <settlement>London</settlement>
                     </pubPlace>
                     <date when="1604">1604</date>
                  </imprint>
               </monogr>
            </biblStruct>
~~~~~

There's a date, a publication place, and a title. The title page of the text on the original DRE site is here:

https://digitalrenaissance.uvic.ca/doc/1HW_Q1/index.html

and it includes lots of other information we would probably need to include in a proper BIBL1 entry, including the author and the printer. So I don't think these biblStruct elements can be mechanically converted into anything useful for BIBL1.

**Comment by LEMDO-PM** [comment]
@martindholmes, @JanelleJenstad I've just finished getting rid of all `<biblStruct>` elements. There were a few that I just commented out, as they have information that we don't have encoded elsewhere (date that the work was entered in the Stationers' Registry).
