### ISSUE TITLE
Require editionStmt in files ready to be released

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#84]
For anthology diagnostics: Require that each page in an anthology have an `<editionStmt>` element containing the words "Released with"

Suggest that Martin and Navarra do this together to practice XSLT.

**Comment by LEMDO-PM** [comment]
@JanelleJenstad Martin and I took a look at this and came across some issues/questions:

1. Do we just want this in the anthology diagnostics? If so, how do we want to deal with files that are published in multiple anthologies? Martin thinks that we can require that the editionStmt includes the names of all of the anthologies that it's being released with.
2. We would like to require that it includes the full anthology name, not just the abbreviation - does that work for you?
3. We would also like to add a schematron rule requiring editionStmt with "Released with" in all files with `@status="published"`. There is currently one file in the text folder that would follow this rule and it's in the Selimus anthology (the MoMS anthology files typically say some variation of "MoMS release v.1.0").
4. Do you want to require "v." in the version number?
5. Do you want to require capitalization for "Released with"?

**Comment by LEMDO-PM** [comment]
@martindholmes , Here are our decisions on these questions:

1. We do want it in both anthology diagnostics and as a schematron rule. Yes, please require names for all anthologies.
2. Yes, require full anthology name.
3. We want to change the requirements slightly for the schematron rule: Require capital 'R' on Released, no "v." (just digits and periods), no period allowed at end of string.

I.e.,
Released with [full anthology name] 1.0

This will mean that I'll need to go in and change the `<editionStmt>` in a bunch of files, so I'll start on that tomorrow with the MoMS anthology tomorrow.

**Comment by martindholmes** [comment]
@Navarra-Houldin When you've done the data file changes, why don't you take a look in the lemdo.odd file, right at the end, and see if you can modify the Schematron we wrote yesterday to do the job? I'll take care of the anthology diagnostics. You won't be able to handle the name of the anthology in the context of the Schematron because Schematron works on a single file, not across the collection, but I can do that in the anthology diagnostics.

**Comment by martindholmes** [comment]
I've implemented the anthology diagnostics component in rev 11685. This of course causes lots of reports of errors in the QME anthology status. Not sure how you'd like to address that; do we know what version they're going to settle on?

**Comment by LEMDO-PM** [comment]
Schematron implemented in rev 11701.

**Comment by martindholmes** [comment]
@LEMDO-PM Is this now working as you expect? If so, please close the ticket.

**Comment by LEMDO-PM** [comment]
It's working! I'll close the ticket now.
