### ISSUE TITLE
Write processing for ORGS pop-ups

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#86]
We don't seem to have processing for organizations that are listed in ORGS1. We do point to organizations using the org: prefix (e.g., in running text and in respStmts). We'd like pop-ups that work like the pers: entity pop-ups.

<img width="274" alt="image" src="https://user-images.githubusercontent.com/5943608/206094936-aa139336-71db-4b8e-bb7b-871bb83c8983.png">

**Comment by martindholmes** [comment]
This is the same problem as issue #72. I've committed a fix in rev 11734. But I do notice that some orgs have virtually no info about them (SSHRC is a good example), so I think there's some work to do there. I've just added a tiny bit of info to the empty HCMC entry.

**Comment by JanelleJenstad** [comment]
I can go in and add info for all of the orgs. I've added it to my to-do list for this week.

**Comment by martindholmes** [comment]
I assume the original issue is fixed, so I'm closing this.
