### ISSUE TITLE
Add parentheses around <stage> in prose

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#87]
We would like to have parentheses around stage directions (other than entrances/exits) in speeches. Currently, there are parentheses rendering for `<stage>` elements that are children of `<l>` (i.e., verse speeches are working how we want), but not around `<stage>` elements that are children of `<p>`.

Please add processing so that `<stage>` elements (other than those with `@type="exit|entrance"`) that are descendants of `<sp>` get wrapped in parentheses regardless of if they are children of `<l>` or `<p>`.

See emd1HW_M_a1_s1_sp29 and emdH5_a2_S1_sp11 for examples.

**Comment by martindholmes** [comment]
Fix committed in rev 11737.

**Comment by martindholmes** [comment]
Seems to be working. Closing.
