### ISSUE TITLE
Some font fixing to do on lemdo-dev

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#88]
In the fonts folder, most fonts are woff2 as they should be, but these are not:

data/anthologies/lemdo-dev/site/fonts/alte-schwabacher.regular.woff
data/anthologies/lemdo-dev/site/fonts/Garamond.woff
data/anthologies/lemdo-dev/site/fonts/Lora-Regular.woff
data/anthologies/lemdo-dev/site/fonts/ui.woff

The CSS currently links to ui.woff2, which causes a 404, so that could be fixed by creating a woff2 version, adding it, and deleting the old woff version. It's not clear to me that any of the other fonts are actually being used in the CSS at all, so the first thing to do would be to check that; if they're not, they can be deleted, but if so, they should be woff2ed and linked as woff2.

**Comment by pszpak** [comment]
ui.woff2 added. Others deleted.
