### ISSUE TITLE
Make openers and closers the same font and size as other text

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#89]
Text tagged with `<opener>` and `<closer>` in editions are rendering in a different font on the site. We would like it to show up in the same font as the rest of the text. Text tagged with `<signed>` is showing up in a smaller font size. We would like it to be the same size as the rest of the text.

**Comment by pszpak** [comment]
I've committed a change that should show in the next build that styles these elements.

**Comment by LEMDO-PM** [comment]
The text for `<opener>` is working as hoped, but `<closer>` still looks different.

This is how it's encoded:
`<closer>Attending your <anchor xml:id="emdTEMP3_M_anc_428"/>lordship,<anchor xml:id="emdTEMP3_M_anc_429"/>
               <signed><ref target="mol:DEKK1">Thomas Dekker</ref>.</signed>
            </closer>`

This is how it's appearing on the site
![Closer](https://user-images.githubusercontent.com/116194494/207923097-858cc803-b01a-4d6f-9591-5cc82ecb970d.png)

**Comment by pszpak** [comment]
Should be fixed in the next build. Thanks for the screenshot.

**Comment by pszpak** [comment]
Closing assuming it's ok. Please reopen if I missed something.
