### ISSUE TITLE
Correct rendering of image width on MoMS site

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#90]
Janelle and I noticed that large images are being squished in moms_edGuide. Can you please check that the images are being scaled in rendering to fit the width of the page across the MoMS site?

**Comment by pszpak** [comment]
I'm not seeing this. Can you tell me an image specifically?

**Comment by LEMDO-PM** [comment]
img:moms_edGuide_italic.jpg (right after the `<div>` called `moms_edGuide_modernizeTypeItalics`) is one.

**Comment by pszpak** [comment]
Does this look right to you?
<img width="1082" alt="Screenshot 2022-12-14 at 3 21 01 PM" src="https://user-images.githubusercontent.com/18728777/207736513-8360cc45-6035-4e79-af92-7aee3c991c1f.png">

**Comment by LEMDO-PM** [comment]
It looks a bit squished compared to the original. I think it should be shorter vertically to keep the same scale.
![moms_edGuide_italic](https://user-images.githubusercontent.com/116194494/207736990-da5165d4-f32d-4772-8d01-877ef7a500f5.jpg)

**Comment by pszpak** [comment]
I just made a change that should makes this render properly. I'll leave this open until were sure after it builds.

**Comment by LEMDO-PM** [comment]
Great, thanks!

**Comment by LEMDO-PM** [comment]
@pszpak It looks good to me!

**Comment by martindholmes** [comment]
Do make sure this wasn't caused by an error in the original image encoding.

**Comment by LEMDO-PM** [comment]
The original encoding looks correct, Pat's new work looks good on the site.

**Comment by JanelleJenstad** [comment]
Thanks @pszpak!
