### ISSUE TITLE
Add processing for links to divs in editions

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#92]
`<ptr>` elements linking to `<div>`s in editions are rendering as "link" on the website. Can we add processing to pull in the content of the `<head>` element like we do with documentation?

There is an example in emdDEVI3_M_annotation.xml in the `<note>` with `@target="doc:emdDEVI3_M#emdDEVI3_M_anc_29" targetEnd="doc:emdDEVI3_M#emdDEVI3_M_anc_30"`. Pointer is encoded as `<ptr type="localCit" target="doc:emdDEVI3_genIntro#emdDEVI3_genIntro_hist"/>`

**Comment by martindholmes** [comment]
I think this is a new feature, so it'll have to wait for after our current release set. For the specific example you have, you could use a ref element and provide a link string.

**Comment by LEMDO-PM** [comment]
That sounds good. Thanks!

**Comment by LEMDO-PM** [comment]
Update: We only want to pull content from the `<head>` if there is no ASSp stuff.

**Comment by martindholmes** [comment]
I think this should be what is happening already. If you have examples where it's not, can you point me at one? We now have a diagnostic for any ptr that points at a div which doesn't have a usable head or ASSP id.

**Comment by LEMDO-PM** [comment]
There are two examples in emdAHDM_GenIntro_p138
![image](https://user-images.githubusercontent.com/116194494/215163032-c841056a-d958-4e06-8a0d-bf6483bb4ebd.png)
"Date" is encoded as a `<ref>` link, while the other two (rendering as "link") are encoded as `<ptr>`s.

**Comment by martindholmes** [comment]
@LEMDO-PM The link to emdAHDM_TextIntro is a link to a document, not a div; localCit is only used to point to a div or an assp component. The link to the Sources section should work, though. Looking at that now.

**Comment by martindholmes** [comment]
I believe this is working fine, so I'm closing it.
