### ISSUE TITLE
Review values of `ab/@type` and remove from schema any that are not being used

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#93]
This arises out of issue #8, which has a very confusing discussion trail, so I'm starting a new one and closing that one. I think all we need to do is what it says in the heading.

**Comment by martindholmes** [comment]
We no longer appear to have any instances of `ab/@type`, so I propose that we remove the attribute from that element completely. @JanelleJenstad, any thoughts on this?

**Comment by JanelleJenstad** [comment]
@LEMDO-PM: I note this error in our documentation (learn_encodeLettersSongs): "When encoding letters and songs, you must distinguish the two by adding the appropriate value to the @type attribute on either the `<p>`  or  `<lg>`  For example, you would wrap the lines of a verse letter in the `<lg>` element with the` @type` attribute and the value verseLetter. For songs, use song, and for prose letters, use proseLetter. `<p>` is not a member of `att.typed` so this documentation (written very early on, IIRC) is simply wrong.  Can you check our documentation to see if it mentions using `@type` on `<ab>` anywhere else?

@martindholmes: We're clear to remove `@type` from `<ab>` in the ODD file.

**Comment by martindholmes** [comment]
@JanelleJenstad We don't currently have any uses of it, but I wonder if some might appear whenever an old ISE text is imported? In other words, should I actually remove the attribute, or stick with the Schematron I've just enabled that will complain if any of the values appear in apparently-remediated texts?

**Comment by LEMDO-PM** [comment]
@JanelleJenstad: to confirm, we do not want `@type` on `<p>`. Do we want it on `<lg>` to indicate verse letters or songs? Is there any way that we **do** distinguish is the content of a `<p>` element is a prose letter?
We do document using `@type` on `<lg>` in learn_encodeModernLineation (values are "sonnet", "quatrain", "verseLetter", "song") and in learn_remediateLettersSongs. We also document using `@type` on `<p>` in learn_encodeQuotationsQuote (value is "proseLetter") and in learn_remediateLettersSongs.

**Comment by martindholmes** [comment]
@LEMDO-PM @JanelleJenstad I've now removed the type attribute from the ab element in the schema, since we have no more uses of it. At this point I believe this ticket could be closed, but since there's a question above that might still need answers, I'll just take myself off it and leave it with you. (Incidentally, note that the type attribute is not available on the  p element anyway, so I don't know how it could have ended up in the documentation.)

**Comment by LEMDO-PM** [comment]
@JanelleJenstad Are we ready to close this issue? What was the answer on `@type` on `<lg>`?

**Comment by martindholmes** [comment]
Just a note: the ab element has now been removed from sourceDesc, and all instances of it replaced with p, in case that makes any difference.

**Comment by martindholmes** [comment]
I'm closing this ticket since there doesn't seem to be any further action required.
