### ISSUE TITLE
No information on pageant author Thomas Nelson

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#94]
The author of DEVI3 has nothing in his bio on MoMS. There is a bit of info in MoEML that could be used:

(b. in or after 1580, d. in or before 1592)
Ballad writer.

**Comment by LEMDO-PM** [comment]
I will add that information to PROS1 now. We do not allow `<birth>` or `<death>` elements currently, so that will be something that we add in the future (after this release).

**Comment by LEMDO-PM** [comment]
I've added the note. Closing this now.
