### ISSUE TITLE
Link in critical intro seems a bit broken

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#95]
At the bottom of para 7 in emdDEVI3_genIntro.html, there's a link that shows as "Sp1-Sp1"; it spans two anchors, but since those anchors are both in the same speech I the two locations are rendered as the same speech. This is either a programming bug or a misunderstanding about what's supposed to happen when two anchors are both inside the same textual unit. Assigning to myself to investigate the programming issue, and to @JanelleJenstad and @LEMDO-PM  to clarify what is supposed to happen, and find examples from other texts of where it's working as expected, so we can compare them. The same thing happens in the Sp 8 link in para 8.

**Comment by martindholmes** [comment]
On thinking about this, it seems that the markup is asking for something it can't have. When we link to anchors using a localCit, the objective is to allow the processing to retrieve the most detailed reference range that's possible given the ids in the text. These links point to two anchors both of which are inside the same speech, and speeches are the lowest level of id we have, so the anchors are pointless; the links might as well point just directly to the speech, without anchors.

However, given that the anchors are there, and some future markup might provide lower-level targets, I still need to fix the processing so that it simply says "Sp1", not "Sp1 - Sp1". The remaining question is whether it makes sense at all to link to an anchor rather than to the speech. It's confusing to click on "Sp1" and be dumped into the middle of some text, especially when the actual text that matters is being quoted anyway? Shouldn't the link just be to "Sp1" and go to the beginning of the speech? The idea of linking to two anchors is really only useful if the target text crosses two lines (for the case of our print output) or if you're linking an annotation, from which linked text is to be created.

**Comment by martindholmes** [comment]
Turns out the processing isn't the problem. This is one of the links:

~~~~~
<bibl>(<ptr type="localCit" target="doc:emdDEVI3_M#emdDEVI3_M_anc_397"/>–<ptr type="localCit" target="doc:emdDEVI3_M#emdDEVI3_M_anc_398"/>)</bibl>
~~~~~

Instead of using a single pointer with `@target` and `@targetEnd`, this explicitly creates two distinct links for some reason; it's more puzzling because both links can only resolve to the same thing, Sp1, because there are no ids below that which could be used. So the markup is the problem. I think it's worth finding out what the encoder believed should happen here, but I don't see how the processing can do anything useful beyond linking to Sp1, so the problem should be fixed in the encoding.

**Comment by LEMDO-PM** [comment]
I'll go through and fix `<ptr>`s in emdDEVI3_genIntro.xml and make it so that the ones pointing to spans simply point to the speech.

**Comment by martindholmes** [comment]
I would like to know what the intention was, though, and what the expected result was.

**Comment by LEMDO-PM** [comment]
I think just confusion about linking and forgetting that we don't do line numbers in the HTML output. We'll want to talk about our linking practices (and how we want encoders to think about print/HTML while encoding) in the new year so that Janelle and I can revise and clarify the linking chapter.

**Comment by martindholmes** [comment]
There are no cases of this pattern now that I can see, so I'm closing the ticket. Thanks!

**Comment by JanelleJenstad** [comment]
That was encoded by someone new to LEMDO. It was just a mistake.
