### ISSUE TITLE
Change font of author and Editor fields to sans-serif on edition landing pages

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#96]
![image](https://user-images.githubusercontent.com/5943608/208493100-a45d6f83-a156-4868-9020-0a8f16f9d15c.png)
@pszpak: Just noticed that the words "Author" and "Editor" are showing up in a serif font on the edition landing page. Would you please tweak the rendition to make them the same as everything else on the page?

**Comment by pszpak** [comment]
Last commit should fix this.

**Comment by JanelleJenstad** [comment]
Thank you for your work on tickets today!
