### ISSUE TITLE
Mobile rendering of tables causes page to be too wide 

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#98]
I don't think @pszpak was expecting that documentation would be published as part of MoMS, and it looks like the margins and padding haven't been set up for mobile on those pages. Should be possible to do some quick fixes tomorrow pending his return.

**Comment by martindholmes** [comment]
Looking again at this today, the problem appears on pages with tables like this one:

moms/site/editions.html

where the table cannot be compressed to fit within the window.

I think the solution here (for the moment anyway) is to use the same approach I did on MoEML for tables, where they display as lists instead of tables. I'll have a go at this today.

**Comment by martindholmes** [comment]
Temporary fix committed in rev 11907; will add @pszpak to this ticket so we can review what I did. I made the fix in lemdo-dev.scss since the problem is identical on lemdo-dev.

**Comment by martindholmes** [comment]
I've improved this considerably by enhancing the XSLT output in rev 11930; the new rendering now only applies to tables which don't have any column or row spanning, because that's really fraught, and instead of displaying the thead, we now display the thead captions in the individual lists for greater clarity. I think this is done now, but @pszpak will want to take a look at the results on eg moms_editions.html and make tweaks if necessary.

**Comment by pszpak** [comment]
A robust way of dealing with tables with wide-ranging column and row counts would be to wrap all tables in a `figure` element. The table would then scroll horizontally when on a narrow viewport. This copes well with complex tables that don't lend themselves to becoming lists on mobile.

```
<figure class="fig-table">
<table> … </table>
</figure>
```

With CSS like this:

```
.fig-table {
    max-width: 100%;
    overflow-x: scroll;
}
```

**Comment by martindholmes** [comment]
@pszpak This isn't a solution really; it would require that we change the HTML of every table we generate, even if it's tiny and not going to cause a problem on mobile. It'll also cause issues around how articles number items, because traditionally tables and figures are numbered separately.

If you don't think this is a design thing, I'll try a different approach.

**Comment by pszpak** [comment]
It does deal with tables on mobile (technically tables are figures as well), but shifting the tables into lists on mobile works well enough for some kinds of tabular data - just not all of it. In my view if the data works on a list on mobile it may as well just be a list always, or perhaps a grid.

Of course recoding the build process to wrap tables in a container is not critical - especially if people are satisfied with tables as lists on mobile, our tables work with it, and it messes up other site tools (if wrapped in a figure). 

Closing this one with the css tables-to-list solution.
